In [14]:
import pandas as pd
from pathlib import Path
import numpy as np
from dataclasses import dataclass
from enum import Enum

In [2]:
class UtteranceTypes(Enum): # Not implemented yet
    CONCEDE = "___Concede___"
    RETRACT = "___Retract___"
    WHY = "___Why___"
    QUESTION = "___Question___"
    SINCE = "___Since___"
    CLAIM = "___Claim___"

In [3]:
class ModelName(Enum):
    GPT_4O = "gpt-4o"
    GROK_3 = "grok-3"
    GROK_4 = "grok-4"
    MISTRAL_MEDIUM = "mistral-medium"

In [4]:
@dataclass
class Prediction:
    label: UtteranceTypes
    prediction: UtteranceTypes
    df_row_id: int
    predictor: ModelName
    speaker: ModelName

In [33]:
utt_type_classes = []

for utt_type in UtteranceTypes:
    utt_type_classes.append(utt_type.value.replace("_","").lower())

utt_type_classes.reverse()
utt_type_classes

utt_class_indices = {k: i for i, k in enumerate(utt_type_classes)}

In [34]:
utt_class_indices

{'claim': 0, 'since': 1, 'question': 2, 'why': 3, 'retract': 4, 'concede': 5}

In [13]:
model_and_utt_type_classes = []

for model in ModelName:
    for utt_type in utt_type_classes:
        string = model.value + "_" + utt_type
        model_and_utt_type_classes.append(string)

model_and_utt_type_classes

['gpt-4o_claim',
 'gpt-4o_since',
 'gpt-4o_question',
 'gpt-4o_why',
 'gpt-4o_retract',
 'gpt-4o_concede',
 'grok-3_claim',
 'grok-3_since',
 'grok-3_question',
 'grok-3_why',
 'grok-3_retract',
 'grok-3_concede',
 'grok-4_claim',
 'grok-4_since',
 'grok-4_question',
 'grok-4_why',
 'grok-4_retract',
 'grok-4_concede',
 'mistral-medium_claim',
 'mistral-medium_since',
 'mistral-medium_question',
 'mistral-medium_why',
 'mistral-medium_retract',
 'mistral-medium_concede']

In [40]:
model_and_utt_type_indices = {k: i for i, k in enumerate(model_and_utt_type_classes)}

In [41]:
model_and_utt_type_indices

{'gpt-4o_claim': 0,
 'gpt-4o_since': 1,
 'gpt-4o_question': 2,
 'gpt-4o_why': 3,
 'gpt-4o_retract': 4,
 'gpt-4o_concede': 5,
 'grok-3_claim': 6,
 'grok-3_since': 7,
 'grok-3_question': 8,
 'grok-3_why': 9,
 'grok-3_retract': 10,
 'grok-3_concede': 11,
 'grok-4_claim': 12,
 'grok-4_since': 13,
 'grok-4_question': 14,
 'grok-4_why': 15,
 'grok-4_retract': 16,
 'grok-4_concede': 17,
 'mistral-medium_claim': 18,
 'mistral-medium_since': 19,
 'mistral-medium_question': 20,
 'mistral-medium_why': 21,
 'mistral-medium_retract': 22,
 'mistral-medium_concede': 23}

In [ ]:
utt_type_classes_counts = {} 
for model in ModelName:
    utt_type_classes_counts[model.value] = {
        "y_pred" : np.zeros(len(utt_type_classes)),
        "y_true" : np.zeros(len(utt_type_classes))
        }
utt_type_classes_counts

{'gpt-4o': {'y_pred': array([0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0.])},
 'grok-3': {'y_pred': array([0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0.])},
 'grok-4': {'y_pred': array([0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0.])},
 'mistral-medium': {'y_pred': array([0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0.])}}

{'gpt-4o_claim': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'gpt-4o_since': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'gpt-4o_question': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'gpt-4o_why': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'gpt-4o_retract': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'gpt-4o_concede': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'grok-3_claim': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'grok-3_since': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'grok-3_question': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'grok-3_why': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'grok-3_retract': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'grok-3_concede': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'grok-4_claim': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'grok-4_since': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'grok-4_question': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'grok-4_why': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'grok-4_retract': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'grok-4_concede': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'mistral-medium_claim': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'mistral-medium_since': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'mistral-medium_question': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'mistral-medium_why': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'mistral-medium_retract': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])},
 'mistral-medium_concede': {'y_pred': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]),
  'y_true': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.])}}

In [17]:
results_dir = Path() / ".." / "data" / "experiments" 
results_file = results_dir / "classification_results.csv"

df = pd.read_csv(results_file)

In [18]:
df.head()

,testset_row_index,repetition,dialogue_turn_1,dialogue_turn_2,target,label,predictor,speaker,temp,top_p,seed,classification
0,0,0,Resource misallocation is more likely in syste...,"Fairness is best achieved through efficiency, ...",Heavy oversight does not delay support; it ens...,claim,mistral-medium,gpt-4o,0,1,123,since
1,0,1,Resource misallocation is more likely in syste...,"Fairness is best achieved through efficiency, ...",Heavy oversight does not delay support; it ens...,claim,mistral-medium,gpt-4o,0,1,123,since
2,0,2,Resource misallocation is more likely in syste...,"Fairness is best achieved through efficiency, ...",Heavy oversight does not delay support; it ens...,claim,mistral-medium,gpt-4o,0,1,123,since
3,0,3,Resource misallocation is more likely in syste...,"Fairness is best achieved through efficiency, ...",Heavy oversight does not delay support; it ens...,claim,mistral-medium,gpt-4o,0,1,123,since
4,0,4,Resource misallocation is more likely in syste...,"Fairness is best achieved through efficiency, ...",Heavy oversight does not delay support; it ens...,claim,mistral-medium,gpt-4o,0,1,123,claim

In [38]:
for index, row in df.iterrows():
    predictor = row["predictor"]
    prediction = row["classification"]
    label = row["label"]

    utt_type_classes_counts[predictor]['y_pred'][utt_class_indices[prediction]] += 1
    utt_type_classes_counts[predictor]['y_true'][utt_class_indices[label]] += 1

In [39]:
utt_type_classes_counts

{'gpt-4o': {'y_pred': array([338., 100.,   5., 395., 180., 182.]),
  'y_true': array([200., 200., 200., 200., 200., 200.])},
 'grok-3': {'y_pred': array([347.,  60.,   0., 400., 185., 208.]),
  'y_true': array([200., 200., 200., 200., 200., 200.])},
 'grok-4': {'y_pred': array([293., 117.,   0., 400., 170., 220.]),
  'y_true': array([200., 200., 200., 200., 200., 200.])},
 'mistral-medium': {'y_pred': array([278., 147.,   0., 400., 152., 223.]),
  'y_true': array([200., 200., 200., 200., 200., 200.])}}

In [42]:
# Initialize the confusion matrix
conf_matrix = np.zeros((len(utt_class_indices), len(utt_class_indices)), dtype=int)

In [43]:
conf_matrix

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [44]:
# Define function to create a confusion matrix with NumPy
def confusion_matrix_np(y_true, y_pred):
    classes = np.unique(np.concatenate((y_true, y_pred)))
    conf_matrix = np.zeros((len(classes), len(classes)), dtype=int)
    class_to_index = {cls: idx for idx, cls in enumerate(classes)}
    for t, p in zip(y_true, y_pred):
        conf_matrix[class_to_index[t], class_to_index[p]] += 1
    return conf_matrix, classes

In [ ]:
from typing import List

@dataclass 
class BootstrapSampleData:
    model: str
    confusion_matrix: List[List[int]]
    f1_scores: List[float]
    macro_f1: float
    weighted_f1: float
    micro_f1:float

In [68]:
N=10

In [75]:
import json

In [76]:
results = []

for i in range(N):
    bootstrap_df = df.sample(n=len(df), replace=True)
    for model_name, group in bootstrap_df.groupby("predictor"):
        y_true = group["label"].to_numpy()
        y_pred = group["classification"].to_numpy()

        conf_matrix, classes = confusion_matrix_np(y_true, y_pred)

        TP = np.diag(conf_matrix)
        FP = np.sum(conf_matrix, axis=0) - TP
        FN = np.sum(conf_matrix, axis=1) - TP
        precision = TP / (TP + FP)
        recall = TP / (TP + FN)
        f1 = 2 * precision * recall / (precision + recall)
        f1 = np.nan_to_num(f1, nan=0.0)

        support = np.sum(conf_matrix, axis=1)
        f1_weighted = np.sum(f1 * support) / np.sum(support)

        TP_micro = np.sum(TP)
        FP_micro = np.sum(FP)
        FN_micro = np.sum(FN)

        precision_micro = TP_micro / (TP_micro + FP_micro)
        recall_micro = TP_micro / (TP_micro + FN_micro)
        f1_micro = 2 * precision_micro * recall_micro / (precision_micro + recall_micro)



        result = BootstrapSampleData(
            model=model_name, 
            confusion_matrix=conf_matrix.tolist(), 
            f1_scores=f1.tolist(), 
            macro_f1=np.mean(f1).tolist(),
            weighted_f1=f1_weighted.tolist(),
            micro_f1=f1_micro.tolist()
            )
        
        results.append(result.__dict__)

# Write to JSONL file
with open("test.jsonl", "w") as f:
    for item in results:
        f.write(json.dumps(item) + "\n")

C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4284672244.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)
C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4284672244.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)
C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4284672244.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)
C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4284672244.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)
C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4284672244.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)
C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4284672244.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)
C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4284672244.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)
C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4284672244.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)
C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4284672244.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)
C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4284672244.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)

In [74]:
results

[{'model': 'gpt-4o',
  'confusion_matrix': [[184, 0, 0, 0, 14, 0],
   [34, 159, 0, 0, 4, 0],
   [0, 0, 3, 0, 0, 186],
   [0, 17, 0, 197, 3, 0],
   [121, 0, 0, 0, 76, 0],
   [0, 0, 0, 0, 0, 191]],
  'f1_scores': [0.6852886405959032,
   0.8525469168900804,
   0.03125,
   0.9516908212560387,
   0.5170068027210885,
   0.6725352112676056],
  'macro_f1': 0.6183863987884527,
  'weighted_f1': 0.6277263390799515,
  'micro_f1': 0.6812447434819175},
 {'model': 'grok-3',
  'confusion_matrix': [[176, 0, 0, 0, 16, 0],
   [2, 210, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 216],
   [0, 14, 0, 166, 0, 0],
   [156, 0, 0, 0, 55, 0],
   [0, 0, 0, 0, 0, 209]],
  'f1_scores': [0.6692015209125475,
   0.963302752293578,
   0.0,
   0.9595375722543353,
   0.3900709219858156,
   0.6593059936908517],
  'macro_f1': 0.606903126856188,
  'weighted_f1': 0.5946914391210025,
  'micro_f1': 0.6688524590163935},
 {'model': 'grok-4',
  'confusion_matrix': [[176, 0, 0, 0, 18, 0],
   [10, 174, 0, 0, 4, 0],
   [0, 0, 0, 0, 0, 200],
   [0, 34, 0, 166, 0, 0],
   [113, 0, 0, 0, 82, 0],
   [0, 0, 0, 0, 0, 201]],
  'f1_scores': [0.7139959432048684,
   0.8787878787878788,
   0.0,
   0.9071038251366119,
   0.5484949832775919,
   0.6677740863787375],
  'macro_f1': 0.6193594527976148,
  'weighted_f1': 0.6165765809188835,
  'micro_f1': 0.6782682512733447},
 {'model': 'mistral-medium',
  'confusion_matrix': [[174, 0, 0, 0, 35, 0],
   [26, 172, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 192],
   [0, 47, 0, 172, 1, 0],
   [103, 0, 0, 0, 102, 0],
   [0, 0, 0, 0, 0, 189]],
  'f1_scores': [0.6796875,
   0.8249400479616307,
   0.0,
   0.8775510204081634,
   0.5947521865889213,
   0.6631578947368421],
  'macro_f1': 0.6066814416159262,
  'weighted_f1': 0.6147692348245596,
  'micro_f1': 0.6669414674361088},
 {'model': 'gpt-4o',
  'confusion_matrix': [[185, 0, 0, 0, 13, 0],
   [24, 182, 0, 0, 2, 0],
   [0, 0, 8, 0, 0, 202],
   [0, 12, 0, 175, 1, 0],
   [128, 0, 0, 0, 74, 0],
   [0, 0, 0, 0, 0, 174]],
  'f1_scores': [0.691588785046729,
   0.9054726368159204,
   0.07339449541284404,
   0.9641873278236914,
   0.5068493150684931,
   0.6327272727272727],
  'macro_f1': 0.6290366388158252,
  'weighted_f1': 0.6223992005617764,
  'micro_f1': 0.676271186440678},
 {'model': 'grok-3',
  'confusion_matrix': [[196, 0, 0, 0, 8, 0],
   [9, 197, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 203],
   [0, 12, 0, 181, 0, 0],
   [163, 0, 0, 0, 53, 0],
   [0, 0, 0, 0, 0, 188]],
  'f1_scores': [0.6853146853146853,
   0.9493975903614459,
   0.0,
   0.9679144385026738,
   0.38267148014440433,
   0.6493955094991364],
  'macro_f1': 0.6057822839703909,
  'weighted_f1': 0.6007694062369412,
  'micro_f1': 0.6735537190082644},
 {'model': 'grok-4',
  'confusion_matrix': [[198, 0, 0, 0, 20, 0],
   [7, 194, 0, 0, 6, 0],
   [0, 0, 0, 0, 0, 208],
   [0, 39, 0, 175, 0, 0],
   [105, 0, 0, 0, 119, 0],
   [0, 0, 0, 0, 0, 203]],
  'f1_scores': [0.7499999999999999,
   0.8818181818181817,
   0.0,
   0.8997429305912596,
   0.6449864498644986,
   0.6612377850162867],
  'macro_f1': 0.6396308912150377,
  'weighted_f1': 0.6415145886270386,
  'micro_f1': 0.6978021978021978},
 {'model': 'mistral-medium',
  'confusion_matrix': [[148, 0, 0, 0, 30, 0],
   [22, 167, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 204],
   [0, 45, 0, 151, 4, 0],
   [62, 0, 0, 0, 81, 0],
   [0, 0, 0, 0, 0, 222]],
  'f1_scores': [0.7219512195121951,
   0.8329177057356608,
   0.0,
   0.8603988603988605,
   0.6279069767441859,
   0.6851851851851851],
  'macro_f1': 0.6213933245960146,
  'weighted_f1': 0.616118260847282,
  'micro_f1': 0.6769366197183099},
 {'model': 'gpt-4o',
  'confusion_matrix': [[181, 0, 0, 0, 18, 0],
   [26, 143, 0, 0, 9, 0],
   [0, 0, 6, 0, 0, 218],
   [0, 19, 0, 184, 10, 0],
   [128, 0, 0, 0, 68, 0],
   [0, 0, 0, 0, 0, 201]],
  'f1_scores': [0.6779026217228464,
   0.8411764705882352,
   0.052173913043478265,
   0.9269521410579346,
   0.4518272425249169,
   0.6483870967741936],
  'macro_f1': 0.599736580951934,
  'weighted_f1': 0.5884754269538631,
  'micro_f1': 0.6465730800990916},
 {'model': 'grok-3',
  'confusion_matrix': [[189, 0, 0, 0, 11, 0],
   [9, 217, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 210],
   [0, 15, 0, 180, 0, 0],
   [146, 0, 0, 0, 41, 0],
   [0, 0, 0, 0, 0, 211]],
  'f1_scores': [0.6948529411764705,
   0.9475982532751092,
   0.0,
   0.9600000000000001,
   0.34309623430962344,
   0.6677215189873418],
  'macro_f1': 0.6022114912914242,
  'weighted_f1': 0.6064898533748555,
  'micro_f1': 0.6818551668022783},
 {'model': 'grok-4',
  'confusion_matrix': [[186, 0, 0, 0, 12, 0],
   [4, 214, 0, 0, 1, 0],
   [0, 0, 0, 0, 0, 197],
   [0, 22, 0, 174, 0, 0],
   [102, 0, 0, 0, 89, 0],
   [0, 0, 0, 0, 0, 188]],
  'f1_scores': [0.7591836734693878,
   0.9406593406593408,
   0.0,
   0.9405405405405405,
   0.6075085324232082,
   0.656195462478185],
  'macro_f1': 0.650681258261777,
  'weighted_f1': 0.6560702990210361,
  'micro_f1': 0.7157275021026073},
 {'model': 'mistral-medium',
  'confusion_matrix': [[158, 0, 0, 0, 32, 0],
   [20, 189, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 178],
   [0, 41, 0, 145, 8, 0],
   [81, 0, 0, 0, 123, 0],
   [0, 0, 0, 0, 0, 196]],
  'f1_scores': [0.7037861915367483,
   0.8610478359908884,
   0.0,
   0.855457227138643,
   0.670299727520436,
   0.6877192982456141],
  'macro_f1': 0.6297183800720549,
  'weighted_f1': 0.6414783971385859,
  'micro_f1': 0.6925704526046115},
 {'model': 'gpt-4o',
  'confusion_matrix': [[186, 0, 0, 0, 14, 0],
   [22, 183, 0, 0, 6, 0],
   [0, 0, 6, 0, 0, 214],
   [0, 15, 0, 159, 5, 0],
   [128, 0, 0, 0, 64, 0],
   [0, 0, 0, 0, 0, 220]],
  'f1_scores': [0.6940298507462688,
   0.8948655256723715,
   0.053097345132743355,
   0.9408284023668639,
   0.4555160142348754,
   0.672782874617737],
  'macro_f1': 0.6185200021284767,
  'weighted_f1': 0.6081698880261821,
  'micro_f1': 0.6693944353518821},
 {'model': 'grok-3',
  'confusion_matrix': [[176, 0, 0, 0, 14, 0],
   [5, 190, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 188],
   [0, 12, 0, 184, 0, 0],
   [133, 0, 0, 0, 38, 0],
   [0, 0, 0, 0, 0, 199]],
  'f1_scores': [0.6984126984126984,
   0.9571788413098237,
   0.0,
   0.968421052631579,
   0.34080717488789236,
   0.6791808873720137],
  'macro_f1': 0.6073334424356679,
  'weighted_f1': 0.6168514807396647,
  'micro_f1': 0.6909569798068481},
 {'model': 'grok-4',
  'confusion_matrix': [[199, 0, 0, 0, 11, 0],
   [7, 224, 0, 0, 9, 0],
   [0, 0, 0, 0, 0, 188],
   [0, 25, 0, 154, 0, 0],
   [112, 0, 0, 0, 107, 0],
   [0, 0, 0, 0, 0, 188]],
  'f1_scores': [0.7537878787878788,
   0.9161554192229039,
   0.0,
   0.9249249249249248,
   0.6184971098265896,
   0.6666666666666666],
  'macro_f1': 0.6466719999048273,
  'weighted_f1': 0.6572863701845338,
  'micro_f1': 0.7124183006535948},
 {'model': 'mistral-medium',
  'confusion_matrix': [[181, 0, 0, 0, 38, 0],
   [27, 186, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 206],
   [0, 44, 0, 136, 5, 0],
   [83, 0, 0, 0, 108, 0],
   [0, 0, 0, 0, 0, 201]],
  'f1_scores': [0.7098039215686275,
   0.8397291196388261,
   0.0,
   0.8473520249221184,
   0.6315789473684211,
   0.6611842105263158],
  'macro_f1': 0.6149413706707182,
  'weighted_f1': 0.6128387581731269,
  'micro_f1': 0.6683127572016461},
 {'model': 'gpt-4o',
  'confusion_matrix': [[181, 0, 0, 0, 18, 0],
   [35, 181, 0, 0, 3, 0],
   [0, 0, 2, 0, 0, 206],
   [0, 13, 0, 193, 6, 0],
   [125, 0, 0, 0, 74, 0],
   [0, 0, 0, 0, 0, 195]],
  'f1_scores': [0.6703703703703704,
   0.8765133171912832,
   0.01904761904761905,
   0.9530864197530864,
   0.49333333333333323,
   0.6543624161073825],
  'macro_f1': 0.6111189126338458,
  'weighted_f1': 0.6145700896042424,
  'micro_f1': 0.6704545454545454},
 {'model': 'grok-3',
  'confusion_matrix': [[188, 0, 0, 0, 10, 0],
   [6, 206, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 193],
   [0, 16, 0, 169, 0, 0],
   [133, 0, 0, 0, 44, 0],
   [0, 0, 0, 0, 0, 200]],
  'f1_scores': [0.7161904761904762,
   0.9493087557603687,
   0.0,
   0.9548022598870056,
   0.38095238095238093,
   0.6745362563237773],
  'macro_f1': 0.612631688185668,
  'weighted_f1': 0.6197711684801163,
  'micro_f1': 0.6927038626609442},
 {'model': 'grok-4',
  'confusion_matrix': [[204, 0, 0, 0, 11, 0],
   [1, 172, 0, 0, 8, 0],
   [0, 0, 0, 0, 0, 193],
   [0, 46, 0, 181, 0, 0],
   [109, 0, 0, 0, 78, 0],
   [0, 0, 0, 0, 0, 207]],
  'f1_scores': [0.771266540642722,
   0.862155388471178,
   0.0,
   0.8872549019607843,
   0.5492957746478873,
   0.6820428336079076],
  'macro_f1': 0.6253359065550799,
  'weighted_f1': 0.6340334468698829,
  'micro_f1': 0.6958677685950413},
 {'model': 'mistral-medium',
  'confusion_matrix': [[139, 0, 0, 0, 42, 0],
   [26, 196, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 184],
   [0, 47, 0, 145, 8, 0],
   [99, 0, 0, 0, 108, 0],
   [0, 0, 0, 0, 0, 199]],
  'f1_scores': [0.6247191011235955,
   0.843010752688172,
   0.0,
   0.8405797101449275,
   0.5917808219178082,
   0.6838487972508591],
  'macro_f1': 0.5973231971875604,
  'weighted_f1': 0.609323576881004,
  'micro_f1': 0.6596814752724225},
 {'model': 'gpt-4o',
  'confusion_matrix': [[192, 0, 0, 0, 15, 0],
   [22, 167, 0, 0, 2, 0],
   [0, 0, 2, 0, 0, 198],
   [0, 16, 0, 172, 0, 0],
   [122, 0, 0, 0, 61, 0],
   [0, 0, 0, 0, 0, 171]],
  'f1_scores': [0.7071823204419889,
   0.893048128342246,
   0.019801980198019802,
   0.9555555555555556,
   0.4674329501915708,
   0.6333333333333334],
  'macro_f1': 0.6127257113437857,
  'weighted_f1': 0.6091263186087426,
  'micro_f1': 0.6710526315789473},
 {'model': 'grok-3',
  'confusion_matrix': [[185, 0, 0, 0, 13, 0],
   [4, 193, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 181],
   [0, 13, 0, 188, 0, 0],
   [173, 0, 0, 0, 50, 0],
   [0, 0, 0, 0, 0, 212]],
  'f1_scores': [0.6607142857142856,
   0.9578163771712158,
   0.0,
   0.9665809768637532,
   0.34965034965034963,
   0.7008264462809918],
  'macro_f1': 0.6059314059467661,
  'weighted_f1': 0.6108426285539362,
  'micro_f1': 0.6831683168316832},
 {'model': 'grok-4',
  'confusion_matrix': [[187, 0, 0, 0, 15, 0],
   [5, 212, 0, 0, 7, 0],
   [0, 0, 0, 0, 0, 200],
   [0, 28, 0, 174, 0, 0],
   [116, 0, 0, 0, 103, 0],
   [0, 0, 0, 0, 0, 214]],
  'f1_scores': [0.7333333333333333,
   0.9137931034482758,
   0.0,
   0.9255319148936171,
   0.5988372093023255,
   0.6815286624203821],
  'macro_f1': 0.6421707038996557,
  'weighted_f1': 0.647718412299309,
  'micro_f1': 0.7057890563045203},
 {'model': 'mistral-medium',
  'confusion_matrix': [[144, 0, 0, 0, 43, 0],
   [20, 180, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 223],
   [0, 51, 0, 146, 7, 0],
   [76, 0, 0, 0, 102, 0],
   [0, 0, 0, 0, 0, 195]],
  'f1_scores': [0.6744730679156907,
   0.8352668213457076,
   0.0,
   0.8342857142857142,
   0.6181818181818182,
   0.636215334420881],
  'macro_f1': 0.5997371260249685,
  'weighted_f1': 0.5875926432452374,
  'micro_f1': 0.6461668070766639},
 {'model': 'gpt-4o',
  'confusion_matrix': [[183, 0, 0, 0, 14, 0],
   [23, 171, 0, 0, 7, 0],
   [0, 0, 4, 0, 0, 187],
   [0, 7, 0, 206, 4, 0],
   [133, 0, 0, 0, 72, 0],
   [0, 0, 0, 0, 0, 216]],
  'f1_scores': [0.6828358208955224,
   0.9023746701846965,
   0.041025641025641026,
   0.9739952718676123,
   0.4768211920529801,
   0.6978998384491114],
  'macro_f1': 0.6291587390792607,
  'weighted_f1': 0.6386173971724369,
  'micro_f1': 0.6943765281173594},
 {'model': 'grok-3',
  'confusion_matrix': [[161, 0, 0, 0, 18, 0],
   [9, 183, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 184],
   [0, 20, 0, 201, 0, 0],
   [149, 0, 0, 0, 40, 0],
   [0, 0, 0, 0, 0, 213]],
  'f1_scores': [0.6465863453815262,
   0.9265822784810126,
   0.0,
   0.9526066350710901,
   0.32388663967611336,
   0.6983606557377049],
  'macro_f1': 0.5913370923912412,
  'weighted_f1': 0.6062259882964983,
  'micro_f1': 0.6774193548387096},
 {'model': 'grok-4',
  'confusion_matrix': [[185, 0, 0, 0, 12, 0],
   [4, 210, 0, 0, 8, 0],
   [0, 0, 0, 0, 0, 206],
   [0, 41, 0, 161, 0, 0],
   [113, 0, 0, 0, 105, 0],
   [0, 0, 0, 0, 0, 207]],
  'f1_scores': [0.7414829659318638,
   0.8879492600422834,
   0.0,
   0.8870523415977962,
   0.6122448979591837,
   0.667741935483871],
  'macro_f1': 0.6327452335024998,
  'weighted_f1': 0.6342439468218708,
  'micro_f1': 0.6932907348242812},
 {'model': 'mistral-medium',
  'confusion_matrix': [[147, 0, 0, 0, 28, 0],
   [22, 153, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 209],
   [0, 37, 0, 168, 4, 0],
   [79, 0, 0, 0, 96, 0],
   [0, 0, 0, 0, 0, 200]],
  'f1_scores': [0.6950354609929079,
   0.8383561643835616,
   0.0,
   0.8912466843501327,
   0.6336633663366338,
   0.6568144499178982],
  'macro_f1': 0.6191860209968557,
  'weighted_f1': 0.6096833513233162,
  'micro_f1': 0.668416447944007},
 {'model': 'gpt-4o',
  'confusion_matrix': [[196, 0, 0, 0, 18, 0],
   [25, 169, 0, 0, 11, 0],
   [0, 0, 1, 0, 0, 216],
   [0, 19, 0, 171, 7, 0],
   [121, 0, 0, 0, 83, 0],
   [0, 0, 0, 0, 0, 200]],
  'f1_scores': [0.7050359712230215,
   0.8600508905852416,
   0.009174311926605503,
   0.9293478260869565,
   0.5139318885448916,
   0.6493506493506493],
  'macro_f1': 0.611148589619561,
  'weighted_f1': 0.6038582966630499,
  'micro_f1': 0.6628940986257074},
 {'model': 'grok-3',
  'confusion_matrix': [[189, 0, 0, 0, 20, 0],
   [5, 215, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 178],
   [0, 16, 0, 196, 0, 0],
   [188, 0, 0, 0, 36, 0],
   [0, 0, 0, 0, 0, 170]],
  'f1_scores': [0.6395939086294417,
   0.9534368070953438,
   0.0,
   0.9607843137254902,
   0.2571428571428572,
   0.6563706563706564],
  'macro_f1': 0.5778880904939648,
  'weighted_f1': 0.590519794358899,
  'micro_f1': 0.6644682605111294},
 {'model': 'grok-4',
  'confusion_matrix': [[187, 0, 0, 0, 15, 0],
   [10, 176, 0, 0, 5, 0],
   [0, 0, 0, 0, 0, 211],
   [0, 31, 0, 178, 0, 0],
   [103, 0, 0, 0, 97, 0],
   [0, 0, 0, 0, 0, 180]],
  'f1_scores': [0.7450199203187251,
   0.8844221105527639,
   0.0,
   0.9198966408268734,
   0.61198738170347,
   0.6304728546409808],
  'macro_f1': 0.6319664846738021,
  'weighted_f1': 0.6266216555983632,
  'micro_f1': 0.6856663872590109},
 {'model': 'mistral-medium',
  'confusion_matrix': [[168, 0, 0, 0, 35, 0],
   [13, 196, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 181],
   [0, 35, 0, 140, 7, 0],
   [94, 0, 0, 0, 104, 0],
   [0, 0, 0, 0, 0, 184]],
  'f1_scores': [0.702928870292887,
   0.8909090909090909,
   0.0,
   0.8695652173913044,
   0.6046511627906977,
   0.6703096539162112],
  'macro_f1': 0.6230606658833652,
  'weighted_f1': 0.6311264795054576,
  'micro_f1': 0.6845289541918755},
 {'model': 'gpt-4o',
  'confusion_matrix': [[189, 0, 0, 0, 16, 0],
   [21, 176, 0, 0, 6, 0],
   [0, 0, 2, 0, 0, 196],
   [0, 13, 0, 163, 0, 0],
   [138, 0, 0, 0, 69, 0],
   [0, 0, 0, 0, 0, 202]],
  'f1_scores': [0.6835443037974684,
   0.8979591836734695,
   0.02,
   0.9616519174041297,
   0.4630872483221477,
   0.6733333333333333],
  'macro_f1': 0.6165959977550914,
  'weighted_f1': 0.6108273952672881,
  'micro_f1': 0.672544080604534},
 {'model': 'grok-3',
  'confusion_matrix': [[207, 0, 0, 0, 13, 0],
   [11, 188, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 201],
   [0, 18, 0, 185, 0, 0],
   [146, 0, 0, 0, 51, 0],
   [0, 0, 0, 0, 0, 218]],
  'f1_scores': [0.708904109589041,
   0.928395061728395,
   0.0,
   0.9536082474226805,
   0.3908045977011494,
   0.6844583987441131],
  'macro_f1': 0.6110284025308965,
  'weighted_f1': 0.6142911407864998,
  'micro_f1': 0.68578352180937},
 {'model': 'grok-4',
  'confusion_matrix': [[196, 0, 0, 0, 12, 0],
   [4, 178, 0, 0, 9, 0],
   [0, 0, 0, 0, 0, 199],
   [0, 33, 0, 160, 0, 0],
   [108, 0, 0, 0, 95, 0],
   [0, 0, 0, 0, 0, 210]],
  'f1_scores': [0.7596899224806201,
   0.8855721393034826,
   0.0,
   0.9065155807365439,
   0.5956112852664577,
   0.6785137318255251],
  'macro_f1': 0.6376504432687716,
  'weighted_f1': 0.6358091894996165,
  'micro_f1': 0.696843853820598},
 {'model': 'mistral-medium',
  'confusion_matrix': [[163, 0, 0, 0, 31, 0],
   [18, 170, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 176],
   [0, 41, 0, 153, 4, 0],
   [97, 0, 0, 0, 118, 0],
   [0, 0, 0, 0, 0, 196]],
  'f1_scores': [0.690677966101695,
   0.8521303258145363,
   0.0,
   0.8717948717948718,
   0.641304347826087,
   0.6901408450704225],
  'macro_f1': 0.6243413927679354,
  'weighted_f1': 0.634066368216502,
  'micro_f1': 0.6855184233076264},
 {'model': 'gpt-4o',
  'confusion_matrix': [[180, 0, 0, 0, 18, 0],
   [27, 158, 0, 0, 13, 0],
   [0, 0, 2, 0, 0, 199],
   [0, 16, 0, 181, 3, 0],
   [137, 0, 0, 0, 69, 0],
   [0, 0, 0, 0, 0, 207]],
  'f1_scores': [0.6642066420664207,
   0.8494623655913979,
   0.019704433497536946,
   0.9501312335958005,
   0.44660194174757284,
   0.6753670473083198],
  'macro_f1': 0.6009122773011747,
  'weighted_f1': 0.5995820497200292,
  'micro_f1': 0.6586776859504132},
 {'model': 'grok-3',
  'confusion_matrix': [[197, 0, 0, 0, 21, 0],
   [7, 178, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 188],
   [0, 14, 0, 186, 0, 0],
   [168, 0, 0, 0, 48, 0],
   [0, 0, 0, 0, 0, 214]],
  'f1_scores': [0.6677966101694914,
   0.9442970822281168,
   0.0,
   0.9637305699481865,
   0.3368421052631579,
   0.6948051948051948],
  'macro_f1': 0.6012452604023579,
  'weighted_f1': 0.6015290267354152,
  'micro_f1': 0.674037674037674},
 {'model': 'grok-4',
  'confusion_matrix': [[153, 0, 0, 0, 12, 0],
   [10, 198, 0, 0, 2, 0],
   [0, 0, 0, 0, 0, 211],
   [0, 26, 0, 156, 0, 0],
   [107, 0, 0, 0, 86, 0],
   [0, 0, 0, 0, 0, 196]],
  'f1_scores': [0.7034482758620689,
   0.9124423963133641,
   0.0,
   0.923076923076923,
   0.5870307167235496,
   0.6500829187396352],
  'macro_f1': 0.6293468717859235,
  'weighted_f1': 0.619183274972914,
  'micro_f1': 0.6819360414866033},
 {'model': 'mistral-medium',
  'confusion_matrix': [[175, 0, 0, 0, 38, 0],
   [15, 163, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 190],
   [0, 38, 0, 194, 9, 0],
   [102, 0, 0, 0, 103, 0],
   [0, 0, 0, 0, 0, 185]],
  'f1_scores': [0.693069306930693,
   0.8601583113456465,
   0.0,
   0.8919540229885058,
   0.5802816901408452,
   0.6607142857142857],
  'macro_f1': 0.6143629361866627,
  'weighted_f1': 0.6244907183762448,
  'micro_f1': 0.6765676567656765}]

In [ ]:
for model_name, group in df.groupby("predictor"):
    y_true = group["label"].to_numpy()
    y_pred = group["classification"].to_numpy()

    conf_matrix, classes = confusion_matrix_np(y_true, y_pred)
    
    print(f"\nModel: {model_name}")
    print("Classes:", classes)
    print("Confusion Matrix:\n", conf_matrix)

    TP = np.diag(conf_matrix)
    FP = np.sum(conf_matrix, axis=0) - TP
    FN = np.sum(conf_matrix, axis=1) - TP
    precision = TP / (TP + FP)
    recall = TP / (TP + FN)
    f1 = 2 * precision * recall / (precision + recall)
    f1 = np.nan_to_num(f1, nan=0.0)
    print("f1 scores: ", f1)
    print("macro f1 score: ", np.mean(f1))

    support = np.sum(conf_matrix, axis=1)
    f1_weighted = np.sum(f1 * support) / np.sum(support)
    print("weighted score: ", f1_weighted)

    TP_micro = np.sum(TP)
    FP_micro = np.sum(FP)
    FN_micro = np.sum(FN)

    precision_micro = TP_micro / (TP_micro + FP_micro)
    recall_micro = TP_micro / (TP_micro + FN_micro)
    f1_micro = 2 * precision_micro * recall_micro / (precision_micro + recall_micro)

    print("Micro F1:", f1_micro)
    print()

Model: gpt-4o
Classes: ['claim' 'concede' 'question' 'retract' 'since' 'why']
Confusion Matrix:
 [[184   0   0   0  16   0]
 [ 26 167   0   0   7   0]
 [  0   0   5   0   0 195]
 [  0  15   0 180   5   0]
 [128   0   0   0  72   0]
 [  0   0   0   0   0 200]]
f1 scores:  [0.68401487 0.87434555 0.04878049 0.94736842 0.48       0.67226891]
macro f1 score:  0.6177963726745385
weighted score:  0.6177963726745385
Micro F1: 0.6733333333333333


Model: grok-3
Classes: ['claim' 'concede' 'question' 'retract' 'since' 'why']
Confusion Matrix:
 [[185   0   0   0  15   0]
 [  7 193   0   0   0   0]
 [  0   0   0   0   0 200]
 [  0  15   0 185   0   0]
 [155   0   0   0  45   0]
 [  0   0   0   0   0 200]]
f1 scores:  [0.67641682 0.94607843 0.         0.96103896 0.34615385 0.66666667]
macro f1 score:  0.5993924540408033
weighted score:  0.5993924540408034
Micro F1: 0.6733333333333333


Model: grok-4
Classes: ['claim' 'concede' 'question' 'retract' 'since' 'why']
Confusion Matrix:
 [[185   0   0   0  15   0]
 [  5 190   0   0   5   0]
 [  0   0   0   0   0 200]
 [  0  30   0 170   0   0]
 [103   0   0   0  97   0]
 [  0   0   0   0   0 200]]
f1 scores:  [0.7505071  0.9047619  0.         0.91891892 0.61198738 0.66666667]
macro f1 score:  0.64214032857374
weighted score:  0.6421403285737401
Micro F1: 0.7016666666666667


Model: mistral-medium
Classes: ['claim' 'concede' 'question' 'retract' 'since' 'why']
Confusion Matrix:
 [[165   0   0   0  35   0]
 [ 20 180   0   0   0   0]
 [  0   0   0   0   0 200]
 [  0  43   0 152   5   0]
 [ 93   0   0   0 107   0]
 [  0   0   0   0   0 200]]
f1 scores:  [0.69037657 0.85106383 0.         0.86363636 0.6167147  0.66666667]
macro f1 score:  0.6147430210890436
weighted score:  0.6147430210890436
Micro F1: 0.67

C:\Users\Jordan\AppData\Local\Temp\ipykernel_8972\4005659965.py:14: RuntimeWarning: invalid value encountered in divide
  precision = TP / (TP + FP)

In [64]:
bootstrap_df = df.sample(n=len(df), replace=True)

In [65]:
bootstrap_df.head()

,testset_row_index,repetition,dialogue_turn_1,dialogue_turn_2,target,label,predictor,speaker,temp,top_p,seed,classification
1026,51,1,The competitive nature of private healthcare f...,Why should we trust that profit-driven healthc...,I am no longer committed to the assertion that...,retract,gpt-4o,gpt-4o,0,1,123,retract
3614,180,4,Blaming freeloaders distracts from the fact th...,Strict state oversight is the most effective w...,"Far from proving responsible use, heavy-handed...",claim,grok-3,grok-4,0,1,123,claim
2892,144,2,I’m not dismissing ONS data on state funding i...,ONS data shows state investment boosts NHS acc...,Why do you keep ignoring that state control ha...,why,grok-3,grok-3,0,1,123,why
2607,130,2,Relying on state-guaranteed healthcare ignores...,Healthcare access should be guaranteed by stat...,Market-driven healthcare pushes providers to i...,since,gpt-4o,grok-3,0,1,123,claim
1936,96,1,Why can't public-private partnerships be struc...,Public-private partnerships often fail to alig...,Why do you assume that market-driven solutions...,question,grok-4,mistral-medium,0,1,123,why

In [66]:
len(bootstrap_df)

4800