In [1]:
import yaml
import json
import pickle
import pandas as pd
import numpy as np
import itertools
import matplotlib.pyplot as plt
import seaborn as sns
import httpx
import os

import warnings
warnings.filterwarnings("ignore")

from prolific import ProlificAPIError, ProlificClient

pd.set_option('display.max_columns', None)

# config = yaml.safe_load(open("config.yaml", "r"))

client = ProlificClient(
    api_token=os.environ["prolific_key"])

# API Testing

In [2]:
ID = "6978ec7f65af76fdfe5640b8"

In [3]:
client.get_study(ID)

{'id': '6978ec7f65af76fdfe5640b8',
 'name': 'Human judgements of persuasiveness',
 'description': '<p>In this study, you will evaluate <strong>persuasiveness in debate transcripts</strong>. You will read transcripts from <strong>two separate debates</strong> on the same topic and judge which speaker is more persuasive.</p><p>Each debate features two participants, Speaker A and Speaker B. Although the debates involve different individuals, <strong>Speaker A represents the same ideological or political position in both debates</strong>.</p><p>Your task is to compare the persuasiveness of <strong>Speaker A across the two debates</strong>, focusing only on how effectively they argue their position.</p><p>There are <strong>no right or wrong answers</strong>—we are interested in your honest, subjective judgment based on the debate content. </p>',
 'total_available_places': 100,
 'reward': 60,
 'average_reward_per_hour': 1317.0,
 'external_study_url': 'https://tars.dcp.prod.aws.prolific.co/access-details/cfd86ff2-90d1-4e35-841e-5f124157e55d/allocate',
 'device_compatibility': ['desktop', 'mobile', 'tablet'],
 'peripheral_requirements': [],
 'researcher': {'id': '693837451402cb5f5765430f',
  'name': 'Jordan Robinson',
  'email': 'j.robinson@turing.ac.uk',
  'country': 'GB',
  'institution': {'name': 'turing.ac.uk',
   'logo': 'https://internal-api.prolific.com/assets/img/institutions/turing.ac.uk.png',
   'link': 'http://www.turing.ac.uk'}},
 'publisher': {'id': '693837451402cb5f5765430f',
  'name': 'Jordan Robinson',
  'email': 'j.robinson@turing.ac.uk',
  'country': 'GB',
  'institution': {'name': 'turing.ac.uk',
   'logo': 'https://internal-api.prolific.com/assets/img/institutions/turing.ac.uk.png',
   'link': 'http://www.turing.ac.uk'}},
 'places_taken': 100,
 'study_type': 'SINGLE',
 'submissions_config': {'max_submissions_per_participant': 1,
  'max_concurrent_submissions': -1,
  'auto_rejection_categories': ['EXCEPTIONALLY_FAST']},
 'status': 'COMPLETED',
 'internal_name': 'dso-persuasiveness-5-samples-pilot-study-num-1',
 'minimum_reward_per_hour': 600.0,
 'date_created': '2026-01-27T16:48:54.284000Z',
 'published_at': '2026-01-27T16:49:16.435000Z',
 'number_of_submissions': 107,
 'estimated_completion_time': 4,
 'average_time_taken': 2,
 'average_time_taken_seconds': 164,
 'completion_code': None,
 'failed_attention_code': None,
 'alternative_completion_codes': [],
 'completion_code_action': None,
 'last_email_update_sent_datetime': None,
 'maximum_allowed_time': 26,
 'receipt': None,
 'eligible_participant_count': 6860,
 'total_participant_pool': 183799,
 'currency_code': 'GBP',
 'total_cost': 8401,
 'fees_per_submission': 0.0,
 'fees_percentage': 0.333333,
 'service_margin_percentage': '0.25000000000000000',
 'vat_percentage': 0.2,
 'discount_from_coupons': 0,
 'eligibility_requirements': [{'id': '6978ec7f65af76fdfe5640ba',
   'type': 'select',
   'attributes': [{'label': 'United Kingdom',
     'name': 'United Kingdom',
     'value': True,
     'index': 0},
    {'label': 'United States',
     'name': 'United States',
     'value': False,
     'index': 1},
    {'label': 'Ireland', 'name': 'Ireland', 'value': False, 'index': 2},
    {'label': 'Germany', 'name': 'Germany', 'value': False, 'index': 3},
    {'label': 'France', 'name': 'France', 'value': False, 'index': 4},
    {'label': 'Spain', 'name': 'Spain', 'value': False, 'index': 5},
    {'label': 'Afghanistan',
     'name': 'Afghanistan',
     'value': False,
     'index': 6},
    {'label': 'Aland Islands',
     'name': 'Aland Islands',
     'value': False,
     'index': 7},
    {'label': 'Albania', 'name': 'Albania', 'value': False, 'index': 8},
    {'label': 'Algeria', 'name': 'Algeria', 'value': False, 'index': 9},
    {'label': 'American Samoa',
     'name': 'American Samoa',
     'value': False,
     'index': 10},
    {'label': 'Andorra', 'name': 'Andorra', 'value': False, 'index': 11},
    {'label': 'Angola', 'name': 'Angola', 'value': False, 'index': 12},
    {'label': 'Anguilla', 'name': 'Anguilla', 'value': False, 'index': 13},
    {'label': 'Antarctica', 'name': 'Antarctica', 'value': False, 'index': 14},
    {'label': 'Antigua and Barbuda',
     'name': 'Antigua and Barbuda',
     'value': False,
     'index': 15},
    {'label': 'Argentina', 'name': 'Argentina', 'value': False, 'index': 16},
    {'label': 'Armenia', 'name': 'Armenia', 'value': False, 'index': 17},
    {'label': 'Aruba', 'name': 'Aruba', 'value': False, 'index': 18},
    {'label': 'Australia', 'name': 'Australia', 'value': False, 'index': 19},
    {'label': 'Austria', 'name': 'Austria', 'value': False, 'index': 20},
    {'label': 'Azerbaijan', 'name': 'Azerbaijan', 'value': False, 'index': 21},
    {'label': 'Bahamas', 'name': 'Bahamas', 'value': False, 'index': 22},
    {'label': 'Bahrain', 'name': 'Bahrain', 'value': False, 'index': 23},
    {'label': 'Bangladesh', 'name': 'Bangladesh', 'value': False, 'index': 24},
    {'label': 'Barbados', 'name': 'Barbados', 'value': False, 'index': 25},
    {'label': 'Belarus', 'name': 'Belarus', 'value': False, 'index': 26},
    {'label': 'Belgium', 'name': 'Belgium', 'value': False, 'index': 27},
    {'label': 'Belize', 'name': 'Belize', 'value': False, 'index': 28},
    {'label': 'Benin', 'name': 'Benin', 'value': False, 'index': 29},
    {'label': 'Bermuda', 'name': 'Bermuda', 'value': False, 'index': 30},
    {'label': 'Bhutan', 'name': 'Bhutan', 'value': False, 'index': 31},
    {'label': 'Bolivia', 'name': 'Bolivia', 'value': False, 'index': 32},
    {'label': 'Bonaire', 'name': 'Bonaire', 'value': False, 'index': 33},
    {'label': 'Bosnia and Herzegovina',
     'name': 'Bosnia and Herzegovina',
     'value': False,
     'index': 34},
    {'label': 'Botswana', 'name': 'Botswana', 'value': False, 'index': 35},
    {'label': 'Bouvet Island',
     'name': 'Bouvet Island',
     'value': False,
     'index': 36},
    {'label': 'Brazil', 'name': 'Brazil', 'value': False, 'index': 37},
    {'label': 'British Indian Ocean Territory',
     'name': 'British Indian Ocean Territory',
     'value': False,
     'index': 38},
    {'label': 'Brunei Darussalam',
     'name': 'Brunei Darussalam',
     'value': False,
     'index': 39},
    {'label': 'Bulgaria', 'name': 'Bulgaria', 'value': False, 'index': 40},
    {'label': 'Burkina Faso',
     'name': 'Burkina Faso',
     'value': False,
     'index': 41},
    {'label': 'Burundi', 'name': 'Burundi', 'value': False, 'index': 42},
    {'label': 'Cambodia', 'name': 'Cambodia', 'value': False, 'index': 43},
    {'label': 'Cameroon', 'name': 'Cameroon', 'value': False, 'index': 44},
    {'label': 'Canada', 'name': 'Canada', 'value': False, 'index': 45},
    {'label': 'Cape Verde', 'name': 'Cape Verde', 'value': False, 'index': 46},
    {'label': 'Cayman Islands',
     'name': 'Cayman Islands',
     'value': False,
     'index': 47},
    {'label': 'Central African Republic',
     'name': 'Central African Republic',
     'value': False,
     'index': 48},
    {'label': 'Chad', 'name': 'Chad', 'value': False, 'index': 49},
    {'label': 'Chile', 'name': 'Chile', 'value': False, 'index': 50},
    {'label': 'China', 'name': 'China', 'value': False, 'index': 51},
    {'label': 'Christmas Island',
     'name': 'Christmas Island',
     'value': False,
     'index': 52},
    {'label': 'Cocos (Keeling) Islands',
     'name': 'Cocos (Keeling) Islands',
     'value': False,
     'index': 53},
    {'label': 'Colombia', 'name': 'Colombia', 'value': False, 'index': 54},
    {'label': 'Comoros', 'name': 'Comoros', 'value': False, 'index': 55},
    {'label': 'Congo', 'name': 'Congo', 'value': False, 'index': 56},
    {'label': 'Congo the Democratic Republic of the',
     'name': 'Congo the Democratic Republic of the',
     'value': False,
     'index': 57},
    {'label': 'Cook Islands',
     'name': 'Cook Islands',
     'value': False,
     'index': 58},
    {'label': 'Costa Rica', 'name': 'Costa Rica', 'value': False, 'index': 59},
    {'label': "Cote d'Ivoire",
     'name': "Cote d'Ivoire",
     'value': False,
     'index': 60},
    {'label': 'Croatia', 'name': 'Croatia', 'value': False, 'index': 61},
    {'label': 'Cuba', 'name': 'Cuba', 'value': False, 'index': 62},
    {'label': 'Curacao', 'name': 'Curacao', 'value': False, 'index': 63},
    {'label': 'Cyprus', 'name': 'Cyprus', 'value': False, 'index': 64},
    {'label': 'Czech Republic',
     'name': 'Czech Republic',
     'value': False,
     'index': 65},
    {'label': 'Denmark', 'name': 'Denmark', 'value': False, 'index': 66},
    {'label': 'Djibouti', 'name': 'Djibouti', 'value': False, 'index': 67},
    {'label': 'Dominica', 'name': 'Dominica', 'value': False, 'index': 68},
    {'label': 'Dominican Republic',
     'name': 'Dominican Republic',
     'value': False,
     'index': 69},
    {'label': 'Ecuador', 'name': 'Ecuador', 'value': False, 'index': 70},
    {'label': 'Egypt', 'name': 'Egypt', 'value': False, 'index': 71},
    {'label': 'El Salvador',
     'name': 'El Salvador',
     'value': False,
     'index': 72},
    {'label': 'Equatorial Guinea',
     'name': 'Equatorial Guinea',
     'value': False,
     'index': 73},
    {'label': 'Eritrea', 'name': 'Eritrea', 'value': False, 'index': 74},
    {'label': 'Estonia', 'name': 'Estonia', 'value': False, 'index': 75},
    {'label': 'Ethiopia', 'name': 'Ethiopia', 'value': False, 'index': 76},
    {'label': 'Falkland Islands (Malvinas)',
     'name': 'Falkland Islands (Malvinas)',
     'value': False,
     'index': 77},
    {'label': 'Faroe Islands',
     'name': 'Faroe Islands',
     'value': False,
     'index': 78},
    {'label': 'Fiji', 'name': 'Fiji', 'value': False, 'index': 79},
    {'label': 'Finland', 'name': 'Finland', 'value': False, 'index': 80},
    {'label': 'French Guiana',
     'name': 'French Guiana',
     'value': False,
     'index': 81},
    {'label': 'French Polynesia',
     'name': 'French Polynesia',
     'value': False,
     'index': 82},
    {'label': 'French Southern Territories',
     'name': 'French Southern Territories',
     'value': False,
     'index': 83},
    {'label': 'Gabon', 'name': 'Gabon', 'value': False, 'index': 84},
    {'label': 'Gambia', 'name': 'Gambia', 'value': False, 'index': 85},
    {'label': 'Georgia', 'name': 'Georgia', 'value': False, 'index': 86},
    {'label': 'Ghana', 'name': 'Ghana', 'value': False, 'index': 87},
    {'label': 'Gibraltar', 'name': 'Gibraltar', 'value': False, 'index': 88},
    {'label': 'Greece', 'name': 'Greece', 'value': False, 'index': 89},
    {'label': 'Greenland', 'name': 'Greenland', 'value': False, 'index': 90},
    {'label': 'Grenada', 'name': 'Grenada', 'value': False, 'index': 91},
    {'label': 'Guadeloupe', 'name': 'Guadeloupe', 'value': False, 'index': 92},
    {'label': 'Guam', 'name': 'Guam', 'value': False, 'index': 93},
    {'label': 'Guatemala', 'name': 'Guatemala', 'value': False, 'index': 94},
    {'label': 'Guernsey', 'name': 'Guernsey', 'value': False, 'index': 95},
    {'label': 'Guinea', 'name': 'Guinea', 'value': False, 'index': 96},
    {'label': 'Guinea-Bissau',
     'name': 'Guinea-Bissau',
     'value': False,
     'index': 97},
    {'label': 'Guyana', 'name': 'Guyana', 'value': False, 'index': 98},
    {'label': 'Haiti', 'name': 'Haiti', 'value': False, 'index': 99},
    {'label': 'Heard Island and McDonald Islands',
     'name': 'Heard Island and McDonald Islands',
     'value': False,
     'index': 100},
    {'label': 'Holy See (Vatican City State)',
     'name': 'Holy See (Vatican City State)',
     'value': False,
     'index': 101},
    {'label': 'Honduras', 'name': 'Honduras', 'value': False, 'index': 102},
    {'label': 'Hong Kong', 'name': 'Hong Kong', 'value': False, 'index': 103},
    {'label': 'Hungary', 'name': 'Hungary', 'value': False, 'index': 104},
    {'label': 'Iceland', 'name': 'Iceland', 'value': False, 'index': 105},
    {'label': 'India', 'name': 'India', 'value': False, 'index': 106},
    {'label': 'Indonesia', 'name': 'Indonesia', 'value': False, 'index': 107},
    {'label': 'Iran', 'name': 'Iran', 'value': False, 'index': 108},
    {'label': 'Iraq', 'name': 'Iraq', 'value': False, 'index': 109},
    {'label': 'Isle of Man',
     'name': 'Isle of Man',
     'value': False,
     'index': 110},
    {'label': 'Israel', 'name': 'Israel', 'value': False, 'index': 111},
    {'label': 'Italy', 'name': 'Italy', 'value': False, 'index': 112},
    {'label': 'Jamaica', 'name': 'Jamaica', 'value': False, 'index': 113},
    {'label': 'Japan', 'name': 'Japan', 'value': False, 'index': 114},
    {'label': 'Jersey', 'name': 'Jersey', 'value': False, 'index': 115},
    {'label': 'Jordan', 'name': 'Jordan', 'value': False, 'index': 116},
    {'label': 'Kazakhstan',
     'name': 'Kazakhstan',
     'value': False,
     'index': 117},
    {'label': 'Kenya', 'name': 'Kenya', 'value': False, 'index': 118},
    {'label': 'Kiribati', 'name': 'Kiribati', 'value': False, 'index': 119},
    {'label': 'Korea', 'name': 'Korea', 'value': False, 'index': 120},
    {'label': 'Kuwait', 'name': 'Kuwait', 'value': False, 'index': 121},
    {'label': 'Kyrgyzstan',
     'name': 'Kyrgyzstan',
     'value': False,
     'index': 122},
    {'label': "Lao People's Democratic Republic",
     'name': "Lao People's Democratic Republic",
     'value': False,
     'index': 123},
    {'label': 'Latvia', 'name': 'Latvia', 'value': False, 'index': 124},
    {'label': 'Lebanon', 'name': 'Lebanon', 'value': False, 'index': 125},
    {'label': 'Lesotho', 'name': 'Lesotho', 'value': False, 'index': 126},
    {'label': 'Liberia', 'name': 'Liberia', 'value': False, 'index': 127},
    {'label': 'Libya', 'name': 'Libya', 'value': False, 'index': 128},
    {'label': 'Liechtenstein',
     'name': 'Liechtenstein',
     'value': False,
     'index': 129},
    {'label': 'Lithuania', 'name': 'Lithuania', 'value': False, 'index': 130},
    {'label': 'Luxembourg',
     'name': 'Luxembourg',
     'value': False,
     'index': 131},
    {'label': 'Macao', 'name': 'Macao', 'value': False, 'index': 132},
    {'label': 'Macedonia', 'name': 'Macedonia', 'value': False, 'index': 133},
    {'label': 'Madagascar',
     'name': 'Madagascar',
     'value': False,
     'index': 134},
    {'label': 'Malawi', 'name': 'Malawi', 'value': False, 'index': 135},
    {'label': 'Malaysia', 'name': 'Malaysia', 'value': False, 'index': 136},
    {'label': 'Maldives', 'name': 'Maldives', 'value': False, 'index': 137},
    {'label': 'Mali', 'name': 'Mali', 'value': False, 'index': 138},
    {'label': 'Malta', 'name': 'Malta', 'value': False, 'index': 139},
    {'label': 'Marshall Islands',
     'name': 'Marshall Islands',
     'value': False,
     'index': 140},
    {'label': 'Martinique',
     'name': 'Martinique',
     'value': False,
     'index': 141},
    {'label': 'Mauritania',
     'name': 'Mauritania',
     'value': False,
     'index': 142},
    {'label': 'Mauritius', 'name': 'Mauritius', 'value': False, 'index': 143},
    {'label': 'Mayotte', 'name': 'Mayotte', 'value': False, 'index': 144},
    {'label': 'Mexico', 'name': 'Mexico', 'value': False, 'index': 145},
    {'label': 'Micronesia',
     'name': 'Micronesia',
     'value': False,
     'index': 146},
    {'label': 'Moldova', 'name': 'Moldova', 'value': False, 'index': 147},
    {'label': 'Monaco', 'name': 'Monaco', 'value': False, 'index': 148},
    {'label': 'Mongolia', 'name': 'Mongolia', 'value': False, 'index': 149},
    {'label': 'Montenegro',
     'name': 'Montenegro',
     'value': False,
     'index': 150},
    {'label': 'Montserrat',
     'name': 'Montserrat',
     'value': False,
     'index': 151},
    {'label': 'Morocco', 'name': 'Morocco', 'value': False, 'index': 152},
    {'label': 'Mozambique',
     'name': 'Mozambique',
     'value': False,
     'index': 153},
    {'label': 'Myanmar', 'name': 'Myanmar', 'value': False, 'index': 154},
    {'label': 'Namibia', 'name': 'Namibia', 'value': False, 'index': 155},
    {'label': 'Nauru', 'name': 'Nauru', 'value': False, 'index': 156},
    {'label': 'Nepal', 'name': 'Nepal', 'value': False, 'index': 157},
    {'label': 'Netherlands',
     'name': 'Netherlands',
     'value': False,
     'index': 158},
    {'label': 'New Caledonia',
     'name': 'New Caledonia',
     'value': False,
     'index': 159},
    {'label': 'New Zealand',
     'name': 'New Zealand',
     'value': False,
     'index': 160},
    {'label': 'Nicaragua', 'name': 'Nicaragua', 'value': False, 'index': 161},
    {'label': 'Niger', 'name': 'Niger', 'value': False, 'index': 162},
    {'label': 'Nigeria', 'name': 'Nigeria', 'value': False, 'index': 163},
    {'label': 'Niue', 'name': 'Niue', 'value': False, 'index': 164},
    {'label': 'Norfolk Island',
     'name': 'Norfolk Island',
     'value': False,
     'index': 165},
    {'label': 'Northern Mariana Islands',
     'name': 'Northern Mariana Islands',
     'value': False,
     'index': 166},
    {'label': 'Norway', 'name': 'Norway', 'value': False, 'index': 167},
    {'label': 'Oman', 'name': 'Oman', 'value': False, 'index': 168},
    {'label': 'Pakistan', 'name': 'Pakistan', 'value': False, 'index': 169},
    {'label': 'Palau', 'name': 'Palau', 'value': False, 'index': 170},
    {'label': 'Palestinian Territory',
     'name': 'Palestinian Territory',
     'value': False,
     'index': 171},
    {'label': 'Panama', 'name': 'Panama', 'value': False, 'index': 172},
    {'label': 'Papua New Guinea',
     'name': 'Papua New Guinea',
     'value': False,
     'index': 173},
    {'label': 'Paraguay', 'name': 'Paraguay', 'value': False, 'index': 174},
    {'label': 'Peru', 'name': 'Peru', 'value': False, 'index': 175},
    {'label': 'Philippines',
     'name': 'Philippines',
     'value': False,
     'index': 176},
    {'label': 'Pitcairn', 'name': 'Pitcairn', 'value': False, 'index': 177},
    {'label': 'Poland', 'name': 'Poland', 'value': False, 'index': 178},
    {'label': 'Portugal', 'name': 'Portugal', 'value': False, 'index': 179},
    {'label': 'Puerto Rico',
     'name': 'Puerto Rico',
     'value': False,
     'index': 180},
    {'label': 'Qatar', 'name': 'Qatar', 'value': False, 'index': 181},
    {'label': 'Reunion', 'name': 'Reunion', 'value': False, 'index': 182},
    {'label': 'Romania', 'name': 'Romania', 'value': False, 'index': 183},
    {'label': 'Russian Federation',
     'name': 'Russian Federation',
     'value': False,
     'index': 184},
    {'label': 'Rwanda', 'name': 'Rwanda', 'value': False, 'index': 185},
    {'label': 'Saint Barthelemy',
     'name': 'Saint Barthelemy',
     'value': False,
     'index': 186},
    {'label': 'Saint Helena',
     'name': 'Saint Helena',
     'value': False,
     'index': 187},
    {'label': 'Saint Kitts and Nevis',
     'name': 'Saint Kitts and Nevis',
     'value': False,
     'index': 188},
    {'label': 'Saint Lucia',
     'name': 'Saint Lucia',
     'value': False,
     'index': 189},
    {'label': 'Saint Martin (French part)',
     'name': 'Saint Martin (French part)',
     'value': False,
     'index': 190},
    {'label': 'Saint Pierre and Miquelon',
     'name': 'Saint Pierre and Miquelon',
     'value': False,
     'index': 191},
    {'label': 'Saint Vincent and the Grenadines',
     'name': 'Saint Vincent and the Grenadines',
     'value': False,
     'index': 192},
    {'label': 'Samoa', 'name': 'Samoa', 'value': False, 'index': 193},
    {'label': 'San Marino',
     'name': 'San Marino',
     'value': False,
     'index': 194},
    {'label': 'Sao Tome and Principe',
     'name': 'Sao Tome and Principe',
     'value': False,
     'index': 195},
    {'label': 'Saudi Arabia',
     'name': 'Saudi Arabia',
     'value': False,
     'index': 196},
    {'label': 'Senegal', 'name': 'Senegal', 'value': False, 'index': 197},
    {'label': 'Serbia', 'name': 'Serbia', 'value': False, 'index': 198},
    {'label': 'Seychelles',
     'name': 'Seychelles',
     'value': False,
     'index': 199},
    {'label': 'Sierra Leone',
     'name': 'Sierra Leone',
     'value': False,

In [4]:
responses = client.list_submissions(study=ID, page_size=1000)
print(len(responses["results"]))
print(json.dumps(responses['results'][0], indent=2))

107
{
  "id": "6978ed104fd1353ebbd8a84c",
  "participant_id": "5c93b062c9d93b0015fcbc02",
  "started_at": "2026-01-27T16:51:31.999000Z",
  "completed_at": "2026-01-27T16:52:29.973000Z",
  "is_complete": true,
  "time_taken": 57,
  "reward": 6000,
  "status": "APPROVED",
  "strata": {},
  "study_code": "NOCODE",
  "bonus_payments": [],
  "ip": "92.238.156.108",
  "return_requested": null,
  "has_siblings": false,
  "time_taken_under_auto_approval_threshold": true,
  "dynamic_payment_percentage": null
}

In [5]:
sub = client.get_submission(responses['results'][0]['id'])
sub

{'id': '6978ed104fd1353ebbd8a84c',
 'status': 'APPROVED',
 'participant': '5c93b062c9d93b0015fcbc02',
 'datetime_created': '2026-01-27T16:51:28Z',
 'started_at': '2026-01-27T16:51:31.999000Z',
 'ip': '92.238.156.108',
 'completed_at': '2026-01-27T16:52:29.973000Z',
 'payment_sent_at': None,
 'emailed_at': None,
 'timed_out_permenant': False,
 'started_index': 32,
 'is_approved': True,
 'entered_code': 'NOCODE',
 'reviewed_at': '2026-01-27T18:03:13.752000Z',
 'returned_at': None,
 'discount_amount': 0,
 'study': None,
 'time_remaining': 0,
 'study_url': 'https://tars.dcp.prod.aws.prolific.co/access-details/cfd86ff2-90d1-4e35-841e-5f124157e55d/allocate',
 'study_code': 'NOCODE',
 'study_id': '6978ec7f65af76fdfe5640b8',
 'reserve_until': None,
 'return_requested': None,
 'bonus_payments': [],
 'parent_study_id': None,
 '_links': {'self': {'href': 'https://api.prolific.com/api/v1/submissions/6978ed104fd1353ebbd8a84c/',
   'title': 'Current'},
  'related': [{'href': 'https://api.prolific.com/api/v1/studies/6978ec7f65af76fdfe5640b8/',
    'title': 'Study'},
   {'href': 'https://api.prolific.com/api/v1/users/5c93b062c9d93b0015fcbc02/',
    'title': 'Participant'}]}}

In [19]:
df = pd.read_csv("data/test-pilot-study-results-019c004e-c6f8-71dd-9c9c-86944a4f873e.csv")

In [20]:
df.head()

,DataPoint_ID,Task_Group_ID,Task_Type,Question,Debate Topic,Debate 1,Debate 2,META_SAMPLE1_POLITICAL_POSITION,META_SAMPLE1_SPEAKERA,META_SAMPLE1_SPEAKERB,META_COMPARISON,META_COMPARISONID,META_SAMPLE1_DIALOGUE_CHUNK,META_PAIR_SESSION_IDS,Annotator1_ID,Annotator1_Response,Annotator1_Timestamp,Annotator2_ID,Annotator2_Response,Annotator2_Timestamp,Annotator3_ID,Annotator3_Response,Annotator3_Timestamp,Annotator4_ID,Annotator4_Response,Annotator4_Timestamp,Annotator5_ID,Annotator5_Response,Annotator5_Timestamp,Annotator6_ID,Annotator6_Response,Annotator6_Timestamp,Annotator7_ID,Annotator7_Response,Annotator7_Timestamp,Annotator8_ID,Annotator8_Response,Annotator8_Timestamp,Annotator9_ID,Annotator9_Response,Annotator9_Timestamp,Annotator10_ID,Annotator10_Response,Annotator10_Timestamp,Annotator11_ID,Annotator11_Response,Annotator11_Timestamp,Annotator12_ID,Annotator12_Response,Annotator12_Timestamp,Annotator13_ID,Annotator13_Response,Annotator13_Timestamp,Annotator14_ID,Annotator14_Response,Annotator14_Timestamp,Annotator15_ID,Annotator15_Response,Annotator15_Timestamp,Annotator16_ID,Annotator16_Response,Annotator16_Timestamp,Annotator17_ID,Annotator17_Response,Annotator17_Timestamp,Annotator18_ID,Annotator18_Response,Annotator18_Timestamp,Annotator19_ID,Annotator19_Response,Annotator19_Timestamp,Annotator20_ID,Annotator20_Response,Annotator20_Timestamp
0,019c004e-b441-77a8-b741-60a6e281c5a4,407a1775-fc8a-5da6-9bcd-c9879baf85cb,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""The government should allow parent...","Speaker A: ""I don't trust that they will const...",left,human_7,human_12,"('human_7', 'human_8')",158,"[{'speaker': 'human_12', 'timestamp': '2026-01...","('1XHC4T', 'RSQGNQ')",5d4d9ea8c088850019ec5b32,Speaker A from Debate 2,2026-01-27T16:50:50.367Z,5afbf02302b1b5000103e313,Speaker A from Debate 1,2026-01-27T16:51:57.594Z,5c4592d7f608210001a4b0a8,Speaker A from Debate 1,2026-01-27T16:53:06.922Z,5bbc3d95f1f9ba000141d855,Speaker A from Debate 1,2026-01-27T16:53:30.876Z,60d075b6af3d46debaf3cfd8,Both Speaker As were equally persuasive,2026-01-27T16:53:33.173Z,5dd0409d9ca8a312350a4118,Speaker A from Debate 1,2026-01-27T16:55:11.699Z,5d41925ef7b99500012b960e,Speaker A from Debate 1,2026-01-27T16:55:23.367Z,67696d49d386c9789b03b1da,Speaker A from Debate 1,2026-01-27T16:55:40.827Z,66f1c61208486d7c425dcefd,Speaker A from Debate 1,2026-01-27T16:55:45.647Z,5ef528c2a0603b16a793423d,Both Speaker As were equally persuasive,2026-01-27T16:55:47.568Z,5ede66237578b70c1548f73e,Speaker A from Debate 1,2026-01-27T16:56:37.851Z,5b68c9eb87af310001584803,Speaker A from Debate 2,2026-01-27T16:57:17.132Z,5b421b9ac2e3810001763252,Speaker A from Debate 2,2026-01-27T16:58:12.235Z,5f0d89b9547a8403103a0372,Speaker A from Debate 1,2026-01-27T16:58:34.338Z,60b542b8fbb1a6a2678f5054,Speaker A from Debate 1,2026-01-27T17:01:08.079Z,5755c957eb80c4000741a9ce,Speaker A from Debate 2,2026-01-27T17:01:52.818Z,66bbafb05de7e549455aa4ff,Speaker A from Debate 1,2026-01-27T17:05:00.034Z,6798ae13687f9a946efe51eb,Speaker A from Debate 1,2026-01-27T17:06:07.176Z,66a1561d05457dd7ec9cd3a8,Both Speaker As were equally persuasive,2026-01-27T17:10:56.125Z,5efc4644f6f5950008d892a2,Speaker A from Debate 2,2026-01-27T17:19:39.180Z
1,019c004e-b441-77a8-b741-60a6e281c5a4,407a1775-fc8a-5da6-9bcd-c9879baf85cb,multiple_choice,How confident are you in your choice?,Debate the trade-offs of government interventi...,"Speaker B: ""The government should allow parent...","Speaker A: ""I don't trust that they will const...",left,human_7,human_12,"('human_7', 'human_8')",158,"[{'speaker': 'human_12', 'timestamp': '2026-01...","('1XHC4T', 'RSQGNQ')",5d4d9ea8c088850019ec5b32,Somewhat unsure,2026-01-27T16:50:50.367Z,5afbf02302b1b5000103e313,Very confident,2026-01-27T16:51:57.594Z,5c4592d7f608210001a4b0a8,Somewhat confident,2026-01-27T16:53:06.922Z,5bbc3d95f1f9ba000141d855,Very confident,2026-01-27T16:53:30.876Z,60d075b6af3d46debaf3cfd8,Somewhat confident,2026-01-27T16:53:33.173Z,5dd0409d9ca8a312350a4118,Somewhat confident,2026-01-27T16:55:11.699Z,5d41925ef7b99500012b960e,Very confident,2026-01-27T16:55:23.368Z,67696d49d386c9789b03b1da,Somewhat confident,2026-01-27T16:55:40.827Z,66f1c61208486d7c425dcefd,Somewhat confident,2026-01-27T16:55:45.647Z,5ef528c2a0603b16a793423d,Somewhat confident,2026-01-27T16:55:47.568Z,5ede66237578b70c1548f73e,Somewhat confident,2026-01-27T16:56:37.851Z,5b68c9eb87af310001584803,Very confident,2026-01-27T16:57:17.132Z,5b421b9ac2e3810001763252,Somewhat confident,2026-01-27T16:58:12.235Z,5f0d89b9547a8403103a0372,Somewhat confident,2026-01-27T16:58:34.338Z,60b542b8fbb1a6a2678f5054,Very confident,2026-01-27T17:01:08.079Z,5755c957eb80c4000741a9ce,Somewhat unsure,2026-01-27T17:01:52.818Z,66bbafb05de7e549455aa4ff,Somewhat confident,2026-01-27T17:05:00.034Z,6798ae13687f9a946efe51eb,Somewhat confident,2026-01-27T17:06:07.176Z,66a1561d05457dd7ec9cd3a8,Neutral,2026-01-27T17:10:56.125Z,5efc4644f6f5950008d892a2,Neutral,2026-01-27T17:19:39.180Z
2,019c004e-b479-7348-8a29-9781ff428810,6762026f-5d49-52d1-be4a-133965da5ff6,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""The NHS in the UK continues to pro...","Speaker B: ""So does that mean that the whole p...",right,human_7,gpt-4o_mas_rag,"('human_7', 'human_8')",159,"[{'speaker': 'gpt-4o_mas_rag', 'timestamp': '2...","('DL3D7S', '6XAVOS')",671d3690dc5df6d004cfb65e,Speaker A from Debate 1,2026-01-27T16:52:05.218Z,5bb62f1a3e969700019bd44d,Both Speaker As were equally persuasive,2026-01-27T16:53:05.218Z,6704539fe462b87182866f14,Speaker A from Debate 1,2026-01-27T16:53:12.361Z,5c03e86d55555b0001caf233,Speaker A from Debate 2,2026-01-27T16:53:15.495Z,5ac4b010f69e940001d97645,Speaker A from Debate 1,2026-01-27T16:53:27.744Z,54aefa06fdf99b09c01b37f4,Speaker A from Debate 1,2026-01-27T16:53:56.045Z,5a5a6ed7f6c517000195029e,Both Speaker As were equally persuasive,2026-01-27T16:54:12.699Z,65537e14439274fe5036b4d2,Speaker A from Debate 2,2026-01-27T16:55:04.365Z,668dc7b684452eaca13eb60d,Speaker A from Debate 2,2026-01-27T16:55:25.805Z,56a757a95ad8d9000c970c76,Speaker A from Debate 1,2026-01-27T16:55:52.295Z,629dd4199343d7710fcdb39c,Speaker A from Debate 2,2026-01-27T16:57:33.573Z,5a0f34de9b760100013a7afd,Speaker A from Debate 2,2026-01-27T16:57:34.140Z,6125646031b73d8171421e7c,Speaker A from Debate 1,2026-01-27T16:58:25.996Z,5f0cf299c6db5770064402e1,Speaker A from Debate 1,2026-01-27T17:01:39.421Z,6007421356226920359b5f3e,Speaker A from Debate 1,2026-01-27T17:01:39.983Z,6100906e671b8294f9ea93d8,Speaker A from Debate 1,2026-01-27T17:02:07.443Z,677a8e5affbe5673b3a79e6b,Speaker A from Debate 2,2026-01-27T17:02:45.367Z,644fdc8d0d748ff99020fcae,Both Speaker As were equally persuasive,2026-01-27T17:03:22.631Z,677880f787ed7d2cfb6f7345,Speaker A from Debate 1,2026-01-27T17:08:09.003Z,60ed501279c68ea1a313d0aa,Speaker A from Debate 1,2026-01-27T17:17:37.693Z
3,019c004e-b479-7348-8a29-9781ff428810,6762026f-5d49-52d1-be4a-133965da5ff6,multiple_choice,How confident are you in your choice?,Debate the trade-offs of government interventi...,"Speaker B: ""The NHS in the UK continues to pro...","Speaker B: ""So does that mean that the whole p...",right,human_7,gpt-4o_mas_rag,"('human_7', 'human_8')",159,"[{'speaker': 'gpt-4o_mas_rag', 'timestamp': '2...","('DL3D7S', '6XAVOS')",671d3690dc5df6d004cfb65e,Somewhat confident,2026-01-27T16:52:05.218Z,5bb62f1a3e969700019bd44d,Somewhat unsure,2026-01-27T16:53:05.218Z,6704539fe462b87182866f14,Somewhat confident,2026-01-27T16:53:12.361Z,5c03e86d55555b0001caf233,Very confident,2026-01-27T16:53:15.495Z,5ac4b010f69e940001d97645,Somewhat confident,2026-01-27T16:53:27.744Z,54aefa06fdf99b09c01b37f4,Neutral,2026-01-27T16:53:56.045Z,5a5a6ed7f6c517000195029e,Very confident,2026-01-27T16:54:12.699Z,65537e14439274fe5036b4d2,Somewhat confident,2026-01-27T16:55:04.365Z,668dc7b684452eaca13eb60d,Somewhat confident,2026-01-27T16:55:25.805Z,56a757a95ad8d9000c970c76,Somewhat confident,2026-01-27T16:55:52.295Z,629dd4199343d7710fcdb39c,Very confident,2026-01-27T16:57:33.573Z,5a0f34de9b760100013a7afd,Somewhat confident,2026-01-27T16:57:34.140Z,6125646031b73d8171421e7c,Very confident,2026-01-27T16:58:25.996Z,5f0cf299c6db5770064402e1,Somewhat confident,2026-01-27T17:01:39.421Z,6007421356226920359b5f3e,Somewhat confident,2026-01-27T17:01:39.983Z,6100906e671b8294f9ea93d8,Very confident,2026-01-27T17:02:07.443Z,677a8e5affbe5673b3a79e6b,Neutral,2026-01-27T17:02:45.367Z,644fdc8d0d748ff99020fcae,Somewhat confident,2026-01-27T17:03:22.632Z,677880f787ed7d2cfb6f7345,Somewhat confident,2026-01-27T17:08:09.003Z,60ed501279c68ea1a313d0aa,Somewhat confident,2026-01-27T17:17:37.693Z
4,019c004e-b39c-763e-a452-76e60beaf993,cb54765c-b499-5c27-bc6b-c3422e99b557,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""Conditional welfare schemes active...","Speaker A: ""Preventative care in universal sys...",left,gpt-4o_mas,mistral-medium_mas,"('gpt-4o_mas', 'gpt-4o_mas_rag')",0,"[{'speaker': 'gpt-4o_mas', 'timestamp': '2025-...","('gpt-4o_mas:l__vs__mistral-medium_mas:r', 'gp...",5a8f01d95292b80001235d34,Speaker A from Debate 2,2026-01-27T16:52:12.574Z,59baf1a2178f1b0001828a26,Speaker A from Debate 2,2026-01-27T16:52:12.859Z,5bbb5e3f118c0600013c3202,Speaker A from Debate 2,2026-01-27T16:53:18.655Z,5d4310bbd8e961001b825ca4,Speaker A from Debate 2,2026-01-27T16:53:35.540Z,60524a9ece19f6b376473cf7,Speaker A from Debate 2,2026-01-27T16:54:50.526Z,5f69f87e83dfd701bfc84b39,Both Speaker As were equally persuasive,2026-01-27T16:55:11.195Z,5e908233a1ea4d013e973b75,Speaker A from Debate 2,2026-01-27T16:55:11.832Z,579f55486475d400015ab683,Speaker A from Debate 1,2026-01-27T16:57:34.022Z,613129fdf8f6b04c9a7a2429,Both Speaker As were equally persuasive,2026-01-27T16:57:58.615Z,669b9cae8f4c91285f2219d7,Speaker A from Debate 2,2026-01-27T16:58:27.273Z,574da26c7f1e770007f42d11,Speaker A from Debate 1,2026-01-27T17:00:34.507Z,55da1c4669dbc30010b67569,Speaker A from Debate 1,2026-01-27T17:00:35.545Z,5ea2e082eeb3d720ccb93f03,Both Speaker As were equally persuasive,2026-01-27T17:03:21.587Z,665ee374604d2c5d4d858efd,Speaker A from Debate 2,2026-01-27T17:03:57.456Z,5f5bb87a0093333445af65f2,Speaker A from Debate 1,2026-01-27T17:04:49.539Z,667a7ab2a6179deb78e9dd1a,Both Speaker As were equally persuasive,2026-01-27T17:05:52.721Z,67380a0419c95d7829fc2144,Speaker A from Debate 1,2026-01-27T17:08:55.064Z,5fbf90f025a567296d943c7e,Speaker A from Debate 2,2026-01-27T17:10:15.177Z,5ec79cbd44972a1fceed2719,Speaker A from Debate 2,2026-01-27T17:17:30.069Z,58693d5b1ed9d10001050196,Speaker A from Debate 2,2026-01-27T17:19:38.263Z

In [21]:
df["Question"][0]

'Based only on the debate transcripts, which Speaker A presented the more persuasive arguments?'

In [22]:
df[df["Question"] == "Based only on the debate transcripts, which Speaker A presented the more persuasive arguments?"]

,DataPoint_ID,Task_Group_ID,Task_Type,Question,Debate Topic,Debate 1,Debate 2,META_SAMPLE1_POLITICAL_POSITION,META_SAMPLE1_SPEAKERA,META_SAMPLE1_SPEAKERB,META_COMPARISON,META_COMPARISONID,META_SAMPLE1_DIALOGUE_CHUNK,META_PAIR_SESSION_IDS,Annotator1_ID,Annotator1_Response,Annotator1_Timestamp,Annotator2_ID,Annotator2_Response,Annotator2_Timestamp,Annotator3_ID,Annotator3_Response,Annotator3_Timestamp,Annotator4_ID,Annotator4_Response,Annotator4_Timestamp,Annotator5_ID,Annotator5_Response,Annotator5_Timestamp,Annotator6_ID,Annotator6_Response,Annotator6_Timestamp,Annotator7_ID,Annotator7_Response,Annotator7_Timestamp,Annotator8_ID,Annotator8_Response,Annotator8_Timestamp,Annotator9_ID,Annotator9_Response,Annotator9_Timestamp,Annotator10_ID,Annotator10_Response,Annotator10_Timestamp,Annotator11_ID,Annotator11_Response,Annotator11_Timestamp,Annotator12_ID,Annotator12_Response,Annotator12_Timestamp,Annotator13_ID,Annotator13_Response,Annotator13_Timestamp,Annotator14_ID,Annotator14_Response,Annotator14_Timestamp,Annotator15_ID,Annotator15_Response,Annotator15_Timestamp,Annotator16_ID,Annotator16_Response,Annotator16_Timestamp,Annotator17_ID,Annotator17_Response,Annotator17_Timestamp,Annotator18_ID,Annotator18_Response,Annotator18_Timestamp,Annotator19_ID,Annotator19_Response,Annotator19_Timestamp,Annotator20_ID,Annotator20_Response,Annotator20_Timestamp
0,019c004e-b441-77a8-b741-60a6e281c5a4,407a1775-fc8a-5da6-9bcd-c9879baf85cb,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""The government should allow parent...","Speaker A: ""I don't trust that they will const...",left,human_7,human_12,"('human_7', 'human_8')",158,"[{'speaker': 'human_12', 'timestamp': '2026-01...","('1XHC4T', 'RSQGNQ')",5d4d9ea8c088850019ec5b32,Speaker A from Debate 2,2026-01-27T16:50:50.367Z,5afbf02302b1b5000103e313,Speaker A from Debate 1,2026-01-27T16:51:57.594Z,5c4592d7f608210001a4b0a8,Speaker A from Debate 1,2026-01-27T16:53:06.922Z,5bbc3d95f1f9ba000141d855,Speaker A from Debate 1,2026-01-27T16:53:30.876Z,60d075b6af3d46debaf3cfd8,Both Speaker As were equally persuasive,2026-01-27T16:53:33.173Z,5dd0409d9ca8a312350a4118,Speaker A from Debate 1,2026-01-27T16:55:11.699Z,5d41925ef7b99500012b960e,Speaker A from Debate 1,2026-01-27T16:55:23.367Z,67696d49d386c9789b03b1da,Speaker A from Debate 1,2026-01-27T16:55:40.827Z,66f1c61208486d7c425dcefd,Speaker A from Debate 1,2026-01-27T16:55:45.647Z,5ef528c2a0603b16a793423d,Both Speaker As were equally persuasive,2026-01-27T16:55:47.568Z,5ede66237578b70c1548f73e,Speaker A from Debate 1,2026-01-27T16:56:37.851Z,5b68c9eb87af310001584803,Speaker A from Debate 2,2026-01-27T16:57:17.132Z,5b421b9ac2e3810001763252,Speaker A from Debate 2,2026-01-27T16:58:12.235Z,5f0d89b9547a8403103a0372,Speaker A from Debate 1,2026-01-27T16:58:34.338Z,60b542b8fbb1a6a2678f5054,Speaker A from Debate 1,2026-01-27T17:01:08.079Z,5755c957eb80c4000741a9ce,Speaker A from Debate 2,2026-01-27T17:01:52.818Z,66bbafb05de7e549455aa4ff,Speaker A from Debate 1,2026-01-27T17:05:00.034Z,6798ae13687f9a946efe51eb,Speaker A from Debate 1,2026-01-27T17:06:07.176Z,66a1561d05457dd7ec9cd3a8,Both Speaker As were equally persuasive,2026-01-27T17:10:56.125Z,5efc4644f6f5950008d892a2,Speaker A from Debate 2,2026-01-27T17:19:39.180Z
2,019c004e-b479-7348-8a29-9781ff428810,6762026f-5d49-52d1-be4a-133965da5ff6,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""The NHS in the UK continues to pro...","Speaker B: ""So does that mean that the whole p...",right,human_7,gpt-4o_mas_rag,"('human_7', 'human_8')",159,"[{'speaker': 'gpt-4o_mas_rag', 'timestamp': '2...","('DL3D7S', '6XAVOS')",671d3690dc5df6d004cfb65e,Speaker A from Debate 1,2026-01-27T16:52:05.218Z,5bb62f1a3e969700019bd44d,Both Speaker As were equally persuasive,2026-01-27T16:53:05.218Z,6704539fe462b87182866f14,Speaker A from Debate 1,2026-01-27T16:53:12.361Z,5c03e86d55555b0001caf233,Speaker A from Debate 2,2026-01-27T16:53:15.495Z,5ac4b010f69e940001d97645,Speaker A from Debate 1,2026-01-27T16:53:27.744Z,54aefa06fdf99b09c01b37f4,Speaker A from Debate 1,2026-01-27T16:53:56.045Z,5a5a6ed7f6c517000195029e,Both Speaker As were equally persuasive,2026-01-27T16:54:12.699Z,65537e14439274fe5036b4d2,Speaker A from Debate 2,2026-01-27T16:55:04.365Z,668dc7b684452eaca13eb60d,Speaker A from Debate 2,2026-01-27T16:55:25.805Z,56a757a95ad8d9000c970c76,Speaker A from Debate 1,2026-01-27T16:55:52.295Z,629dd4199343d7710fcdb39c,Speaker A from Debate 2,2026-01-27T16:57:33.573Z,5a0f34de9b760100013a7afd,Speaker A from Debate 2,2026-01-27T16:57:34.140Z,6125646031b73d8171421e7c,Speaker A from Debate 1,2026-01-27T16:58:25.996Z,5f0cf299c6db5770064402e1,Speaker A from Debate 1,2026-01-27T17:01:39.421Z,6007421356226920359b5f3e,Speaker A from Debate 1,2026-01-27T17:01:39.983Z,6100906e671b8294f9ea93d8,Speaker A from Debate 1,2026-01-27T17:02:07.443Z,677a8e5affbe5673b3a79e6b,Speaker A from Debate 2,2026-01-27T17:02:45.367Z,644fdc8d0d748ff99020fcae,Both Speaker As were equally persuasive,2026-01-27T17:03:22.631Z,677880f787ed7d2cfb6f7345,Speaker A from Debate 1,2026-01-27T17:08:09.003Z,60ed501279c68ea1a313d0aa,Speaker A from Debate 1,2026-01-27T17:17:37.693Z
4,019c004e-b39c-763e-a452-76e60beaf993,cb54765c-b499-5c27-bc6b-c3422e99b557,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""Conditional welfare schemes active...","Speaker A: ""Preventative care in universal sys...",left,gpt-4o_mas,mistral-medium_mas,"('gpt-4o_mas', 'gpt-4o_mas_rag')",0,"[{'speaker': 'gpt-4o_mas', 'timestamp': '2025-...","('gpt-4o_mas:l__vs__mistral-medium_mas:r', 'gp...",5a8f01d95292b80001235d34,Speaker A from Debate 2,2026-01-27T16:52:12.574Z,59baf1a2178f1b0001828a26,Speaker A from Debate 2,2026-01-27T16:52:12.859Z,5bbb5e3f118c0600013c3202,Speaker A from Debate 2,2026-01-27T16:53:18.655Z,5d4310bbd8e961001b825ca4,Speaker A from Debate 2,2026-01-27T16:53:35.540Z,60524a9ece19f6b376473cf7,Speaker A from Debate 2,2026-01-27T16:54:50.526Z,5f69f87e83dfd701bfc84b39,Both Speaker As were equally persuasive,2026-01-27T16:55:11.195Z,5e908233a1ea4d013e973b75,Speaker A from Debate 2,2026-01-27T16:55:11.832Z,579f55486475d400015ab683,Speaker A from Debate 1,2026-01-27T16:57:34.022Z,613129fdf8f6b04c9a7a2429,Both Speaker As were equally persuasive,2026-01-27T16:57:58.615Z,669b9cae8f4c91285f2219d7,Speaker A from Debate 2,2026-01-27T16:58:27.273Z,574da26c7f1e770007f42d11,Speaker A from Debate 1,2026-01-27T17:00:34.507Z,55da1c4669dbc30010b67569,Speaker A from Debate 1,2026-01-27T17:00:35.545Z,5ea2e082eeb3d720ccb93f03,Both Speaker As were equally persuasive,2026-01-27T17:03:21.587Z,665ee374604d2c5d4d858efd,Speaker A from Debate 2,2026-01-27T17:03:57.456Z,5f5bb87a0093333445af65f2,Speaker A from Debate 1,2026-01-27T17:04:49.539Z,667a7ab2a6179deb78e9dd1a,Both Speaker As were equally persuasive,2026-01-27T17:05:52.721Z,67380a0419c95d7829fc2144,Speaker A from Debate 1,2026-01-27T17:08:55.064Z,5fbf90f025a567296d943c7e,Speaker A from Debate 2,2026-01-27T17:10:15.177Z,5ec79cbd44972a1fceed2719,Speaker A from Debate 2,2026-01-27T17:17:30.069Z,58693d5b1ed9d10001050196,Speaker A from Debate 2,2026-01-27T17:19:38.263Z
6,019c004e-b4a6-74bc-b420-c24b2f84dab4,bd318cc4-b519-5140-a00d-46170314413d,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""It isn't reasonable to assume that...","Speaker B: ""The government should crack down o...",left,human_3,human_1,"('human_3', 'human_12')",178,"[{'speaker': 'human_3', 'timestamp': '2026-01-...","('B1QOQZ', 'NEZTYI')",5964ee31b752840001ca4ba4,Speaker A from Debate 1,2026-01-27T16:51:30.396Z,5c93b062c9d93b0015fcbc02,Speaker A from Debate 1,2026-01-27T16:52:29.177Z,6978c27699b03621e7f724f6,Speaker A from Debate 1,2026-01-27T16:52:58.918Z,678e978dfeca0ba2fca8109f,Speaker A from Debate 1,2026-01-27T16:53:07.139Z,682b3f63d0e2c4eff64fe664,Both Speaker As were equally persuasive,2026-01-27T16:53:22.123Z,6669a77e7f1a7b2fcdd8171f,Speaker A from Debate 1,2026-01-27T16:54:06.777Z,5d190e1c686b190018ea4d86,Speaker A from Debate 2,2026-01-27T16:54:11.998Z,5f85c88c61e23608718cbd03,Speaker A from Debate 1,2026-01-27T16:54:27.164Z,5d542c3a5af5900019bc80c4,Both Speaker As were equally persuasive,2026-01-27T16:54:55.177Z,678cb09be2da97686a860d32,Speaker A from Debate 1,2026-01-27T16:55:17.076Z,55d51a6b8ce09000127d4821,Speaker A from Debate 1,2026-01-27T16:55:22.590Z,62b38331e0ef38710a5b0c78,Speaker A from Debate 1,2026-01-27T16:56:19.480Z,67229e0529249d25d00b1a87,Speaker A from Debate 1,2026-01-27T16:58:21.235Z,670426ac729d4ec0254bedd8,Speaker A from Debate 1,2026-01-27T16:58:35.286Z,637f7d10665738cfea163256,Speaker A from Debate 1,2026-01-27T17:01:30.388Z,5ccc76bbc7508d0017d35954,Speaker A from Debate 1,2026-01-27T17:02:02.342Z,63d7b30ddc8ceb61c74fe85b,Both Speaker As were equally persuasive,2026-01-27T17:04:36.894Z,5d9750fe74d24900145633a7,Speaker A from Debate 1,2026-01-27T17:07:19.358Z,62b4403257f7d42730f83394,Speaker A from Debate 1,2026-01-27T17:08:49.920Z,6121727de83f87433cb96b08,Speaker A from Debate 2,2026-01-27T17:15:52.268Z
8,019c004e-b3d1-775d-8b47-289a3cab9eeb,e90a33ed-3b63-5f82-b597-1fa405597e25,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""Did you see the current job market...","Speaker A: ""Private solutions prioritising pro...",left,human,human_13,"('human', 'mistral-medium_base')",34,"[{'speaker': 'human_13', 'timestamp': '2026-01...","('KNI0QV', 'gpt-4o_base:r__vs__mistral-medium_...",60f5d1dfd8ff71196982160b,Speaker A from Debate 2,2026-01-27T16:52:14.552Z,6978c3a72db1c98638d31aa7,Speaker A from Debate 2,2026-01-27T16:52:37.516Z,612842ca25ad8ffd1b8e44ec,Speaker A from Debate 1,2026-01-27T16:52:53.499Z,66d329d8beefe060d4c648e3,Speaker A from Debate 1,2026-01-27T16:53:23.001Z,58f669cefb4d7500014af69b,Speaker A from Debate 1,2026-01-27T16:53:37.404Z,5e8f8ebc09b58f28c329da6f,Speaker A from Debate 1,2026-01-27T16:54:09.900Z,600b5191a434df19524dd1a0,Speaker A from Debate 2,2026-01-27T16:54:22.586Z,5f3ec93efbd299158253f283,Speaker A from Debate 2,2026-01-27T16:54:32.537Z,59fc8a30087f2e0001ead66d,Speaker A from Debate 2,2026-01-27T16:54:45.927Z,5af6e439672ea800010d4e92,Speaker A from Debate 2,2026-01-27T16:56:34.374Z,5e84edae53c6f80a42d74120,Speaker A from Debate 1,2026-01-27T16:56:38.282Z,63f77f79278126e103659cf4,Speaker A from Debate 1,2026-01-27T16:57:29.720Z,6571fd9d691befe21fa61d18,Speaker A from Debate 2,2026-01-27T16:57:44.811Z,5e299d8c2e9dc4000be0fde0,Speaker A from Debate 2,2026-01-27T17:01:30.584Z,5bb7abf3c190e20001e5c2c8,Speaker A from Debate 2,2026-01-27T17:01:37.836Z,5f78863ec51814422de56470,Speaker A from Debate 1,2026-01-27T17:02:40.043Z,5b17642244127b00013f7f65,Speaker A from Debate 1,2026-01-27T17:02:55.366Z,5d5a75c570a7c1000152623e,Speaker A from Debate 2,2026-01-27T17:04:35.976Z,5a8367b9190420000155ec2a,Speaker A from Debate 2,2026-01-27T17:07:53.517Z,6655f13e04490671e36a8dcf,Speaker A from Debate 2,2026-01-27T17:12:35.374Z

In [23]:
annotator_cols = [col for col in df.columns if col.endswith('_Response')]
responses = df[annotator_cols].melt(value_name='response')['response']
response_counts = responses.value_counts()
print(response_counts)

response
Somewhat confident                         58
Speaker A from Debate 1                    51
Speaker A from Debate 2                    36
Very confident                             29
Both Speaker As were equally persuasive    13
Somewhat unsure                             7
Neutral                                     6
Name: count, dtype: int64

In [24]:
# annotator_cols = [col for col in df.columns if col.endswith('_Response')]

# df['sample1_count'] = (df[annotator_cols] == "Speaker A from Debate 1").sum(axis=1)
# df['sample2_count'] = (df[annotator_cols] == "Speaker A from Debate 2").sum(axis=1)

In [25]:
annotator_cols = [col for col in df.columns if col.endswith('_Response')]

# Only consider rows where the Question matches the target
target_rows = df["Question"] == "Based only on the debate transcripts, which Speaker A presented the more persuasive arguments?"

def count_sample1(row):
    return sum([
        1 if val == "Speaker A from Debate 1" else
        0.5 if val == "Both Speaker As were equally persuasive" else
        0
        for val in row
    ])

def count_sample2(row):
    return sum([
        1 if val == "Speaker A from Debate 2" else
        0.5 if val == "Both Speaker As were equally persuasive" else
        0
        for val in row
    ])

df.loc[target_rows, 'sample1_count'] = df.loc[target_rows, annotator_cols].apply(count_sample1, axis=1)
df.loc[target_rows, 'sample2_count'] = df.loc[target_rows, annotator_cols].apply(count_sample2, axis=1)

df

,DataPoint_ID,Task_Group_ID,Task_Type,Question,Debate Topic,Debate 1,Debate 2,META_SAMPLE1_POLITICAL_POSITION,META_SAMPLE1_SPEAKERA,META_SAMPLE1_SPEAKERB,META_COMPARISON,META_COMPARISONID,META_SAMPLE1_DIALOGUE_CHUNK,META_PAIR_SESSION_IDS,Annotator1_ID,Annotator1_Response,Annotator1_Timestamp,Annotator2_ID,Annotator2_Response,Annotator2_Timestamp,Annotator3_ID,Annotator3_Response,Annotator3_Timestamp,Annotator4_ID,Annotator4_Response,Annotator4_Timestamp,Annotator5_ID,Annotator5_Response,Annotator5_Timestamp,Annotator6_ID,Annotator6_Response,Annotator6_Timestamp,Annotator7_ID,Annotator7_Response,Annotator7_Timestamp,Annotator8_ID,Annotator8_Response,Annotator8_Timestamp,Annotator9_ID,Annotator9_Response,Annotator9_Timestamp,Annotator10_ID,Annotator10_Response,Annotator10_Timestamp,Annotator11_ID,Annotator11_Response,Annotator11_Timestamp,Annotator12_ID,Annotator12_Response,Annotator12_Timestamp,Annotator13_ID,Annotator13_Response,Annotator13_Timestamp,Annotator14_ID,Annotator14_Response,Annotator14_Timestamp,Annotator15_ID,Annotator15_Response,Annotator15_Timestamp,Annotator16_ID,Annotator16_Response,Annotator16_Timestamp,Annotator17_ID,Annotator17_Response,Annotator17_Timestamp,Annotator18_ID,Annotator18_Response,Annotator18_Timestamp,Annotator19_ID,Annotator19_Response,Annotator19_Timestamp,Annotator20_ID,Annotator20_Response,Annotator20_Timestamp,sample1_count,sample2_count
0,019c004e-b441-77a8-b741-60a6e281c5a4,407a1775-fc8a-5da6-9bcd-c9879baf85cb,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""The government should allow parent...","Speaker A: ""I don't trust that they will const...",left,human_7,human_12,"('human_7', 'human_8')",158,"[{'speaker': 'human_12', 'timestamp': '2026-01...","('1XHC4T', 'RSQGNQ')",5d4d9ea8c088850019ec5b32,Speaker A from Debate 2,2026-01-27T16:50:50.367Z,5afbf02302b1b5000103e313,Speaker A from Debate 1,2026-01-27T16:51:57.594Z,5c4592d7f608210001a4b0a8,Speaker A from Debate 1,2026-01-27T16:53:06.922Z,5bbc3d95f1f9ba000141d855,Speaker A from Debate 1,2026-01-27T16:53:30.876Z,60d075b6af3d46debaf3cfd8,Both Speaker As were equally persuasive,2026-01-27T16:53:33.173Z,5dd0409d9ca8a312350a4118,Speaker A from Debate 1,2026-01-27T16:55:11.699Z,5d41925ef7b99500012b960e,Speaker A from Debate 1,2026-01-27T16:55:23.367Z,67696d49d386c9789b03b1da,Speaker A from Debate 1,2026-01-27T16:55:40.827Z,66f1c61208486d7c425dcefd,Speaker A from Debate 1,2026-01-27T16:55:45.647Z,5ef528c2a0603b16a793423d,Both Speaker As were equally persuasive,2026-01-27T16:55:47.568Z,5ede66237578b70c1548f73e,Speaker A from Debate 1,2026-01-27T16:56:37.851Z,5b68c9eb87af310001584803,Speaker A from Debate 2,2026-01-27T16:57:17.132Z,5b421b9ac2e3810001763252,Speaker A from Debate 2,2026-01-27T16:58:12.235Z,5f0d89b9547a8403103a0372,Speaker A from Debate 1,2026-01-27T16:58:34.338Z,60b542b8fbb1a6a2678f5054,Speaker A from Debate 1,2026-01-27T17:01:08.079Z,5755c957eb80c4000741a9ce,Speaker A from Debate 2,2026-01-27T17:01:52.818Z,66bbafb05de7e549455aa4ff,Speaker A from Debate 1,2026-01-27T17:05:00.034Z,6798ae13687f9a946efe51eb,Speaker A from Debate 1,2026-01-27T17:06:07.176Z,66a1561d05457dd7ec9cd3a8,Both Speaker As were equally persuasive,2026-01-27T17:10:56.125Z,5efc4644f6f5950008d892a2,Speaker A from Debate 2,2026-01-27T17:19:39.180Z,13.5,6.5
1,019c004e-b441-77a8-b741-60a6e281c5a4,407a1775-fc8a-5da6-9bcd-c9879baf85cb,multiple_choice,How confident are you in your choice?,Debate the trade-offs of government interventi...,"Speaker B: ""The government should allow parent...","Speaker A: ""I don't trust that they will const...",left,human_7,human_12,"('human_7', 'human_8')",158,"[{'speaker': 'human_12', 'timestamp': '2026-01...","('1XHC4T', 'RSQGNQ')",5d4d9ea8c088850019ec5b32,Somewhat unsure,2026-01-27T16:50:50.367Z,5afbf02302b1b5000103e313,Very confident,2026-01-27T16:51:57.594Z,5c4592d7f608210001a4b0a8,Somewhat confident,2026-01-27T16:53:06.922Z,5bbc3d95f1f9ba000141d855,Very confident,2026-01-27T16:53:30.876Z,60d075b6af3d46debaf3cfd8,Somewhat confident,2026-01-27T16:53:33.173Z,5dd0409d9ca8a312350a4118,Somewhat confident,2026-01-27T16:55:11.699Z,5d41925ef7b99500012b960e,Very confident,2026-01-27T16:55:23.368Z,67696d49d386c9789b03b1da,Somewhat confident,2026-01-27T16:55:40.827Z,66f1c61208486d7c425dcefd,Somewhat confident,2026-01-27T16:55:45.647Z,5ef528c2a0603b16a793423d,Somewhat confident,2026-01-27T16:55:47.568Z,5ede66237578b70c1548f73e,Somewhat confident,2026-01-27T16:56:37.851Z,5b68c9eb87af310001584803,Very confident,2026-01-27T16:57:17.132Z,5b421b9ac2e3810001763252,Somewhat confident,2026-01-27T16:58:12.235Z,5f0d89b9547a8403103a0372,Somewhat confident,2026-01-27T16:58:34.338Z,60b542b8fbb1a6a2678f5054,Very confident,2026-01-27T17:01:08.079Z,5755c957eb80c4000741a9ce,Somewhat unsure,2026-01-27T17:01:52.818Z,66bbafb05de7e549455aa4ff,Somewhat confident,2026-01-27T17:05:00.034Z,6798ae13687f9a946efe51eb,Somewhat confident,2026-01-27T17:06:07.176Z,66a1561d05457dd7ec9cd3a8,Neutral,2026-01-27T17:10:56.125Z,5efc4644f6f5950008d892a2,Neutral,2026-01-27T17:19:39.180Z,NaN,NaN
2,019c004e-b479-7348-8a29-9781ff428810,6762026f-5d49-52d1-be4a-133965da5ff6,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""The NHS in the UK continues to pro...","Speaker B: ""So does that mean that the whole p...",right,human_7,gpt-4o_mas_rag,"('human_7', 'human_8')",159,"[{'speaker': 'gpt-4o_mas_rag', 'timestamp': '2...","('DL3D7S', '6XAVOS')",671d3690dc5df6d004cfb65e,Speaker A from Debate 1,2026-01-27T16:52:05.218Z,5bb62f1a3e969700019bd44d,Both Speaker As were equally persuasive,2026-01-27T16:53:05.218Z,6704539fe462b87182866f14,Speaker A from Debate 1,2026-01-27T16:53:12.361Z,5c03e86d55555b0001caf233,Speaker A from Debate 2,2026-01-27T16:53:15.495Z,5ac4b010f69e940001d97645,Speaker A from Debate 1,2026-01-27T16:53:27.744Z,54aefa06fdf99b09c01b37f4,Speaker A from Debate 1,2026-01-27T16:53:56.045Z,5a5a6ed7f6c517000195029e,Both Speaker As were equally persuasive,2026-01-27T16:54:12.699Z,65537e14439274fe5036b4d2,Speaker A from Debate 2,2026-01-27T16:55:04.365Z,668dc7b684452eaca13eb60d,Speaker A from Debate 2,2026-01-27T16:55:25.805Z,56a757a95ad8d9000c970c76,Speaker A from Debate 1,2026-01-27T16:55:52.295Z,629dd4199343d7710fcdb39c,Speaker A from Debate 2,2026-01-27T16:57:33.573Z,5a0f34de9b760100013a7afd,Speaker A from Debate 2,2026-01-27T16:57:34.140Z,6125646031b73d8171421e7c,Speaker A from Debate 1,2026-01-27T16:58:25.996Z,5f0cf299c6db5770064402e1,Speaker A from Debate 1,2026-01-27T17:01:39.421Z,6007421356226920359b5f3e,Speaker A from Debate 1,2026-01-27T17:01:39.983Z,6100906e671b8294f9ea93d8,Speaker A from Debate 1,2026-01-27T17:02:07.443Z,677a8e5affbe5673b3a79e6b,Speaker A from Debate 2,2026-01-27T17:02:45.367Z,644fdc8d0d748ff99020fcae,Both Speaker As were equally persuasive,2026-01-27T17:03:22.631Z,677880f787ed7d2cfb6f7345,Speaker A from Debate 1,2026-01-27T17:08:09.003Z,60ed501279c68ea1a313d0aa,Speaker A from Debate 1,2026-01-27T17:17:37.693Z,12.5,7.5
3,019c004e-b479-7348-8a29-9781ff428810,6762026f-5d49-52d1-be4a-133965da5ff6,multiple_choice,How confident are you in your choice?,Debate the trade-offs of government interventi...,"Speaker B: ""The NHS in the UK continues to pro...","Speaker B: ""So does that mean that the whole p...",right,human_7,gpt-4o_mas_rag,"('human_7', 'human_8')",159,"[{'speaker': 'gpt-4o_mas_rag', 'timestamp': '2...","('DL3D7S', '6XAVOS')",671d3690dc5df6d004cfb65e,Somewhat confident,2026-01-27T16:52:05.218Z,5bb62f1a3e969700019bd44d,Somewhat unsure,2026-01-27T16:53:05.218Z,6704539fe462b87182866f14,Somewhat confident,2026-01-27T16:53:12.361Z,5c03e86d55555b0001caf233,Very confident,2026-01-27T16:53:15.495Z,5ac4b010f69e940001d97645,Somewhat confident,2026-01-27T16:53:27.744Z,54aefa06fdf99b09c01b37f4,Neutral,2026-01-27T16:53:56.045Z,5a5a6ed7f6c517000195029e,Very confident,2026-01-27T16:54:12.699Z,65537e14439274fe5036b4d2,Somewhat confident,2026-01-27T16:55:04.365Z,668dc7b684452eaca13eb60d,Somewhat confident,2026-01-27T16:55:25.805Z,56a757a95ad8d9000c970c76,Somewhat confident,2026-01-27T16:55:52.295Z,629dd4199343d7710fcdb39c,Very confident,2026-01-27T16:57:33.573Z,5a0f34de9b760100013a7afd,Somewhat confident,2026-01-27T16:57:34.140Z,6125646031b73d8171421e7c,Very confident,2026-01-27T16:58:25.996Z,5f0cf299c6db5770064402e1,Somewhat confident,2026-01-27T17:01:39.421Z,6007421356226920359b5f3e,Somewhat confident,2026-01-27T17:01:39.983Z,6100906e671b8294f9ea93d8,Very confident,2026-01-27T17:02:07.443Z,677a8e5affbe5673b3a79e6b,Neutral,2026-01-27T17:02:45.367Z,644fdc8d0d748ff99020fcae,Somewhat confident,2026-01-27T17:03:22.632Z,677880f787ed7d2cfb6f7345,Somewhat confident,2026-01-27T17:08:09.003Z,60ed501279c68ea1a313d0aa,Somewhat confident,2026-01-27T17:17:37.693Z,NaN,NaN
4,019c004e-b39c-763e-a452-76e60beaf993,cb54765c-b499-5c27-bc6b-c3422e99b557,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""Conditional welfare schemes active...","Speaker A: ""Preventative care in universal sys...",left,gpt-4o_mas,mistral-medium_mas,"('gpt-4o_mas', 'gpt-4o_mas_rag')",0,"[{'speaker': 'gpt-4o_mas', 'timestamp': '2025-...","('gpt-4o_mas:l__vs__mistral-medium_mas:r', 'gp...",5a8f01d95292b80001235d34,Speaker A from Debate 2,2026-01-27T16:52:12.574Z,59baf1a2178f1b0001828a26,Speaker A from Debate 2,2026-01-27T16:52:12.859Z,5bbb5e3f118c0600013c3202,Speaker A from Debate 2,2026-01-27T16:53:18.655Z,5d4310bbd8e961001b825ca4,Speaker A from Debate 2,2026-01-27T16:53:35.540Z,60524a9ece19f6b376473cf7,Speaker A from Debate 2,2026-01-27T16:54:50.526Z,5f69f87e83dfd701bfc84b39,Both Speaker As were equally persuasive,2026-01-27T16:55:11.195Z,5e908233a1ea4d013e973b75,Speaker A from Debate 2,2026-01-27T16:55:11.832Z,579f55486475d400015ab683,Speaker A from Debate 1,2026-01-27T16:57:34.022Z,613129fdf8f6b04c9a7a2429,Both Speaker As were equally persuasive,2026-01-27T16:57:58.615Z,669b9cae8f4c91285f2219d7,Speaker A from Debate 2,2026-01-27T16:58:27.273Z,574da26c7f1e770007f42d11,Speaker A from Debate 1,2026-01-27T17:00:34.507Z,55da1c4669dbc30010b67569,Speaker A from Debate 1,2026-01-27T17:00:35.545Z,5ea2e082eeb3d720ccb93f03,Both Speaker As were equally persuasive,2026-01-27T17:03:21.587Z,665ee374604d2c5d4d858efd,Speaker A from Debate 2,2026-01-27T17:03:57.456Z,5f5bb87a0093333445af65f2,Speaker A from Debate 1,2026-01-27T17:04:49.539Z,667a7ab2a6179deb78e9dd1a,Both Speaker As were equally persuasive,2026-01-27T17:05:52.721Z,67380a0419c95d7829fc2144,Speaker A from Debate 1,2026-01-27T17:08:55.064Z,5fbf90f025a567296d943c7e,Speaker A from Debate 2,2026-01-27T17:10:15.177Z,5ec79cbd44972a1fceed2719,Speaker A from Debate 2,2026-01-27T17:17:30.069Z,58693d5b1ed9d10001050196,Speaker A from Debate 2,2026-01-27T17:19:38.263Z,7.0,13.0
5,019c004e-b39c-763e-a452-76e60beaf993,cb54765c-b499-5c27-bc6b-c3422e99b557,multiple_choice,How confident are you in your choice?,Debate the trade-offs of government interventi...,"Speaker A: ""Conditional welfare schemes active...","Speaker A: ""Preventative care in universal sys...",left,gpt-4o_mas,mistral-medium_mas,"('gpt-4o_mas', 'gpt-4o_mas_rag')",0,"[{'speaker': 'gpt-4o_mas', 'timestamp': '2025-...","('gpt-4o_mas:l__vs__mistral-medium_mas:r', 'gp...",5a8f01d95292b80001235d34,Somewhat confident,2026-01-27T16:52:12.574Z,59baf1a2178f1b0001828a26,Somewhat confident,2026-01-27T16:52:12.865Z,5bbb5e3f118c0600013c3202,Somewhat confident,2026-01-27T16:53:18.656Z,5d4310bbd8e961001b825ca4,Very confident,2026-01-27T16:53:35.540Z,60524a9ece19f6b376473cf7,Somewhat confident,2026-01-27T16:54:50.526Z,5f69f87e83dfd701bfc84b39,Very confident,2026-01-27T16:55:11.195Z,5e908233a1ea4d013e973b75,Somewhat confident,2026-01-27T16:55:11.833Z,579f55486475d400015ab683,Somewhat confident,2026-01-27T16:57:34.023Z,613129fdf8f6b04c9a7a2429,Very confident,2026-01-27T16:57:58.615Z,669b9cae8f4c91285f2219d7,Somewhat confident,2026-01-27T16:58:27.273Z,574da26c7f1e770007f42d11,Somewhat confident,2026-01-27T17:00:34.507Z,55da1c4669dbc30010b67569,Somewhat confident,2026-01-27T17:00:35.545Z,5ea2e082eeb3d720ccb93f03,Somewhat confident,2026-01-27T17:03:21.587Z,665ee374604d2c5d4d858efd,Somewhat confident,2026-01-27T17:03:57.456Z,5f5bb87a0093333445af65f2,Very confident,2026-01-27T17:04:49.539Z,667a7ab2a6179deb78e9dd1a,Somewhat unsure,2026-01-27T17:05:52.721Z,67380a0419c95d7829fc2144,Somewhat confident,2026-01-27T17:08:55.064Z,5fbf90f025a567296d943c7e,Somewhat confident,2026-01-27T17:10:15.177Z,5ec79cbd44972a1fceed2719,Neutral,2026-01-27T17:17:30.069Z,58693d5b1ed9d10001050196,Very confident,2026-01-27T17:19:38.263Z,NaN,NaN
6,019c004e-b4a6-74bc-b420-c24b2f84dab4,bd318cc4-b519-5140-a00d-46170314413d,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""It isn't reasonable to assume that...","Speaker B: ""The government should crack down o...",left,human_3,human_1,"('human_3', 'human_12')",178,"[{'speaker': 'human_3', 'timestamp': '2026-01-...","('B1QOQZ', 'NEZTYI')",5964ee31b752840001ca4ba4,Speaker A from Debate 1,2026-01-27T16:51:30.396Z,5c93b062c9d93b0015fcbc02,Speaker A from Debate 1,2026-01-27T16:52:29.177Z,6978c27699b03621e7f724f6,Speaker A from Debate 1,2026-01-27T16:52:58.918Z,678e978dfeca0ba2fca8109f,Speaker A from Debate 1,2026-01-27T16:53:07.139Z,682b3f63d0e2c4eff64fe664,Both Speaker As were equally persuasive,2026-01-27T16:53:22.123Z,6669a77e7f1a7b2fcdd8171f,Speaker A from Debate 1,2026-01-27T16:54:06.777Z,5d190e1c686b190018ea4d86,Speaker A from Debate 2,2026-01-27T16:54:11.998Z,5f85c88c61e23608718cbd03,Speaker A from Debate 1,2026-01-27T16:54:27.164Z,5d542c3a5af5900019bc80c4,Both Speaker As were equally persuasive,2026-01-27T16:54:55.177Z,678cb09be2da97686a860d32,Speaker A from Debate 1,2026-01-27T16:55:17.076Z,55d51a6b8ce09000127d4821,Speaker A from Debate 1,2026-01-27T16:55:22.590Z,62b38331e0ef38710a5b0c78,Speaker A from Debate 1,2026-01-27T16:56:19.480Z,67229e0529249d25d00b1a87,Speaker A from Debate 1,2026-01-27T16:58:21.235Z,670426ac729d4ec0254bedd8,Speaker A from Debate 1,2026-01-27T16:58:35.286Z,637f7d10665738cfea163256,Speaker A from Debate 1,2026-01-27T17:01:30.388Z,5ccc76bbc7508d0017d35954,Speaker A from Debate 1,2026-01-27T17:02:02.342Z,63d7b30ddc8ceb61c74fe85b,Both Speaker As were equally persuasive,2026-01-27T17:04:36.894Z,5d9750fe74d24900145633a7,Speaker A from Debate 1,2026-01-27T17:07:19.358Z,62b4403257f7d42730f83394,Speaker A from Debate 1,2026-01-27T17:08:49.920Z,6121727de83f87433cb96b08,Speaker A from Debate 2,2026-01-27T17:15:52.268Z,16.5,3.5
7,019c004e-b4a6-74bc-b420-c24b2f84dab4,bd318cc4-b519-5140-a00d-46170314413d,multiple_choice,How confident are you in your choice?,Debate the trade-offs of government interventi...,"Speaker A: ""It isn't reasonable to assume that...","Speaker B: ""The government should crack down o...",left,human_3,human_1,"('human_3', 'human_12')",178,"[{'speaker': 'human_3', 'timestamp': '2026-01-...","('B1QOQZ', 'NEZTYI')",5964ee31b752840001ca4ba4,Somewhat confident,2026-01-27T16:51:30.396Z,5c93b062c9d93b0015fcbc02,Very confident,2026-01-27T16:52:29.177Z,6978c27699b03621e7f724f6,Very confident,2026-01-27T16:52:58.918Z,678e978dfeca0ba2fca8109f,Very confident,2026-01-27T16:53:07.140Z,682b3f63d0e2c4eff64fe664,Very confident,2026-01-27T16:53:22.123Z,6669a77e7f1a7b2fcdd8171f,Somewhat confident,2026-01-27T16:54:06.777Z,5d190e1c686b190018ea4d86,Somewhat confident,2026-01-27T16:54:11.998Z,5f85c88c61e23608718cbd03,Somewhat unsure,2026-01-27T16:54:27.164Z,5d542c3a5af5900019bc80c4,Somewhat confident,2026-01-27T16:54:55.177Z,678cb09be2da97686a860d32,Somewhat confident,2026-01-27T16:55:17.077Z,55d51a6b8ce09000127d4821,Very confident,2026-01-27T16:55:22.590Z,62b38331e0ef38710a5b0c78,Neutral,2026-01-27T16:56:19.480Z,67229e0529249d25d00b1a87,Very confident,2026-01-27T16:58:21.235Z,670426ac729d4ec0254bedd8,Somewhat confident,2026-01-27T16:58:35.286Z,637f7d10665738cfea163256,Somewhat confident,2026-01-27T17:01:30.388Z,5ccc76bbc7508d0017d35954,Somewhat confident,2026-01-27T17:02:02.342Z,63d7b30ddc8ceb61c74fe85b,Somewhat confident,2026-01-27T17:04:36.894Z,5d9750fe74d24900145633a7,Somewhat confident,2026-01-27T17:07:19.358Z,62b4403257f7d42730f83394,Somewhat confident,2026-01-27T17:08:49.921Z,6121727de83f87433cb96b08,Somewhat confident,2026-01-27T17:15:52.268Z,NaN,NaN
8,019c004e-b3d1-775d-8b47-289a3cab9eeb,e90a33ed-3b63-5f82-b597-1fa405597e25,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""Did you see the current job market...","Speaker A: ""Private solutions prioritising pro...",left,human,human_13,"('human', 'mistral-medium_base')",34,"[{'speaker': 'human_13', 'timestamp': '2026-01...","('KNI0QV', 'gpt-4o_base:r__vs__mistral-medium_...",60f5d1dfd8ff71196982160b,Speaker A from Debate 2,2026-01-27T16:52:14.552Z,6978c3a72db1c98638d31aa7,Speaker A from Debate 2,2026-01-27T16:52:37.516Z,612842ca25ad8ffd1b8e44ec,Speaker A from Debate 1,2026-01-27T16:52:53.499Z,66d329d8beefe060d4c648e3,Speaker A from Debate 1,2026-01-27T16:53:23.001Z,58f669cefb4d7500014af69b,Speaker A from Debate 1,2026-01-27T16:53:37.404Z,5e8f8ebc09b58f28c329da6f,Speaker A from Debate 1,2026-01-27T16:54:09.900Z,600b5191a434df19524dd1a0,Speaker A from Debate 2,2026-01-27T16:54:22.586Z,5f3ec93efbd299158253f283,Speaker A from Debate 2,2026-01-27T16:54:32.537Z,59fc8a30087f2e0001ead66d,Speaker A from Debate 2,2026-01-27T16:54:45.927Z,5af6e439672ea800010d4e92,Speaker A from Debate 2,2026-01-27T16:56:34.374Z,5e84edae53c6f80a42d74120,Speaker A from Debate 1,2026-01-27T16:56:38.282Z,63f77f79278126e103659cf4,Speaker A from Debate 1,2026-01-27T16:57:29.720Z,6571fd9d691befe21fa61d18,Speaker A from Debate 2,2026-01-27T16:57:44.811Z,5e299d8c2e9dc4000be0fde0,Speaker A from Debate 2,2026-01-27T17:01:30.584Z,5bb7abf3c190e20001e5c2c8,Speaker A from Debate 2,2026-01-27T17:01:37.836Z,5f78863ec51814422de56470,Speaker A from Debate 1,2026-01-27T17:02:40.043Z,5b17642244127b00013f7f65,Speaker A from Debate 1,2026-01-27T17:02:55.366Z,5d5a75c570a7c1000152623e,Speaker A from Debate 2,2026-01-27T17:04:35.976Z,5a8367b9190420000155ec2a,Speaker A from Debate 2,2026-01-27T17:07:53.517Z,6655f13e04490671e36a8dcf,Speaker A from Debate 2,2026-01-27T17:12:35.374Z,8.0,12.0

In [26]:
# annotator_cols = [col for col in df.columns if col.endswith('_Response')]

# # Only consider rows where the Question matches the target
# target_rows = df["Question"] == "Based only on the debate transcripts, which Speaker A presented the more persuasive arguments?"

# df.loc[target_rows, 'sample1_count'] = (df.loc[target_rows, annotator_cols] == "Speaker A from Debate 1").sum(axis=1)
# df.loc[target_rows, 'sample2_count'] = (df.loc[target_rows, annotator_cols] == "Speaker A from Debate 2").sum(axis=1)

In [ ]:
likert_map = {
        "Very unsure": 1,
            "Somewhat unsure": 2,
                "Neutral": 3,
                    "Somewhat confident": 4,
                        "Very confident": 5
                        }


# Select only the rows for the confidence question
conf_rows = df["Question"] == "How confident are you in your choice?"

# Select annotator columns
annotator_cols = [col for col in df.columns if col.endswith('_Response')]

# Map likert responses to numbers
df_conf_numeric = df.loc[conf_rows, annotator_cols].replace(likert_map)

# Compute the mean for each row
df.loc[conf_rows, "average_confidence"] = df_conf_numeric.mean(axis=1)
df.loc[conf_rows, "std_confidence"] = df_conf_numeric.std(axis=1)

In [28]:
df

,DataPoint_ID,Task_Group_ID,Task_Type,Question,Debate Topic,Debate 1,Debate 2,META_SAMPLE1_POLITICAL_POSITION,META_SAMPLE1_SPEAKERA,META_SAMPLE1_SPEAKERB,META_COMPARISON,META_COMPARISONID,META_SAMPLE1_DIALOGUE_CHUNK,META_PAIR_SESSION_IDS,Annotator1_ID,Annotator1_Response,Annotator1_Timestamp,Annotator2_ID,Annotator2_Response,Annotator2_Timestamp,Annotator3_ID,Annotator3_Response,Annotator3_Timestamp,Annotator4_ID,Annotator4_Response,Annotator4_Timestamp,Annotator5_ID,Annotator5_Response,Annotator5_Timestamp,Annotator6_ID,Annotator6_Response,Annotator6_Timestamp,Annotator7_ID,Annotator7_Response,Annotator7_Timestamp,Annotator8_ID,Annotator8_Response,Annotator8_Timestamp,Annotator9_ID,Annotator9_Response,Annotator9_Timestamp,Annotator10_ID,Annotator10_Response,Annotator10_Timestamp,Annotator11_ID,Annotator11_Response,Annotator11_Timestamp,Annotator12_ID,Annotator12_Response,Annotator12_Timestamp,Annotator13_ID,Annotator13_Response,Annotator13_Timestamp,Annotator14_ID,Annotator14_Response,Annotator14_Timestamp,Annotator15_ID,Annotator15_Response,Annotator15_Timestamp,Annotator16_ID,Annotator16_Response,Annotator16_Timestamp,Annotator17_ID,Annotator17_Response,Annotator17_Timestamp,Annotator18_ID,Annotator18_Response,Annotator18_Timestamp,Annotator19_ID,Annotator19_Response,Annotator19_Timestamp,Annotator20_ID,Annotator20_Response,Annotator20_Timestamp,sample1_count,sample2_count,average_confidence,std_confidence
0,019c004e-b441-77a8-b741-60a6e281c5a4,407a1775-fc8a-5da6-9bcd-c9879baf85cb,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""The government should allow parent...","Speaker A: ""I don't trust that they will const...",left,human_7,human_12,"('human_7', 'human_8')",158,"[{'speaker': 'human_12', 'timestamp': '2026-01...","('1XHC4T', 'RSQGNQ')",5d4d9ea8c088850019ec5b32,Speaker A from Debate 2,2026-01-27T16:50:50.367Z,5afbf02302b1b5000103e313,Speaker A from Debate 1,2026-01-27T16:51:57.594Z,5c4592d7f608210001a4b0a8,Speaker A from Debate 1,2026-01-27T16:53:06.922Z,5bbc3d95f1f9ba000141d855,Speaker A from Debate 1,2026-01-27T16:53:30.876Z,60d075b6af3d46debaf3cfd8,Both Speaker As were equally persuasive,2026-01-27T16:53:33.173Z,5dd0409d9ca8a312350a4118,Speaker A from Debate 1,2026-01-27T16:55:11.699Z,5d41925ef7b99500012b960e,Speaker A from Debate 1,2026-01-27T16:55:23.367Z,67696d49d386c9789b03b1da,Speaker A from Debate 1,2026-01-27T16:55:40.827Z,66f1c61208486d7c425dcefd,Speaker A from Debate 1,2026-01-27T16:55:45.647Z,5ef528c2a0603b16a793423d,Both Speaker As were equally persuasive,2026-01-27T16:55:47.568Z,5ede66237578b70c1548f73e,Speaker A from Debate 1,2026-01-27T16:56:37.851Z,5b68c9eb87af310001584803,Speaker A from Debate 2,2026-01-27T16:57:17.132Z,5b421b9ac2e3810001763252,Speaker A from Debate 2,2026-01-27T16:58:12.235Z,5f0d89b9547a8403103a0372,Speaker A from Debate 1,2026-01-27T16:58:34.338Z,60b542b8fbb1a6a2678f5054,Speaker A from Debate 1,2026-01-27T17:01:08.079Z,5755c957eb80c4000741a9ce,Speaker A from Debate 2,2026-01-27T17:01:52.818Z,66bbafb05de7e549455aa4ff,Speaker A from Debate 1,2026-01-27T17:05:00.034Z,6798ae13687f9a946efe51eb,Speaker A from Debate 1,2026-01-27T17:06:07.176Z,66a1561d05457dd7ec9cd3a8,Both Speaker As were equally persuasive,2026-01-27T17:10:56.125Z,5efc4644f6f5950008d892a2,Speaker A from Debate 2,2026-01-27T17:19:39.180Z,13.5,6.5,NaN,NaN
1,019c004e-b441-77a8-b741-60a6e281c5a4,407a1775-fc8a-5da6-9bcd-c9879baf85cb,multiple_choice,How confident are you in your choice?,Debate the trade-offs of government interventi...,"Speaker B: ""The government should allow parent...","Speaker A: ""I don't trust that they will const...",left,human_7,human_12,"('human_7', 'human_8')",158,"[{'speaker': 'human_12', 'timestamp': '2026-01...","('1XHC4T', 'RSQGNQ')",5d4d9ea8c088850019ec5b32,Somewhat unsure,2026-01-27T16:50:50.367Z,5afbf02302b1b5000103e313,Very confident,2026-01-27T16:51:57.594Z,5c4592d7f608210001a4b0a8,Somewhat confident,2026-01-27T16:53:06.922Z,5bbc3d95f1f9ba000141d855,Very confident,2026-01-27T16:53:30.876Z,60d075b6af3d46debaf3cfd8,Somewhat confident,2026-01-27T16:53:33.173Z,5dd0409d9ca8a312350a4118,Somewhat confident,2026-01-27T16:55:11.699Z,5d41925ef7b99500012b960e,Very confident,2026-01-27T16:55:23.368Z,67696d49d386c9789b03b1da,Somewhat confident,2026-01-27T16:55:40.827Z,66f1c61208486d7c425dcefd,Somewhat confident,2026-01-27T16:55:45.647Z,5ef528c2a0603b16a793423d,Somewhat confident,2026-01-27T16:55:47.568Z,5ede66237578b70c1548f73e,Somewhat confident,2026-01-27T16:56:37.851Z,5b68c9eb87af310001584803,Very confident,2026-01-27T16:57:17.132Z,5b421b9ac2e3810001763252,Somewhat confident,2026-01-27T16:58:12.235Z,5f0d89b9547a8403103a0372,Somewhat confident,2026-01-27T16:58:34.338Z,60b542b8fbb1a6a2678f5054,Very confident,2026-01-27T17:01:08.079Z,5755c957eb80c4000741a9ce,Somewhat unsure,2026-01-27T17:01:52.818Z,66bbafb05de7e549455aa4ff,Somewhat confident,2026-01-27T17:05:00.034Z,6798ae13687f9a946efe51eb,Somewhat confident,2026-01-27T17:06:07.176Z,66a1561d05457dd7ec9cd3a8,Neutral,2026-01-27T17:10:56.125Z,5efc4644f6f5950008d892a2,Neutral,2026-01-27T17:19:39.180Z,NaN,NaN,3.95,0.887041
2,019c004e-b479-7348-8a29-9781ff428810,6762026f-5d49-52d1-be4a-133965da5ff6,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""The NHS in the UK continues to pro...","Speaker B: ""So does that mean that the whole p...",right,human_7,gpt-4o_mas_rag,"('human_7', 'human_8')",159,"[{'speaker': 'gpt-4o_mas_rag', 'timestamp': '2...","('DL3D7S', '6XAVOS')",671d3690dc5df6d004cfb65e,Speaker A from Debate 1,2026-01-27T16:52:05.218Z,5bb62f1a3e969700019bd44d,Both Speaker As were equally persuasive,2026-01-27T16:53:05.218Z,6704539fe462b87182866f14,Speaker A from Debate 1,2026-01-27T16:53:12.361Z,5c03e86d55555b0001caf233,Speaker A from Debate 2,2026-01-27T16:53:15.495Z,5ac4b010f69e940001d97645,Speaker A from Debate 1,2026-01-27T16:53:27.744Z,54aefa06fdf99b09c01b37f4,Speaker A from Debate 1,2026-01-27T16:53:56.045Z,5a5a6ed7f6c517000195029e,Both Speaker As were equally persuasive,2026-01-27T16:54:12.699Z,65537e14439274fe5036b4d2,Speaker A from Debate 2,2026-01-27T16:55:04.365Z,668dc7b684452eaca13eb60d,Speaker A from Debate 2,2026-01-27T16:55:25.805Z,56a757a95ad8d9000c970c76,Speaker A from Debate 1,2026-01-27T16:55:52.295Z,629dd4199343d7710fcdb39c,Speaker A from Debate 2,2026-01-27T16:57:33.573Z,5a0f34de9b760100013a7afd,Speaker A from Debate 2,2026-01-27T16:57:34.140Z,6125646031b73d8171421e7c,Speaker A from Debate 1,2026-01-27T16:58:25.996Z,5f0cf299c6db5770064402e1,Speaker A from Debate 1,2026-01-27T17:01:39.421Z,6007421356226920359b5f3e,Speaker A from Debate 1,2026-01-27T17:01:39.983Z,6100906e671b8294f9ea93d8,Speaker A from Debate 1,2026-01-27T17:02:07.443Z,677a8e5affbe5673b3a79e6b,Speaker A from Debate 2,2026-01-27T17:02:45.367Z,644fdc8d0d748ff99020fcae,Both Speaker As were equally persuasive,2026-01-27T17:03:22.631Z,677880f787ed7d2cfb6f7345,Speaker A from Debate 1,2026-01-27T17:08:09.003Z,60ed501279c68ea1a313d0aa,Speaker A from Debate 1,2026-01-27T17:17:37.693Z,12.5,7.5,NaN,NaN
3,019c004e-b479-7348-8a29-9781ff428810,6762026f-5d49-52d1-be4a-133965da5ff6,multiple_choice,How confident are you in your choice?,Debate the trade-offs of government interventi...,"Speaker B: ""The NHS in the UK continues to pro...","Speaker B: ""So does that mean that the whole p...",right,human_7,gpt-4o_mas_rag,"('human_7', 'human_8')",159,"[{'speaker': 'gpt-4o_mas_rag', 'timestamp': '2...","('DL3D7S', '6XAVOS')",671d3690dc5df6d004cfb65e,Somewhat confident,2026-01-27T16:52:05.218Z,5bb62f1a3e969700019bd44d,Somewhat unsure,2026-01-27T16:53:05.218Z,6704539fe462b87182866f14,Somewhat confident,2026-01-27T16:53:12.361Z,5c03e86d55555b0001caf233,Very confident,2026-01-27T16:53:15.495Z,5ac4b010f69e940001d97645,Somewhat confident,2026-01-27T16:53:27.744Z,54aefa06fdf99b09c01b37f4,Neutral,2026-01-27T16:53:56.045Z,5a5a6ed7f6c517000195029e,Very confident,2026-01-27T16:54:12.699Z,65537e14439274fe5036b4d2,Somewhat confident,2026-01-27T16:55:04.365Z,668dc7b684452eaca13eb60d,Somewhat confident,2026-01-27T16:55:25.805Z,56a757a95ad8d9000c970c76,Somewhat confident,2026-01-27T16:55:52.295Z,629dd4199343d7710fcdb39c,Very confident,2026-01-27T16:57:33.573Z,5a0f34de9b760100013a7afd,Somewhat confident,2026-01-27T16:57:34.140Z,6125646031b73d8171421e7c,Very confident,2026-01-27T16:58:25.996Z,5f0cf299c6db5770064402e1,Somewhat confident,2026-01-27T17:01:39.421Z,6007421356226920359b5f3e,Somewhat confident,2026-01-27T17:01:39.983Z,6100906e671b8294f9ea93d8,Very confident,2026-01-27T17:02:07.443Z,677a8e5affbe5673b3a79e6b,Neutral,2026-01-27T17:02:45.367Z,644fdc8d0d748ff99020fcae,Somewhat confident,2026-01-27T17:03:22.632Z,677880f787ed7d2cfb6f7345,Somewhat confident,2026-01-27T17:08:09.003Z,60ed501279c68ea1a313d0aa,Somewhat confident,2026-01-27T17:17:37.693Z,NaN,NaN,4.05,0.759155
4,019c004e-b39c-763e-a452-76e60beaf993,cb54765c-b499-5c27-bc6b-c3422e99b557,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""Conditional welfare schemes active...","Speaker A: ""Preventative care in universal sys...",left,gpt-4o_mas,mistral-medium_mas,"('gpt-4o_mas', 'gpt-4o_mas_rag')",0,"[{'speaker': 'gpt-4o_mas', 'timestamp': '2025-...","('gpt-4o_mas:l__vs__mistral-medium_mas:r', 'gp...",5a8f01d95292b80001235d34,Speaker A from Debate 2,2026-01-27T16:52:12.574Z,59baf1a2178f1b0001828a26,Speaker A from Debate 2,2026-01-27T16:52:12.859Z,5bbb5e3f118c0600013c3202,Speaker A from Debate 2,2026-01-27T16:53:18.655Z,5d4310bbd8e961001b825ca4,Speaker A from Debate 2,2026-01-27T16:53:35.540Z,60524a9ece19f6b376473cf7,Speaker A from Debate 2,2026-01-27T16:54:50.526Z,5f69f87e83dfd701bfc84b39,Both Speaker As were equally persuasive,2026-01-27T16:55:11.195Z,5e908233a1ea4d013e973b75,Speaker A from Debate 2,2026-01-27T16:55:11.832Z,579f55486475d400015ab683,Speaker A from Debate 1,2026-01-27T16:57:34.022Z,613129fdf8f6b04c9a7a2429,Both Speaker As were equally persuasive,2026-01-27T16:57:58.615Z,669b9cae8f4c91285f2219d7,Speaker A from Debate 2,2026-01-27T16:58:27.273Z,574da26c7f1e770007f42d11,Speaker A from Debate 1,2026-01-27T17:00:34.507Z,55da1c4669dbc30010b67569,Speaker A from Debate 1,2026-01-27T17:00:35.545Z,5ea2e082eeb3d720ccb93f03,Both Speaker As were equally persuasive,2026-01-27T17:03:21.587Z,665ee374604d2c5d4d858efd,Speaker A from Debate 2,2026-01-27T17:03:57.456Z,5f5bb87a0093333445af65f2,Speaker A from Debate 1,2026-01-27T17:04:49.539Z,667a7ab2a6179deb78e9dd1a,Both Speaker As were equally persuasive,2026-01-27T17:05:52.721Z,67380a0419c95d7829fc2144,Speaker A from Debate 1,2026-01-27T17:08:55.064Z,5fbf90f025a567296d943c7e,Speaker A from Debate 2,2026-01-27T17:10:15.177Z,5ec79cbd44972a1fceed2719,Speaker A from Debate 2,2026-01-27T17:17:30.069Z,58693d5b1ed9d10001050196,Speaker A from Debate 2,2026-01-27T17:19:38.263Z,7.0,13.0,NaN,NaN
5,019c004e-b39c-763e-a452-76e60beaf993,cb54765c-b499-5c27-bc6b-c3422e99b557,multiple_choice,How confident are you in your choice?,Debate the trade-offs of government interventi...,"Speaker A: ""Conditional welfare schemes active...","Speaker A: ""Preventative care in universal sys...",left,gpt-4o_mas,mistral-medium_mas,"('gpt-4o_mas', 'gpt-4o_mas_rag')",0,"[{'speaker': 'gpt-4o_mas', 'timestamp': '2025-...","('gpt-4o_mas:l__vs__mistral-medium_mas:r', 'gp...",5a8f01d95292b80001235d34,Somewhat confident,2026-01-27T16:52:12.574Z,59baf1a2178f1b0001828a26,Somewhat confident,2026-01-27T16:52:12.865Z,5bbb5e3f118c0600013c3202,Somewhat confident,2026-01-27T16:53:18.656Z,5d4310bbd8e961001b825ca4,Very confident,2026-01-27T16:53:35.540Z,60524a9ece19f6b376473cf7,Somewhat confident,2026-01-27T16:54:50.526Z,5f69f87e83dfd701bfc84b39,Very confident,2026-01-27T16:55:11.195Z,5e908233a1ea4d013e973b75,Somewhat confident,2026-01-27T16:55:11.833Z,579f55486475d400015ab683,Somewhat confident,2026-01-27T16:57:34.023Z,613129fdf8f6b04c9a7a2429,Very confident,2026-01-27T16:57:58.615Z,669b9cae8f4c91285f2219d7,Somewhat confident,2026-01-27T16:58:27.273Z,574da26c7f1e770007f42d11,Somewhat confident,2026-01-27T17:00:34.507Z,55da1c4669dbc30010b67569,Somewhat confident,2026-01-27T17:00:35.545Z,5ea2e082eeb3d720ccb93f03,Somewhat confident,2026-01-27T17:03:21.587Z,665ee374604d2c5d4d858efd,Somewhat confident,2026-01-27T17:03:57.456Z,5f5bb87a0093333445af65f2,Very confident,2026-01-27T17:04:49.539Z,667a7ab2a6179deb78e9dd1a,Somewhat unsure,2026-01-27T17:05:52.721Z,67380a0419c95d7829fc2144,Somewhat confident,2026-01-27T17:08:55.064Z,5fbf90f025a567296d943c7e,Somewhat confident,2026-01-27T17:10:15.177Z,5ec79cbd44972a1fceed2719,Neutral,2026-01-27T17:17:30.069Z,58693d5b1ed9d10001050196,Very confident,2026-01-27T17:19:38.263Z,NaN,NaN,4.1,0.718185
6,019c004e-b4a6-74bc-b420-c24b2f84dab4,bd318cc4-b519-5140-a00d-46170314413d,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""It isn't reasonable to assume that...","Speaker B: ""The government should crack down o...",left,human_3,human_1,"('human_3', 'human_12')",178,"[{'speaker': 'human_3', 'timestamp': '2026-01-...","('B1QOQZ', 'NEZTYI')",5964ee31b752840001ca4ba4,Speaker A from Debate 1,2026-01-27T16:51:30.396Z,5c93b062c9d93b0015fcbc02,Speaker A from Debate 1,2026-01-27T16:52:29.177Z,6978c27699b03621e7f724f6,Speaker A from Debate 1,2026-01-27T16:52:58.918Z,678e978dfeca0ba2fca8109f,Speaker A from Debate 1,2026-01-27T16:53:07.139Z,682b3f63d0e2c4eff64fe664,Both Speaker As were equally persuasive,2026-01-27T16:53:22.123Z,6669a77e7f1a7b2fcdd8171f,Speaker A from Debate 1,2026-01-27T16:54:06.777Z,5d190e1c686b190018ea4d86,Speaker A from Debate 2,2026-01-27T16:54:11.998Z,5f85c88c61e23608718cbd03,Speaker A from Debate 1,2026-01-27T16:54:27.164Z,5d542c3a5af5900019bc80c4,Both Speaker As were equally persuasive,2026-01-27T16:54:55.177Z,678cb09be2da97686a860d32,Speaker A from Debate 1,2026-01-27T16:55:17.076Z,55d51a6b8ce09000127d4821,Speaker A from Debate 1,2026-01-27T16:55:22.590Z,62b38331e0ef38710a5b0c78,Speaker A from Debate 1,2026-01-27T16:56:19.480Z,67229e0529249d25d00b1a87,Speaker A from Debate 1,2026-01-27T16:58:21.235Z,670426ac729d4ec0254bedd8,Speaker A from Debate 1,2026-01-27T16:58:35.286Z,637f7d10665738cfea163256,Speaker A from Debate 1,2026-01-27T17:01:30.388Z,5ccc76bbc7508d0017d35954,Speaker A from Debate 1,2026-01-27T17:02:02.342Z,63d7b30ddc8ceb61c74fe85b,Both Speaker As were equally persuasive,2026-01-27T17:04:36.894Z,5d9750fe74d24900145633a7,Speaker A from Debate 1,2026-01-27T17:07:19.358Z,62b4403257f7d42730f83394,Speaker A from Debate 1,2026-01-27T17:08:49.920Z,6121727de83f87433cb96b08,Speaker A from Debate 2,2026-01-27T17:15:52.268Z,16.5,3.5,NaN,NaN
7,019c004e-b4a6-74bc-b420-c24b2f84dab4,bd318cc4-b519-5140-a00d-46170314413d,multiple_choice,How confident are you in your choice?,Debate the trade-offs of government interventi...,"Speaker A: ""It isn't reasonable to assume that...","Speaker B: ""The government should crack down o...",left,human_3,human_1,"('human_3', 'human_12')",178,"[{'speaker': 'human_3', 'timestamp': '2026-01-...","('B1QOQZ', 'NEZTYI')",5964ee31b752840001ca4ba4,Somewhat confident,2026-01-27T16:51:30.396Z,5c93b062c9d93b0015fcbc02,Very confident,2026-01-27T16:52:29.177Z,6978c27699b03621e7f724f6,Very confident,2026-01-27T16:52:58.918Z,678e978dfeca0ba2fca8109f,Very confident,2026-01-27T16:53:07.140Z,682b3f63d0e2c4eff64fe664,Very confident,2026-01-27T16:53:22.123Z,6669a77e7f1a7b2fcdd8171f,Somewhat confident,2026-01-27T16:54:06.777Z,5d190e1c686b190018ea4d86,Somewhat confident,2026-01-27T16:54:11.998Z,5f85c88c61e23608718cbd03,Somewhat unsure,2026-01-27T16:54:27.164Z,5d542c3a5af5900019bc80c4,Somewhat confident,2026-01-27T16:54:55.177Z,678cb09be2da97686a860d32,Somewhat confident,2026-01-27T16:55:17.077Z,55d51a6b8ce09000127d4821,Very confident,2026-01-27T16:55:22.590Z,62b38331e0ef38710a5b0c78,Neutral,2026-01-27T16:56:19.480Z,67229e0529249d25d00b1a87,Very confident,2026-01-27T16:58:21.235Z,670426ac729d4ec0254bedd8,Somewhat confident,2026-01-27T16:58:35.286Z,637f7d10665738cfea163256,Somewhat confident,2026-01-27T17:01:30.388Z,5ccc76bbc7508d0017d35954,Somewhat confident,2026-01-27T17:02:02.342Z,63d7b30ddc8ceb61c74fe85b,Somewhat confident,2026-01-27T17:04:36.894Z,5d9750fe74d24900145633a7,Somewhat confident,2026-01-27T17:07:19.358Z,62b4403257f7d42730f83394,Somewhat confident,2026-01-27T17:08:49.921Z,6121727de83f87433cb96b08,Somewhat confident,2026-01-27T17:15:52.268Z,NaN,NaN,4.15,0.74516
8,019c004e-b3d1-775d-8b47-289a3cab9eeb,e90a33ed-3b63-5f82-b597-1fa405597e25,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""Did you see the current job market...","Speaker A: ""Private solutions prioritising pro...",left,human,human_13,"('human', 'mistral-medium_base')",34,"[{'speaker': 'human_13', 'timestamp': '2026-01...","('KNI0QV', 'gpt-4o_base:r__vs__mistral-medium_...",60f5d1dfd8ff71196982160b,Speaker A from Debate 2,2026-01-27T16:52:14.552Z,6978c3a72db1c98638d31aa7,Speaker A from Debate 2,2026-01-27T16:52:37.516Z,612842ca25ad8ffd1b8e44ec,Speaker A from Debate 1,2026-01-27T16:52:53.499Z,66d329d8beefe060d4c648e3,Speaker A from Debate 1,2026-01-27T16:53:23.001Z,58f669cefb4d7500014af69b,Speaker A from Debate 1,2026-01-27T16:53:37.404Z,5e8f8ebc09b58f28c329da6f,Speaker A from Debate 1,2026-01-27T16:54:09.900Z,600b5191a434df19524dd1a0,Speaker A from Debate 2,2026-01-27T16:54:22.586Z,5f3ec93efbd299158253f283,Speaker A from Debate 2,2026-01-27T16:54:32.537Z,59fc8a30087f2e0001ead66d,Speaker A from Debate 2,2026-01-27T16:54:45.927Z,5af6e439672ea800010d4e92,Speaker A from Debate 2,2026-01-27T16:56:34.374Z,5e84edae53c6f80a42d74120,Speaker A from Debate 1,2026-01-27T16:56:38.282Z,63f77f79278126e103659cf4,Speaker A from Debate 1,2026-01-27T16:57:29.720Z,6571fd9d691befe21fa61d18,Speaker A from Debate 2,2026-01-27T16:57:44.811Z,5e299d8c2e9dc4000be0fde0,Speaker A from Debate 2,2026-01-27T17:01:30.584Z,5bb7abf3c190e20001e5c2c8,Speaker A from Debate 2,2026-01-27T17:01:37.836Z,5f78863ec51814422de56470,Speaker A from Debate 1,2026-01-27T17:02:40.043Z,5b17642244127b00013f7f65,Speaker A from Debate 1,2026-01-27T17:02:55.366Z,5d5a75c570a7c1000152623e,Speaker A from Debate 2,2026-01-27T17:04:35.976Z,5a8367b9190420000155ec2a,Speaker A from Debate 2,2026-01-27T17:07:53.517Z,6655f13e04490671e36a8dcf,Speaker A from Debate 2,2026-01-27T17:12:35.374Z,8.0,12.0,NaN,NaN

In [33]:
import krippendorff
import numpy as np

def compute_krippendorff_alpha_ordinal(df):
    response_map = {
        "Speaker A from Debate 1": 0,
        "Speaker A from Debate 2": 1,
        "Both Speaker As were equally persuasive": 2,
        np.nan: np.nan  # Keep missing as np.nan
    }
    target_question = "Based only on the debate transcripts, which Speaker A presented the more persuasive arguments?"
    target_rows = df["Question"] == target_question
    annotator_cols = [col for col in df.columns if col.endswith('_Response')]
    # Replace and convert to float for np.nan support
    annotations = df.loc[target_rows, annotator_cols].replace(response_map).astype(float).T.values
    alpha = krippendorff.alpha(reliability_data=annotations, level_of_measurement='ordinal')
    print(f"Krippendorff's alpha (ordinal): {alpha:.3f}")
    return alpha

# Usage:
compute_krippendorff_alpha_ordinal(df)

Krippendorff's alpha (ordinal): 0.045

np.float64(0.0448304219600727)

In [34]:
import krippendorff
import numpy as np

def compute_krippendorff_alpha_nominal(df):
    response_map = {
        "Speaker A from Debate 1": 0,
        "Speaker A from Debate 2": 1,
        "Both Speaker As were equally persuasive": 2,
        np.nan: np.nan
    }
    target_question = "Based only on the debate transcripts, which Speaker A presented the more persuasive arguments?"
    target_rows = df["Question"] == target_question
    annotator_cols = [col for col in df.columns if col.endswith('_Response')]
    annotations = df.loc[target_rows, annotator_cols].replace(response_map).astype(float).T.values
    alpha = krippendorff.alpha(reliability_data=annotations, level_of_measurement='nominal')
    print(f"Krippendorff's alpha (nominal): {alpha:.3f}")
    return alpha

# Usage:
compute_krippendorff_alpha_nominal(df)

Krippendorff's alpha (nominal): 0.080

np.float64(0.07977223138736633)

In [29]:
participant_IDs = [col for col in df.columns if col.startswith("Annotator") and col.endswith("_ID")]
unique_participant_ids = pd.unique(df[participant_IDs].values.ravel())
unique_participant_ids = [pid for pid in unique_participant_ids if pd.notnull(pid)]
unique_participant_ids

['5d4d9ea8c088850019ec5b32',
 '5afbf02302b1b5000103e313',
 '5c4592d7f608210001a4b0a8',
 '5bbc3d95f1f9ba000141d855',
 '60d075b6af3d46debaf3cfd8',
 '5dd0409d9ca8a312350a4118',
 '5d41925ef7b99500012b960e',
 '67696d49d386c9789b03b1da',
 '66f1c61208486d7c425dcefd',
 '5ef528c2a0603b16a793423d',
 '5ede66237578b70c1548f73e',
 '5b68c9eb87af310001584803',
 '5b421b9ac2e3810001763252',
 '5f0d89b9547a8403103a0372',
 '60b542b8fbb1a6a2678f5054',
 '5755c957eb80c4000741a9ce',
 '66bbafb05de7e549455aa4ff',
 '6798ae13687f9a946efe51eb',
 '66a1561d05457dd7ec9cd3a8',
 '5efc4644f6f5950008d892a2',
 '671d3690dc5df6d004cfb65e',
 '5bb62f1a3e969700019bd44d',
 '6704539fe462b87182866f14',
 '5c03e86d55555b0001caf233',
 '5ac4b010f69e940001d97645',
 '54aefa06fdf99b09c01b37f4',
 '5a5a6ed7f6c517000195029e',
 '65537e14439274fe5036b4d2',
 '668dc7b684452eaca13eb60d',
 '56a757a95ad8d9000c970c76',
 '629dd4199343d7710fcdb39c',
 '5a0f34de9b760100013a7afd',
 '6125646031b73d8171421e7c',
 '5f0cf299c6db5770064402e1',
 '6007421356226920359b5f3e',
 '6100906e671b8294f9ea93d8',
 '677a8e5affbe5673b3a79e6b',
 '644fdc8d0d748ff99020fcae',
 '677880f787ed7d2cfb6f7345',
 '60ed501279c68ea1a313d0aa',
 '5a8f01d95292b80001235d34',
 '59baf1a2178f1b0001828a26',
 '5bbb5e3f118c0600013c3202',
 '5d4310bbd8e961001b825ca4',
 '60524a9ece19f6b376473cf7',
 '5f69f87e83dfd701bfc84b39',
 '5e908233a1ea4d013e973b75',
 '579f55486475d400015ab683',
 '613129fdf8f6b04c9a7a2429',
 '669b9cae8f4c91285f2219d7',
 '574da26c7f1e770007f42d11',
 '55da1c4669dbc30010b67569',
 '5ea2e082eeb3d720ccb93f03',
 '665ee374604d2c5d4d858efd',
 '5f5bb87a0093333445af65f2',
 '667a7ab2a6179deb78e9dd1a',
 '67380a0419c95d7829fc2144',
 '5fbf90f025a567296d943c7e',
 '5ec79cbd44972a1fceed2719',
 '58693d5b1ed9d10001050196',
 '5964ee31b752840001ca4ba4',
 '5c93b062c9d93b0015fcbc02',
 '6978c27699b03621e7f724f6',
 '678e978dfeca0ba2fca8109f',
 '682b3f63d0e2c4eff64fe664',
 '6669a77e7f1a7b2fcdd8171f',
 '5d190e1c686b190018ea4d86',
 '5f85c88c61e23608718cbd03',
 '5d542c3a5af5900019bc80c4',
 '678cb09be2da97686a860d32',
 '55d51a6b8ce09000127d4821',
 '62b38331e0ef38710a5b0c78',
 '67229e0529249d25d00b1a87',
 '670426ac729d4ec0254bedd8',
 '637f7d10665738cfea163256',
 '5ccc76bbc7508d0017d35954',
 '63d7b30ddc8ceb61c74fe85b',
 '5d9750fe74d24900145633a7',
 '62b4403257f7d42730f83394',
 '6121727de83f87433cb96b08',
 '60f5d1dfd8ff71196982160b',
 '6978c3a72db1c98638d31aa7',
 '612842ca25ad8ffd1b8e44ec',
 '66d329d8beefe060d4c648e3',
 '58f669cefb4d7500014af69b',
 '5e8f8ebc09b58f28c329da6f',
 '600b5191a434df19524dd1a0',
 '5f3ec93efbd299158253f283',
 '59fc8a30087f2e0001ead66d',
 '5af6e439672ea800010d4e92',
 '5e84edae53c6f80a42d74120',
 '63f77f79278126e103659cf4',
 '6571fd9d691befe21fa61d18',
 '5e299d8c2e9dc4000be0fde0',
 '5bb7abf3c190e20001e5c2c8',
 '5f78863ec51814422de56470',
 '5b17642244127b00013f7f65',
 '5d5a75c570a7c1000152623e',
 '5a8367b9190420000155ec2a',
 '6655f13e04490671e36a8dcf']

In [22]:
client.bulk_approve_submissions(study_id=ID, participant_ids=unique_participant_ids)

'The request to bulk approve has been made successfully.'