In [1]:
import yaml
import json
import pickle
import pandas as pd
import numpy as np
import itertools
import matplotlib.pyplot as plt
import seaborn as sns
import httpx
import os
import ast
import krippendorff

import warnings
warnings.filterwarnings("ignore")

from prolific import ProlificAPIError, ProlificClient

pd.set_option('display.max_columns', None)

# config = yaml.safe_load(open("config.yaml", "r"))

client = ProlificClient(
    api_token=os.environ["prolific_key"])

In [2]:
ID = "698efef38f6dc0baf73e7f6f"

In [3]:
client.get_study(ID)

{'id': '698efef38f6dc0baf73e7f6f',
 'name': 'Evaluating the Persuasiveness of Debaters',
 'description': '<p>In this study, you will evaluate <strong>persuasiveness in debate transcripts</strong>. You will read transcripts from <strong>two separate debates</strong> on the same topic and judge which speaker is more persuasive.</p><p>Each debate features two participants, Speaker A and Speaker B. Although the debates involve different individuals, <strong>Speaker A represents the same ideological or political position in both debates</strong>.</p><p>Your task is to compare the persuasiveness of <strong>Speaker A across the two debates</strong>, focusing only on how effectively they argue their position.</p><p>There are <strong>no right or wrong answers</strong>! We are interested in your honest, subjective judgment based on the debate content.</p><p></p>',
 'total_available_places': 3234,
 'reward': 120,
 'average_reward_per_hour': 1155.0,
 'external_study_url': 'https://tars.dcp.prod.aws.prolific.co/access-details/86e0d8b3-e084-489b-b3a9-a6d9a14128bf/allocate',
 'video_platform': None,
 'video_id': None,
 'device_compatibility': ['desktop', 'mobile', 'tablet'],
 'peripheral_requirements': [],
 'researcher': {'id': '693837451402cb5f5765430f',
  'name': 'Jordan Robinson',
  'email': 'j.robinson@turing.ac.uk',
  'country': 'GB',
  'institution': {'name': 'turing.ac.uk',
   'logo': 'https://internal-api.prolific.com/assets/img/institutions/turing.ac.uk.png',
   'link': 'http://www.turing.ac.uk'}},
 'publisher': {'id': '693837451402cb5f5765430f',
  'name': 'Jordan Robinson',
  'email': 'j.robinson@turing.ac.uk',
  'country': 'GB',
  'institution': {'name': 'turing.ac.uk',
   'logo': 'https://internal-api.prolific.com/assets/img/institutions/turing.ac.uk.png',
   'link': 'http://www.turing.ac.uk'}},
 'places_taken': 3234,
 'study_type': 'SINGLE',
 'submissions_config': {'max_submissions_per_participant': 1,
  'max_concurrent_submissions': -1,
  'auto_rejection_categories': ['EXCEPTIONALLY_FAST']},
 'status': 'AWAITING REVIEW',
 'internal_name': 'final_full_3_annotations_per_human_with_2_atten_checks',
 'minimum_reward_per_hour': 600.0,
 'date_created': '2026-02-13T10:37:30.850000Z',
 'published_at': '2026-02-13T10:38:17.050000Z',
 'number_of_submissions': 3536,
 'estimated_completion_time': 8,
 'average_time_taken': 6,
 'average_time_taken_seconds': 374,
 'completion_code': None,
 'failed_attention_code': None,
 'alternative_completion_codes': [],
 'completion_code_action': None,
 'last_email_update_sent_datetime': None,
 'maximum_allowed_time': 39,
 'receipt': None,
 'eligible_participant_count': 6728,
 'total_participant_pool': 221637,
 'currency_code': 'GBP',
 'total_cost': 543312,
 'fees_per_submission': 0.0,
 'fees_percentage': 0.333333,
 'service_margin_percentage': '0.25000000000000000',
 'vat_percentage': 0.2,
 'discount_from_coupons': 0,
 'estimated_reward_per_hour': 900.0,
 'representative_sample': None,
 'publish_at': None,
 'prolific_id_option': None,
 'is_underpaying': None,
 'average_reward_per_hour_without_adjustment': 1155.0,
 'has_had_adjustment': False,
 'reward_level': {'below_prolific_min': None, 'below_original_estimate': None},
 'project': '6978d3c3aa58c1adeeb3f465',
 'workspace': '688784736462d228c69fdd63',
 'naivety_distribution_rate': -1,
 'is_reallocated': False,
 'external_app': None,
 'external_id': None,
 'privacy_notice': None,
 'can_be_reallocated': False,
 'reallocated_places': 0,
 'progress_percentage': 100,
 'completion_codes': [{'code': 'C815J9E9',
   'code_type': 'COMPLETED',
   'actions': [{'action': 'MANUALLY_REVIEW'}],
   'actor': 'participant'}],
 'metadata': None,
 'filter_set_id': None,
 'filter_set_version': None,
 'filters': [{'filter_id': 'current-country-of-residence',
   'selected_values': ['0']},
  {'filter_id': 'highest-education-level-completed',
   'selected_values': ['4', '5', '6']},
  {'filter_id': 'political-affiliation-uk',
   'selected_values': ['0', '1', '2']}],
 'has_credentials': False,
 'credential_pool_id': None,
 'access_details_collection_id': '86e0d8b3-e084-489b-b3a9-a6d9a14128bf',
 'access_details': [{'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/001fa3b4-68fe-5531-afc9-1aaf675477a3',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/005ae885-bd1e-51c8-8975-9a65f0b12637',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/00826f1b-a5b6-51a1-9306-dcf980416e70',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/00882ffe-0cf2-5fd6-b879-a1fafd988863',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0144426b-eb27-5790-8cad-87e8cd867bef',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/01caa0f1-05c6-5ee1-a8f2-54187eb271eb',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/01ddd2c0-00ba-542e-9986-2b5559bf8653',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/01f2b42a-ba00-5246-8290-bfb854e7a2d7',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/01f978f9-f310-5c2f-8ec2-726104ddd451',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/020f79c1-50f0-5dec-b178-82e816efa973',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/024a21d2-4ada-527f-bdf2-50de33d60183',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0317b707-e0b0-5b47-950c-9d4ef6c6257a',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0393a2a6-105a-5bfc-8dc8-03eddb36c0c8',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/03ccf60f-9d2b-5cfa-8cce-6db22eb96d53',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/03f6c707-10ec-5e7c-836d-ce7e5c514953',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/03fd2089-1ed5-5664-871b-7e870bc0f94b',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/05406f80-716c-5f32-9b3e-0a1240f036ec',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/06a4ce37-bc65-53f4-90cc-75cddbe52a39',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/06caab5a-a713-55ff-83b2-054e2aeb9e64',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/06d28d8b-c36b-52c1-8a6b-88bb810b44d0',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/07ad69c4-3fed-55b1-9586-1647d44ab3f2',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/07da7713-5895-5c72-8e9c-5ce980653c8b',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/082a3825-7238-55cd-b12f-0c0a5de492af',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/088e1a8d-02dd-5ae7-967d-c64d7fc61e9d',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/091ad7ce-5f5e-5d70-8274-54fa7a0a835d',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/091b4e41-0d8c-5c7d-87c7-a9b2c9976dcc',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/093ca67b-1f39-5bd8-a82f-7e0d0fe9b0f2',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0a1e9d80-47b0-5362-b477-096833407e5b',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0a338905-6658-54fd-96b4-18be79a20488',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0ae33930-091e-5a07-a34b-e1a07b5e9816',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0b730dcf-9168-50f2-a8ab-3489f31baadb',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0c0032eb-0be1-5291-8302-2bdf529441c5',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0d2fe138-c8d1-541a-a60a-f40824d1df54',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0f3c09b7-7ff1-5c37-ab4b-b04efcb0ef1d',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0f63aced-d2c5-5f4f-90bd-764159f21def',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0fa39bd4-b7f4-5743-a5d4-10ef22980cdb',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0fee8c0e-0763-5c7f-a810-a11d5f95d0dc',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/10ecdb91-d6a8-562e-8747-1a0ef13abb6b',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/11f1183c-9ce4-5d5a-b5a2-0b7fe0b58c91',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1233a0e6-ff40-5d3d-b841-a23b5df83ca1',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/12947010-3120-58a8-9fcf-bae8a718e292',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/129ab5f7-9abd-591b-ac44-4a65ead86627',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/132b843f-5d41-5a21-869b-a8f7dac017a9',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1345e30c-213a-5d86-9b50-3ab9c6ae60ab',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/137d1f6a-d508-5646-812a-42d74df03bfd',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1537631d-fd29-5aea-8ae5-e717930c75eb',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/15440d5d-b2b5-5589-ace3-15cf8e03b7d0',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1613e21a-88e5-5972-8c37-abb9adb466c2',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/163101c2-70be-5a6b-a5a5-c8c2483930b5',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/163ba230-63c2-5d9e-b770-97c40afd016e',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/174d30ab-e300-523c-897e-25ee72724c58',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/178b14f0-ed94-572b-a46c-d182c682a8cb',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/17903436-07c7-5ef6-aa24-9b897fc76518',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/18bb773f-2d69-583a-a32a-28b4f1dbc980',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1912a09e-ee41-55a1-9aa4-3bf6f93808c6',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1a2683c7-566e-56e0-bb0c-7fac25cd91af',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1a7e9332-106d-5c41-b5b4-b51b01f842ed',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1a7f9613-81bf-5899-b973-80a0fdf217e8',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1aefbd4b-dfe1-582e-a5bd-cc0581f4f4a7',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1b49c192-c0bd-5a00-917b-8603a19c5e84',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1b64a51c-7060-5db8-b9aa-0192992bcdf5',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1c32aa99-cfc3-5043-9788-c9ed6647e3a7',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1c7274a5-65c0-5a5e-b99c-1b65be34f817',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1c9cdf10-23f7-54db-8774-008421d4f0d9',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1ca838f8-5589-54a5-aad6-e1837911e301',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1dd7436b-2037-568d-9674-9d0b45747154',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1de9633f-2ad6-5c9b-b561-e9c0efd6c684',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1dfc82e4-05cc-5380-9a7c-f58386ac8388',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1eaef366-578f-5162-a9d7-cdc05c4d85f9',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1ecdd0a6-eb46-5a80-8cce-116d50e3ba26',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1f62c780-f4a4-5ac2-9c87-acc9de7d2ef2',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1f806385-3aec-5004-9b1d-9fb5fca7a538',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1f8a5bc9-7544-5cf2-b548-18a41616b495',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/20d889a6-a08b-55e5-9dee-56f38e96b1c9',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/22fed747-e728-5f61-8d58-681d876dcc38',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/23b58db6-af4b-5ded-94e9-baf691d9cfb4',
   'total_allocation': 7,
   'allocated': 7},

In [4]:
responses = client.list_submissions(study=ID, page_size=1000)
print(len(responses["results"]))
print(json.dumps(responses['results'][0], indent=2))

1000
{
  "id": "698f546d256d83fbae917ec5",
  "participant_id": "673b7a139cd7db8678fafdcd",
  "started_at": "2026-02-13T16:42:42.802000Z",
  "completed_at": "2026-02-13T16:43:55.622000Z",
  "is_complete": true,
  "time_taken": 72,
  "reward": 12000,
  "status": "AWAITING REVIEW",
  "strata": {},
  "study_code": "NOCODE",
  "bonus_payments": [],
  "ip": "194.233.158.124",
  "return_requested": null,
  "has_siblings": false,
  "time_taken_under_auto_approval_threshold": true,
  "dynamic_payment_percentage": null
}

In [5]:
rejected = client.list_submissions(study=ID, page_size=1000, rejected=True)
print(len(rejected["results"]))

5

In [6]:
df = pd.read_csv(
    "data/019c5684-e8e6-737c-9442-07692f856379.csv"
)

In [7]:
df.head()

,DataPoint_ID,Task_Group_ID,Task_Type,Question,Debate Topic,Debate 1,Debate 2,META_SAMPLE1_POLITICAL_POSITION,META_SAMPLE1_SPEAKERA,META_COMPARISONID_1,META_SAMPLE1_SPEAKERB,META_COMPARISON,META_TASK_GROUP_ID,META_COMPARISONID,META_ATTEN_CHECK_PERSUASIVENESS_ANSWER,META_ATTEN_CHECK_CONFIDENCE_ANSWER,META_SAMPLE1_DIALOGUE_CHUNK,META_PAIR_SESSION_IDS,META_SAMPLE2_POLITICAL_POSITION,Annotator1_ID,Annotator1_Response,Annotator1_Timestamp,Annotator2_ID,Annotator2_Response,Annotator2_Timestamp,Annotator3_ID,Annotator3_Response,Annotator3_Timestamp,Annotator4_ID,Annotator4_Response,Annotator4_Timestamp,Annotator5_ID,Annotator5_Response,Annotator5_Timestamp,Annotator6_ID,Annotator6_Response,Annotator6_Timestamp,Annotator7_ID,Annotator7_Response,Annotator7_Timestamp,Annotator8_ID,Annotator8_Response,Annotator8_Timestamp
0,019c5684-b730-70dd-b5f3-ca369d6a622c,412,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""How can this be done if the opport...","Speaker A: ""Would you concur that this point r...",left,human_9,1154,gpt-4o_base,"('human_9', 'human_11')",412,2064,NaN,NaN,"[{'speaker': 'human_9', 'timestamp': '2026-01-...","('XZV57F', 'OR2XBB')",left,6318acc6273e916b39a95a85,Speaker A from Debate 2,2026-02-13T10:46:55.851Z,579f55486475d400015ab683,Speaker A from Debate 1,2026-02-13T12:06:32.977Z,5e90781c06c6ee000974d087,Speaker A from Debate 1,2026-02-13T19:45:23.867Z,66066cf2a8876c1d1907732a,Speaker A from Debate 1,2026-02-14T20:40:58.661Z,5d07689bad18d40001bb73c1,Speaker A from Debate 1,2026-02-16T15:57:15.704Z,63d13c076dd249ca3a6bffbb,Speaker A from Debate 1,2026-02-18T22:06:51.931Z,5f0c94983314760efb2814c1,Speaker A from Debate 1,2026-02-21T11:14:56.612Z,NaN,NaN,NaN
1,019c5684-b730-70dd-b5f3-ca369d6a622c,412,multiple_choice,How confident are you in your choice?,Debate the trade-offs of government interventi...,"Speaker A: ""How can this be done if the opport...","Speaker A: ""Would you concur that this point r...",left,human_9,1154,gpt-4o_base,"('human_9', 'human_11')",412,2064,NaN,NaN,"[{'speaker': 'human_9', 'timestamp': '2026-01-...","('XZV57F', 'OR2XBB')",left,6318acc6273e916b39a95a85,Neutral,2026-02-13T10:46:55.851Z,579f55486475d400015ab683,Somewhat confident,2026-02-13T12:06:32.978Z,5e90781c06c6ee000974d087,Very confident,2026-02-13T19:45:23.867Z,66066cf2a8876c1d1907732a,Somewhat unsure,2026-02-14T20:40:58.661Z,5d07689bad18d40001bb73c1,Neutral,2026-02-16T15:57:15.704Z,63d13c076dd249ca3a6bffbb,Very confident,2026-02-18T22:06:51.932Z,5f0c94983314760efb2814c1,Somewhat confident,2026-02-21T11:14:56.612Z,NaN,NaN,NaN
2,019c5683-e116-71d8-8aba-b35b807dd373,173,multiple_choice,"Based only on the debate transcripts, which Sp...",(ATTENTION CHECK: ignore this datapoint and se...,(ATTENTION CHECK: ignore this datapoint and se...,(ATTENTION CHECK: ignore this datapoint and se...,left,human_11,1128,human_4,"('human_11', 'human_8')",173,867,Both Speaker As were equally persuasive,Neutral,"[{'speaker': 'human_11', 'timestamp': '2026-01...","('WTXVCV', 'RSQGNQ')",left,695c0670de1faedbce882831,Both Speaker As were equally persuasive,2026-02-13T10:51:45.569Z,5e8f8ebc09b58f28c329da6f,Both Speaker As were equally persuasive,2026-02-13T14:09:52.885Z,60e41e3e8c52dca4b19a3487,Both Speaker As were equally persuasive,2026-02-13T18:49:51.705Z,6978e5020a6d1cdb00d60fe4,Both Speaker As were equally persuasive,2026-02-14T18:01:04.033Z,64784c2bc85267b924936813,Both Speaker As were equally persuasive,2026-02-16T13:42:10.831Z,60fc3a1e0eb578aa02590e27,Both Speaker As were equally persuasive,2026-02-18T18:46:00.749Z,5f1e8aa76210d9000c23deb5,Both Speaker As were equally persuasive,2026-02-21T08:28:37.218Z,NaN,NaN,NaN
3,019c5683-e116-71d8-8aba-b35b807dd373,173,multiple_choice,How confident are you in your choice?,(ATTENTION CHECK: ignore this datapoint and se...,(ATTENTION CHECK: ignore this datapoint and se...,(ATTENTION CHECK: ignore this datapoint and se...,left,human_11,1128,human_4,"('human_11', 'human_8')",173,867,Both Speaker As were equally persuasive,Neutral,"[{'speaker': 'human_11', 'timestamp': '2026-01...","('WTXVCV', 'RSQGNQ')",left,695c0670de1faedbce882831,Neutral,2026-02-13T10:51:45.569Z,5e8f8ebc09b58f28c329da6f,Neutral,2026-02-13T14:09:52.885Z,60e41e3e8c52dca4b19a3487,Neutral,2026-02-13T18:49:51.705Z,6978e5020a6d1cdb00d60fe4,Neutral,2026-02-14T18:01:04.034Z,64784c2bc85267b924936813,Neutral,2026-02-16T13:42:10.831Z,60fc3a1e0eb578aa02590e27,Neutral,2026-02-18T18:46:00.749Z,5f1e8aa76210d9000c23deb5,Neutral,2026-02-21T08:28:37.218Z,NaN,NaN,NaN
4,019c5684-bc10-73fa-ae9c-bdda3c2e3812,417,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""Market forces ensure that the best...","Speaker A: ""Government intervention in public ...",left,gpt-4o_mas_rag,763,mistral-medium_mas,"('gpt-4o_mas_rag', 'human_6')",417,2089,NaN,NaN,"[{'speaker': 'mistral-medium_mas', 'timestamp'...","('gpt-4o_mas_rag:l__vs__mistral-medium_mas:r',...",left,5dd9a7ff98981d926df9ea18,Speaker A from Debate 1,2026-02-13T10:45:34.049Z,6761658b4037ac25f8afbd22,Speaker A from Debate 1,2026-02-13T11:48:57.224Z,5e2c8f69cad44b2bc5ce9a34,Speaker A from Debate 1,2026-02-13T14:38:04.633Z,67605337c41b9ba5ae52a0c8,Speaker A from Debate 1,2026-02-13T21:03:16.757Z,673f069497dc06b5ecbf7470,Speaker A from Debate 1,2026-02-15T11:47:01.602Z,6658ed9e2802dccba9041ca4,Speaker A from Debate 1,2026-02-17T10:05:08.725Z,677d4d04da6aea9117c478b5,Speaker A from Debate 1,2026-02-20T11:56:31.327Z,NaN,NaN,NaN

In [8]:
comparison_ids = df["META_COMPARISONID"].unique().tolist()

annotator_cols = []
for col in df.columns:
    if col.startswith("Annotator") and col.endswith('_ID'):
        base = col.replace("_ID", "")
        annotator_cols.append((
            col,                          # ID column
            base + "_Timestamp",          # Timestamp column
            base + "_Response"            # Response column
        ))
annotator_cols

[('Annotator1_ID', 'Annotator1_Timestamp', 'Annotator1_Response'),
 ('Annotator2_ID', 'Annotator2_Timestamp', 'Annotator2_Response'),
 ('Annotator3_ID', 'Annotator3_Timestamp', 'Annotator3_Response'),
 ('Annotator4_ID', 'Annotator4_Timestamp', 'Annotator4_Response'),
 ('Annotator5_ID', 'Annotator5_Timestamp', 'Annotator5_Response'),
 ('Annotator6_ID', 'Annotator6_Timestamp', 'Annotator6_Response'),
 ('Annotator7_ID', 'Annotator7_Timestamp', 'Annotator7_Response'),
 ('Annotator8_ID', 'Annotator8_Timestamp', 'Annotator8_Response')]

In [9]:
rejected_ids = [sub['participant_id'] for sub in rejected['results']]
rejected_ids

['5b70252c99982e000145ccf7',
 '5cd80c45dcabe80001040e88',
 '5d78d57c8f579d001518e74f',
 '5fcfa3168335430d143b4431',
 '67c3321da0a96b0538b4abbe']

In [10]:
attention_df = df[df["META_ATTEN_CHECK_PERSUASIVENESS_ANSWER"].notna() & df["META_ATTEN_CHECK_CONFIDENCE_ANSWER"].notna()]

In [11]:
ids_failed_atten_checks = {sub_id: {} for sub_id in attention_df["Annotator1_ID"].unique()}
for id in ids_failed_atten_checks:
    ids_failed_atten_checks[id]["persuassiveness_question"] = 0
    ids_failed_atten_checks[id]["confidence_question"] = 0

In [12]:
all_annotator_ids = set()
for col_id, col_ts, col_resp in annotator_cols:
    all_annotator_ids.update(attention_df[col_id].dropna().unique())

ids_failed_atten_checks = {sub_id: {} for sub_id in all_annotator_ids}

In [13]:
all_annotator_ids = set()
for col_id, col_ts, col_resp in annotator_cols:
    all_annotator_ids.update(attention_df[col_id].dropna().unique())

ids_failed_atten_checks = {sub_id: {} for sub_id in all_annotator_ids}

for id in ids_failed_atten_checks:
    ids_failed_atten_checks[id]["persuassiveness_question"] = 0
    ids_failed_atten_checks[id]["confidence_question"] = 0

for idx, row in attention_df.iterrows():
    for col_id, col_ts, col_resp in annotator_cols:
        if row[col_id] in rejected_ids or pd.isna(row[col_id]):
            continue

        response = row[col_resp]

        atten_count = 0
        if row["Question"] == "Based only on the debate transcripts, which Speaker A presented the more persuasive arguments?":
            target = row["META_ATTEN_CHECK_PERSUASIVENESS_ANSWER"]

            if target != response:
                ids_failed_atten_checks[df.at[idx, col_id]]["persuassiveness_question"] += 1

        else:
            # Question == 'How confident are you in your choice?'

            target = row["META_ATTEN_CHECK_CONFIDENCE_ANSWER"]

        
            if target != response:
                ids_failed_atten_checks[df.at[idx,col_id]]["confidence_question"] += 1

print(ids_failed_atten_checks)
len(ids_failed_atten_checks)

{'68136160929cc479375d3c20': {'persuassiveness_question': 0, 'confidence_question': 0}, '6979cf9aa50cf9eff6c75149': {'persuassiveness_question': 0, 'confidence_question': 0}, '566d950e57f93300112d0a7b': {'persuassiveness_question': 0, 'confidence_question': 0}, '677ac6f15c4ac72aaffcab23': {'persuassiveness_question': 0, 'confidence_question': 0}, '66d20f7f74d51c4de3cf0cce': {'persuassiveness_question': 0, 'confidence_question': 0}, '6743316520c610ff047fd40a': {'persuassiveness_question': 0, 'confidence_question': 0}, '5fad3af0a272a23e5aef2aa6': {'persuassiveness_question': 0, 'confidence_question': 0}, '654cc4367585dc78f77e81cb': {'persuassiveness_question': 0, 'confidence_question': 0}, '5e3afe879d5f1e30b75b9ca6': {'persuassiveness_question': 0, 'confidence_question': 0}, '5964e073241f8d0001065056': {'persuassiveness_question': 0, 'confidence_question': 0}, '5be742dd0e366e000175c8ba': {'persuassiveness_question': 0, 'confidence_question': 0}, '664a0d8b5ef52adae600c9fa': {'persuassiveness_question': 0, 'confidence_question': 0}, '57f9238bc786ac00011ebc72': {'persuassiveness_question': 0, 'confidence_question': 0}, '65a009f9618baa6910036765': {'persuassiveness_question': 0, 'confidence_question': 0}, '5e909d6c5321c13abee11725': {'persuassiveness_question': 2, 'confidence_question': 1}, '644150df4e40aadeab246610': {'persuassiveness_question': 0, 'confidence_question': 0}, '660ea867775a9760274fc42e': {'persuassiveness_question': 0, 'confidence_question': 0}, '677335def66e34c1da7101fe': {'persuassiveness_question': 0, 'confidence_question': 0}, '5ca8b2b8614b7b0016be5501': {'persuassiveness_question': 0, 'confidence_question': 0}, '5b1ac052ea64a000017c389e': {'persuassiveness_question': 0, 'confidence_question': 0}, '699442dc54f8b9db5a555afd': {'persuassiveness_question': 0, 'confidence_question': 2}, '61167663afe155e75f71d23d': {'persuassiveness_question': 0, 'confidence_question': 0}, '599a9252bbe848000179676e': {'persuassiveness_question': 0, 'confidence_question': 0}, '6773edcbb205d22a2e097948': {'persuassiveness_question': 0, 'confidence_question': 0}, '5fbfffc4e214a60ab1b745fd': {'persuassiveness_question': 0, 'confidence_question': 0}, '5ea9501501562703c7ef80b4': {'persuassiveness_question': 0, 'confidence_question': 0}, '5d667425bf872a001a72eb79': {'persuassiveness_question': 0, 'confidence_question': 0}, '6124d3c85b6ea8a350177dcc': {'persuassiveness_question': 0, 'confidence_question': 1}, '5d59b9959d203c0001fac7d7': {'persuassiveness_question': 0, 'confidence_question': 0}, '6398cbd807a6ad15411601a3': {'persuassiveness_question': 0, 'confidence_question': 1}, '5e1878b9a3d56c151399af37': {'persuassiveness_question': 0, 'confidence_question': 0}, '56ffd10b18705800099d0416': {'persuassiveness_question': 0, 'confidence_question': 0}, '5e8f5d82af20fc0890922b5d': {'persuassiveness_question': 0, 'confidence_question': 0}, '66f46a8682979653eadb837f': {'persuassiveness_question': 0, 'confidence_question': 1}, '571fdcb14b8ecc0013c24fcb': {'persuassiveness_question': 0, 'confidence_question': 0}, '60b3d51e5faeb57cea9ecda6': {'persuassiveness_question': 0, 'confidence_question': 0}, '63eff3ac389f8a4106938c59': {'persuassiveness_question': 0, 'confidence_question': 0}, '5cd6f56d4a405a001747f8bc': {'persuassiveness_question': 0, 'confidence_question': 0}, '5f9802a1306ea3045e8c0b43': {'persuassiveness_question': 0, 'confidence_question': 0}, '641371a980bf55f2fb89fdd1': {'persuassiveness_question': 0, 'confidence_question': 0}, '644b8b2b8ab902554e307f27': {'persuassiveness_question': 0, 'confidence_question': 0}, '6699392f3b5d44ffc688ea2e': {'persuassiveness_question': 0, 'confidence_question': 0}, '60188eb2eaec9e169fcc94a4': {'persuassiveness_question': 0, 'confidence_question': 0}, '62fb7acaf60ed51dd71d3bfb': {'persuassiveness_question': 0, 'confidence_question': 0}, '678d576bf11a61a3eaac22d4': {'persuassiveness_question': 0, 'confidence_question': 0}, '661bd9a8ac3c7e05dc6ba8ec': {'persuassiveness_question': 0, 'confidence_question': 0}, '6148af7f65d177104cc41fe5': {'persuassiveness_question': 0, 'confidence_question': 0}, '66f71769b59f14f53bbc289f': {'persuassiveness_question': 0, 'confidence_question': 0}, '66ba63f27c6488261bebe6bb': {'persuassiveness_question': 0, 'confidence_question': 0}, '5e1da370b734b411521e22ed': {'persuassiveness_question': 0, 'confidence_question': 0}, '60ddb9501708b858e5d34ff5': {'persuassiveness_question': 0, 'confidence_question': 0}, '5d399007f6d5ef00178f793a': {'persuassiveness_question': 0, 'confidence_question': 0}, '5c697649ec1fb80001c179e6': {'persuassiveness_question': 0, 'confidence_question': 0}, '5a78a1ae527fd00001464a41': {'persuassiveness_question': 0, 'confidence_question': 0}, '6094f14e5f0014a68821c2c1': {'persuassiveness_question': 0, 'confidence_question': 0}, '6051570d959c53ccacb61130': {'persuassiveness_question': 0, 'confidence_question': 0}, '66bbeb249419dc027c25d5e9': {'persuassiveness_question': 0, 'confidence_question': 0}, '6978c746783ac9de9ce737cb': {'persuassiveness_question': 0, 'confidence_question': 0}, '5bfb235518430e0001867abd': {'persuassiveness_question': 0, 'confidence_question': 0}, '5e6509ecf1ccfc27a2ad7e99': {'persuassiveness_question': 0, 'confidence_question': 0}, '60df4b638dc3a43555b7e20c': {'persuassiveness_question': 0, 'confidence_question': 0}, '66855395948d6d88d5a55521': {'persuassiveness_question': 0, 'confidence_question': 0}, '5e187c30b167cd15303f133c': {'persuassiveness_question': 0, 'confidence_question': 0}, '5e25bb2adb62ba80c1c8571a': {'persuassiveness_question': 0, 'confidence_question': 0}, '66a1561d05457dd7ec9cd3a8': {'persuassiveness_question': 0, 'confidence_question': 0}, '66ba0c45a7b789499b014744': {'persuassiveness_question': 0, 'confidence_question': 0}, '63d16c4758851c2e341702aa': {'persuassiveness_question': 0, 'confidence_question': 0}, '62aa505b26242275dbd489c3': {'persuassiveness_question': 0, 'confidence_question': 0}, '5f2018025bfa2a27c0d50916': {'persuassiveness_question': 0, 'confidence_question': 0}, '5ee9f3837b8d29017d076284': {'persuassiveness_question': 0, 'confidence_question': 0}, '562cd833733ea000111632ba': {'persuassiveness_question': 0, 'confidence_question': 0}, '5ec28a6332a7510637436a57': {'persuassiveness_question': 1, 'confidence_question': 1}, '5c97aae102cc0100123bb8a4': {'persuassiveness_question': 0, 'confidence_question': 0}, '67660c5b9df01c212f4082e3': {'persuassiveness_question': 0, 'confidence_question': 2}, '65a7e34961fd2e2798ac3d26': {'persuassiveness_question': 0, 'confidence_question': 0}, '6483648c280beabafcb3797e': {'persuassiveness_question': 0, 'confidence_question': 0}, '560aef7d01c38a00127693d3': {'persuassiveness_question': 0, 'confidence_question': 0}, '5b2450807297750001c6cc57': {'persuassiveness_question': 0, 'confidence_question': 0}, '5f4f4f4aed65db01cc168798': {'persuassiveness_question': 0, 'confidence_question': 0}, '615df60e871e541b17bc128e': {'persuassiveness_question': 0, 'confidence_question': 0}, '66c8a81f25959e5f183e2bb3': {'persuassiveness_question': 0, 'confidence_question': 0}, '601ac0440ae554365a73246b': {'persuassiveness_question': 0, 'confidence_question': 0}, '5ebe6dacb790b80008679d0e': {'persuassiveness_question': 0, 'confidence_question': 0}, '672a0a9dbcaa89f0b7763e8a': {'persuassiveness_question': 0, 'confidence_question': 0}, '6776c27223642df043c8d191': {'persuassiveness_question': 0, 'confidence_question': 0}, '60420bb25042bc00088c5376': {'persuassiveness_question': 0, 'confidence_question': 0}, '66742ef2f9183bb839ec1fbb': {'persuassiveness_question': 0, 'confidence_question': 0}, '66e01d1aef057f7e7a25bb34': {'persuassiveness_question': 0, 'confidence_question': 2}, '60ecb2f2432bec2f16c3ab9a': {'persuassiveness_question': 0, 'confidence_question': 0}, '669573801a4b4330eef51741': {'persuassiveness_question': 0, 'confidence_question': 0}, '5aafe2a9fb22320001babb3a': {'persuassiveness_question': 0, 'confidence_question': 2}, '673f091e544e7e0f26ef3e28': {'persuassiveness_question': 0, 'confidence_question': 0}, '69775cbcc1427b935d67c55f': {'persuassiveness_question': 0, 'confidence_question': 0}, '677388a4d7f566a722046006': {'persuassiveness_question': 0, 'confidence_question': 0}, '63d401296ac856e37cce7cb9': {'persuassiveness_question': 0, 'confidence_question': 0}, '5e8f9e8b20456a294f165542': {'persuassiveness_question': 0, 'confidence_question': 1}, '609911e00dd4843e39cb88ac': {'persuassiveness_question': 0, 'confidence_question': 0}, '5e08b939f9e7501c6b40c650': {'persuassiveness_question': 0, 'confidence_question': 0}, '5dd0409d9ca8a312350a4118': {'persuassiveness_question': 0, 'confidence_question': 0}, '59d395800118340001369be1': {'persuassiveness_question': 0, 'confidence_question': 0}, '5c485ca68133a40001bad6c3': {'persuassiveness_question': 0, 'confidence_question': 0}, '59775e3831c84f0001d977b7': {'persuassiveness_question': 1, 'confidence_question': 1}, '62b626b7cc2365d4e7f5c5aa': {'persuassiveness_question': 0, 'confidence_question': 0}, '54aefa06fdf99b09c01b37f4': {'persuassiveness_question': 0, 'confidence_question': 0}, '67ffe70d62f38907d35f7597': {'persuassiveness_question': 0, 'confidence_question': 0}, '573db9f8cc30e7000dc573bc': {'persuassiveness_question': 0, 'confidence_question': 0}, '5f05beccf7def406fd64c59c': {'persuassiveness_question': 0, 'confidence_question': 0}, '69722fa905921835add584e4': {'persuassiveness_question': 0, 'confidence_question': 0}, '677822a061914ddfb3089b10': {'persuassiveness_question': 0, 'confidence_question': 0}, '60cfce9352df6ebd5674e563': {'persuassiveness_question': 0, 'confidence_question': 0}, '63179a6b97e1cccbb0c28cae': {'persuassiveness_question': 0, 'confidence_question': 0}, '5aeb5c9f0f8859000190a19b': {'persuassiveness_question': 0, 'confidence_question': 0}, '60e5fa452bd56bda03990e27': {'persuassiveness_question': 0, 'confidence_question': 0}, '6978c488d801e64f18d9e371': {'persuassiveness_question': 0, 'confidence_question': 0}, '6447a16ea956d5fcabc3c3b0': {'persuassiveness_question': 0, 'confidence_question': 0}, '5c6df5298c5fd30001b83926': {'persuassiveness_question': 0, 'confidence_question': 0}, '5ecd1e4a26acf103a40f773e': {'persuassiveness_question': 0, 'confidence_question': 0}, '665a200f57097d4fb5a009b1': {'persuassiveness_question': 0, 'confidence_question': 0}, '5f7e0c5f582257095a86ff6e': {'persuassiveness_question': 0, 'confidence_question': 0}, '5af4579eb625f70001e0cfad': {'persuassiveness_question': 0, 'confidence_question': 0}, '61410966afb49e2d0d4bfaa8': {'persuassiveness_question': 0, 'confidence_question': 0}, '5ef07f0ba383185b3570273e': {'persuassiveness_question': 0, 'confidence_question': 0}, '5ba4da6f03692b00019adae6': {'persuassiveness_question': 1, 'confidence_question': 1}, '582470f7e198b200012fc7e7': {'persuassiveness_question': 0, 'confidence_question': 0}, '5ea596f614912a579c4e52e1': {'persuassiveness_question': 0, 'confidence_question': 2}, '594a8e2eeaa18e000163f6cd': {'persuassiveness_question': 0, 'confidence_question': 0}, '63ed27349738654dde4655ae': {'persuassiveness_question': 0, 'confidence_question': 0}, '6978cce6235d336e02e664bb': {'persuassiveness_question': 0, 'confidence_question': 0}, '681485b41e4f472801db525a': {'persuassiveness_question': 0, 'confidence_question': 0}, '5578b513fdf99b12e00afae9': {'persuassiveness_question': 0, 'confidence_question': 0}, '5707c536374137000ebbbc46': {'persuassiveness_question': 0, 'confidence_question': 0}, '67605adf79e021c984b722fc': {'persuassiveness_question': 0, 'confidence_question': 0}, '6968cd8ed53f5a3a484cf82a': {'persuassiveness_question': 0, 'confidence_question': 0}, '5f985f3a4bc1cf120675f408': {'persuassiveness_question': 0, 'confidence_question': 0}, '5dc16c9e317aa40c9882e73b': {'persuassiveness_question': 0, 'confidence_question': 0}, '58106d17a513590001b1ec9e': {'persuassiveness_question': 0, 'confidence_question': 2}, '571ceeb64ca277000953d1c1': {'persuassiveness_question': 1, 'confidence_question': 1}, '62e0028c1389b7b93d5becaf': {'persuassiveness_question': 0, 'confidence_question': 0}, '6093e78e30fb90f291b261f9': {'persuassiveness_question': 0, 'confidence_question': 0}, '5fd93a1e8950531f9a92074d': {'persuassiveness_question': 0, 'confidence_question': 0}, '6012d27152fa5e09eb6a29e0': {'persuassiveness_question': 0, 'confidence_question': 0}, '634691731241de3dd1b31664': {'persuassiveness_question': 0, 'confidence_question': 0}, '5f2dd11452744f1170ea3545': {'persuassiveness_question': 0, 'confidence_question': 0}, '5a93e14b89de8200013ebd26': {'persuassiveness_question': 0, 'confidence_question': 0}, '60a674515b64fa204593b1f3': {'persuassiveness_question': 0, 'confidence_question': 0}, '67ea6d0606c91f5823fc9f19': {'persuassiveness_question': 0, 'confidence_question': 1}, '6081474510faf8072e5d7072': {'persuassiveness_question': 0, 'confidence_question': 0}, '63d54f1c1ca9fabe40fe84b0': {'persuassiveness_question': 0, 'confidence_question': 0}, '66716c6d6281299acbdbbe22': {'persuassiveness_question': 0, 'confidence_question': 0}, '668e596e0af437f0fd23fac6': {'persuassiveness_question': 0, 'confidence_question': 0}, '676abc56272363fc9a095d5d': {'persuassiveness_question': 0, 'confidence_question': 0}, '59f4fa78da08940001d4e7b7': {'persuassiveness_question': 0, 'confidence_question': 0}, '67c3321da0a96b0538b4abbe': {'persuassiveness_question': 0, 'confidence_question': 0}, '601e690acaa62b2bd8d25d52': {'persuassiveness_question': 0, 'confidence_question': 0}, '5e7e72de99b9e6553dc28dcf': {'persuassiveness_question': 0, 'confidence_question': 0}, '629f33affb855dc5645075a0': {'persuassiveness_question': 0, 'confidence_question': 0}, '60b8b31eb3143c92b950deba': {'persuassiveness_question': 0, 'confidence_question': 0}, '61202fedf94fc3ac487980af': {'persuassiveness_question': 0, 'confidence_question': 0}, '5d93ab29efb8550018d5626c': {'persuassiveness_question': 0, 'confidence_question': 0}, '681e539ffde759ea416d4e94': {'persuassiveness_question': 0, 'confidence_question': 0}, '5e28e735ea776009d4d15c34': {'persuassiveness_question': 0, 'confidence_question': 1}, '5f3146c0e8a9536043a627d4': {'persuassiveness_question': 0, 'confidence_question': 0}, '63093a0415adbce573577700': {'persuassiveness_question': 0, 'confidence_question': 0}, '5f04976a0b665371cda768a3': {'persuassiveness_question': 0, 'confidence_question': 0}, '5edff4f2ffed853362263267': {'persuassiveness_question': 0, 'confidence_question': 0}, '66df5574de7eab990c808f55': {'persuassiveness_question': 0, 'confidence_question': 0}, '5f1d635678812366e39f335f': {'persuassiveness_question': 0, 'confidence_question': 0}, '60bcc05d27b1017afc3373b5': {'persuassiveness_question': 0, 'confidence_question': 0}, '595572800f4082000101fc2c': {'persuassiveness_question': 0, 'confidence_question': 0}, '6978c70248540633fbab12c1': {'persuassiveness_question': 0, 'confidence_question': 0}, '65c637e0e76b878b89b9bae2': {'persuassiveness_question': 0, 'confidence_question': 0}, '67e542ac1e6a448fc890f511': {'persuassiveness_question': 0, 'confidence_question': 0}, '6773f9ecbf8a434754bdbdab': {'persuassiveness_question': 0, 'confidence_question': 0}, '66cb2cff2ed7c15cf86a457e': {'persuassiveness_question': 0, 'confidence_question': 0}, '697be41e26e9a0ae244daf11': {'persuassiveness_question': 0, 'confidence_question': 0}, '67696e1e6cf66476feee240e': {'persuassiveness_question': 0, 'confidence_question': 0}, '62728749cc289a89544ba651': {'persuassiveness_question': 0, 'confidence_question': 0}, '6978c38e4532c2e11d102a50': {'persuassiveness_question': 0, 'confidence_question': 0}, '63d53d150a864eb06120bb88': {'persuassiveness_question': 0, 'confidence_question': 0}, '615ed3934e8c11b13593b3e8': {'persuassiveness_question': 0, 'confidence_question': 0}, '5ac25382f69e940001d95ff9': {'persuassiveness_question': 0, 'confidence_question': 1}, '67c03f6f74b9f7f603552b0a': {'persuassiveness_question': 0, 'confidence_question': 0}, '5f5899136db0c00116d2c9a5': {'persuassiveness_question': 0, 'confidence_question': 0}, '5ccf4c5db46c7000170d7f5a': {'persuassiveness_question': 0, 'confidence_question': 0}, '6658c42547c3b7e6e7d4abe8': {'persuassiveness_question': 0, 'confidence_question': 0}, '5bb627b7f047e200014ee3bd': {'persuassiveness_question': 0, 'confidence_question': 0}, '67fc2265467c0ab6f8114ce2': {'persuassiveness_question': 0, 'confidence_question': 0}, '6695a65637c2589d9d3e9f8d': {'persuassiveness_question': 0, 'confidence_question': 0}, '5f1f36c5321e4e10385f1ad8': {'persuassiveness_question': 0, 'confidence_question': 0}, '5f21ac0441a50c10f31ddf96': {'persuassiveness_question': 0, 'confidence_question': 0}, '62b05f639069fb882e8d33c7': {'persuassiveness_question': 0, 'confidence_question': 0}, '65ae2baa95efab88c481edc3': {'persuassiveness_question': 0, 'confidence_question': 0}, '6658ca018e28e3383feae8e9': {'persuassiveness_question': 0, 'confidence_question': 0}, '5ef39c45c154ff120c5e84b8': {'persuassiveness_question': 0, 'confidence_question': 0}, '5c6849dc5b27b00001a340f5': {'persuassiveness_question': 0, 'confidence_question': 1}, '56a757a95ad8d9000c970c76': {'persuassiveness_question': 0, 'confidence_question': 0}, '6978d224639f15b0bf444a8f': {'persuassiveness_question': 0, 'confidence_question': 0}, '5f1587d28ee50f036977fe26': {'persuassiveness_question': 0, 'confidence_question': 0}, '65587e7a2c6ba5c526da3041': {'persuassiveness_question': 0, 'confidence_question': 0}, '602ac80c6cf22516282a7fd3': {'persuassiveness_question': 1, 'confidence_question': 0}, '646b8ccb7cf1ebd3ca8fdc86': {'persuassiveness_question': 0, 'confidence_question': 0}, '54243231fdf99b691fb383c1': {'persuassiveness_question': 0, 'confidence_question': 0}, '5f04758d4d498c073ab4a081': {'persuassiveness_question': 0, 'confidence_question': 0}, '5c6adf2675b3d50001b8af1d': {'persuassiveness_question': 0, 'confidence_question': 0}, '6658c063dd60f6a0b5dcb002': {'persuassiveness_question': 0, 'confidence_question': 0}, '61015f63f9a351d3171a0f98': {'persuassiveness_question': 0, 'confidence_question': 0}, '5e89d10d70750d6667a2c27a': {'persuassiveness_question': 0, 'confidence_question': 0}, '5f8d77f0b348950659f1919e': {'persuassiveness_question': 0, 'confidence_question': 0}, '627a8c396169480144f11d92': {'persuassiveness_question': 0, 'confidence_question': 0}, '665b5f60fd50142f99291688': {'persuassiveness_question': 0, 'confidence_question': 0}, '668524a1a970340348138c93': {'persuassiveness_question': 1, 'confidence_question': 0}, '5d822f75d09b690017857bd4': {'persuassiveness_question': 1, 'confidence_question': 1}, '605515c8060d488db6cfddbf': {'persuassiveness_question': 2, 'confidence_question': 1}, '5eac3b9d594017087b3788af': {'persuassiveness_question': 0, 'confidence_question': 0}, '600f077a481b4705a93b13d7': {'persuassiveness_question': 0, 'confidence_question': 0}, '6655e5bdc2f455b2eec7295c': {'persuassiveness_question': 0, 'confidence_question': 0}, '5fc7affeee0fb001e857b6b1': {'persuassiveness_question': 0, 'confidence_question': 0}, '68892626185fec0f0ef5a624': {'persuassiveness_question': 0, 'confidence_question': 0}, '66912c22d42ca7c3bfa92ca2': {'persuassiveness_question': 0, 'confidence_question': 0}, '60dd30722b3a29b12a2193f8': {'persuassiveness_question': 0, 'confidence_question': 0}, '637f7c6517daaa050a1632ba': {'persuassiveness_question': 0, 'confidence_question': 0}, '5d62e141756469001948081a': {'persuassiveness_question': 0, 'confidence_question': 0}, '5a6127f2c0d8360001078f95': {'persuassiveness_question': 0, 'confidence_question': 0}, '66fc54a823b43df4c3aab628': {'persuassiveness_question': 0, 'confidence_question': 0}, '65181d02b39c0df9f861bdf7': {'persuassiveness_question': 0, 'confidence_question': 1}, '67195927c4149c2053b278da': {'persuassiveness_question': 0, 'confidence_question': 0}, '63e54f85240b204e36ec6f4b': {'persuassiveness_question': 0, 'confidence_question': 0}, '65e729bda61d35956dfd5316': {'persuassiveness_question': 0, 'confidence_question': 0}, '60dde1621f6e206dea63a7dd': {'persuassiveness_question': 0, 'confidence_question': 0}, '64835304c3d7c4fe3a12a917': {'persuassiveness_question': 0, 'confidence_ques

3251

In [15]:
failed_count = 0

for id, att_check in ids_failed_atten_checks.items():
    if att_check["persuassiveness_question"] > 1 and att_check["confidence_question"] > 1:
        failed_count += 1

failed_count

11

In [18]:
df.head()

,DataPoint_ID,Task_Group_ID,Task_Type,Question,Debate Topic,Debate 1,Debate 2,META_SAMPLE1_POLITICAL_POSITION,META_SAMPLE1_SPEAKERA,META_COMPARISONID_1,META_SAMPLE1_SPEAKERB,META_COMPARISON,META_TASK_GROUP_ID,META_COMPARISONID,META_ATTEN_CHECK_PERSUASIVENESS_ANSWER,META_ATTEN_CHECK_CONFIDENCE_ANSWER,META_SAMPLE1_DIALOGUE_CHUNK,META_PAIR_SESSION_IDS,META_SAMPLE2_POLITICAL_POSITION,Annotator1_ID,Annotator1_Response,Annotator1_Timestamp,Annotator2_ID,Annotator2_Response,Annotator2_Timestamp,Annotator3_ID,Annotator3_Response,Annotator3_Timestamp,Annotator4_ID,Annotator4_Response,Annotator4_Timestamp,Annotator5_ID,Annotator5_Response,Annotator5_Timestamp,Annotator6_ID,Annotator6_Response,Annotator6_Timestamp,Annotator7_ID,Annotator7_Response,Annotator7_Timestamp,Annotator8_ID,Annotator8_Response,Annotator8_Timestamp
0,019c5684-b730-70dd-b5f3-ca369d6a622c,412,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""How can this be done if the opport...","Speaker A: ""Would you concur that this point r...",left,human_9,1154,gpt-4o_base,"('human_9', 'human_11')",412,2064,NaN,NaN,"[{'speaker': 'human_9', 'timestamp': '2026-01-...","('XZV57F', 'OR2XBB')",left,6318acc6273e916b39a95a85,Speaker A from Debate 2,2026-02-13T10:46:55.851Z,579f55486475d400015ab683,Speaker A from Debate 1,2026-02-13T12:06:32.977Z,5e90781c06c6ee000974d087,Speaker A from Debate 1,2026-02-13T19:45:23.867Z,66066cf2a8876c1d1907732a,Speaker A from Debate 1,2026-02-14T20:40:58.661Z,5d07689bad18d40001bb73c1,Speaker A from Debate 1,2026-02-16T15:57:15.704Z,63d13c076dd249ca3a6bffbb,Speaker A from Debate 1,2026-02-18T22:06:51.931Z,5f0c94983314760efb2814c1,Speaker A from Debate 1,2026-02-21T11:14:56.612Z,NaN,NaN,NaN
1,019c5684-b730-70dd-b5f3-ca369d6a622c,412,multiple_choice,How confident are you in your choice?,Debate the trade-offs of government interventi...,"Speaker A: ""How can this be done if the opport...","Speaker A: ""Would you concur that this point r...",left,human_9,1154,gpt-4o_base,"('human_9', 'human_11')",412,2064,NaN,NaN,"[{'speaker': 'human_9', 'timestamp': '2026-01-...","('XZV57F', 'OR2XBB')",left,6318acc6273e916b39a95a85,Neutral,2026-02-13T10:46:55.851Z,579f55486475d400015ab683,Somewhat confident,2026-02-13T12:06:32.978Z,5e90781c06c6ee000974d087,Very confident,2026-02-13T19:45:23.867Z,66066cf2a8876c1d1907732a,Somewhat unsure,2026-02-14T20:40:58.661Z,5d07689bad18d40001bb73c1,Neutral,2026-02-16T15:57:15.704Z,63d13c076dd249ca3a6bffbb,Very confident,2026-02-18T22:06:51.932Z,5f0c94983314760efb2814c1,Somewhat confident,2026-02-21T11:14:56.612Z,NaN,NaN,NaN
2,019c5683-e116-71d8-8aba-b35b807dd373,173,multiple_choice,"Based only on the debate transcripts, which Sp...",(ATTENTION CHECK: ignore this datapoint and se...,(ATTENTION CHECK: ignore this datapoint and se...,(ATTENTION CHECK: ignore this datapoint and se...,left,human_11,1128,human_4,"('human_11', 'human_8')",173,867,Both Speaker As were equally persuasive,Neutral,"[{'speaker': 'human_11', 'timestamp': '2026-01...","('WTXVCV', 'RSQGNQ')",left,695c0670de1faedbce882831,Both Speaker As were equally persuasive,2026-02-13T10:51:45.569Z,5e8f8ebc09b58f28c329da6f,Both Speaker As were equally persuasive,2026-02-13T14:09:52.885Z,60e41e3e8c52dca4b19a3487,Both Speaker As were equally persuasive,2026-02-13T18:49:51.705Z,6978e5020a6d1cdb00d60fe4,Both Speaker As were equally persuasive,2026-02-14T18:01:04.033Z,64784c2bc85267b924936813,Both Speaker As were equally persuasive,2026-02-16T13:42:10.831Z,60fc3a1e0eb578aa02590e27,Both Speaker As were equally persuasive,2026-02-18T18:46:00.749Z,5f1e8aa76210d9000c23deb5,Both Speaker As were equally persuasive,2026-02-21T08:28:37.218Z,NaN,NaN,NaN
3,019c5683-e116-71d8-8aba-b35b807dd373,173,multiple_choice,How confident are you in your choice?,(ATTENTION CHECK: ignore this datapoint and se...,(ATTENTION CHECK: ignore this datapoint and se...,(ATTENTION CHECK: ignore this datapoint and se...,left,human_11,1128,human_4,"('human_11', 'human_8')",173,867,Both Speaker As were equally persuasive,Neutral,"[{'speaker': 'human_11', 'timestamp': '2026-01...","('WTXVCV', 'RSQGNQ')",left,695c0670de1faedbce882831,Neutral,2026-02-13T10:51:45.569Z,5e8f8ebc09b58f28c329da6f,Neutral,2026-02-13T14:09:52.885Z,60e41e3e8c52dca4b19a3487,Neutral,2026-02-13T18:49:51.705Z,6978e5020a6d1cdb00d60fe4,Neutral,2026-02-14T18:01:04.034Z,64784c2bc85267b924936813,Neutral,2026-02-16T13:42:10.831Z,60fc3a1e0eb578aa02590e27,Neutral,2026-02-18T18:46:00.749Z,5f1e8aa76210d9000c23deb5,Neutral,2026-02-21T08:28:37.218Z,NaN,NaN,NaN
4,019c5684-bc10-73fa-ae9c-bdda3c2e3812,417,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""Market forces ensure that the best...","Speaker A: ""Government intervention in public ...",left,gpt-4o_mas_rag,763,mistral-medium_mas,"('gpt-4o_mas_rag', 'human_6')",417,2089,NaN,NaN,"[{'speaker': 'mistral-medium_mas', 'timestamp'...","('gpt-4o_mas_rag:l__vs__mistral-medium_mas:r',...",left,5dd9a7ff98981d926df9ea18,Speaker A from Debate 1,2026-02-13T10:45:34.049Z,6761658b4037ac25f8afbd22,Speaker A from Debate 1,2026-02-13T11:48:57.224Z,5e2c8f69cad44b2bc5ce9a34,Speaker A from Debate 1,2026-02-13T14:38:04.633Z,67605337c41b9ba5ae52a0c8,Speaker A from Debate 1,2026-02-13T21:03:16.757Z,673f069497dc06b5ecbf7470,Speaker A from Debate 1,2026-02-15T11:47:01.602Z,6658ed9e2802dccba9041ca4,Speaker A from Debate 1,2026-02-17T10:05:08.725Z,677d4d04da6aea9117c478b5,Speaker A from Debate 1,2026-02-20T11:56:31.327Z,NaN,NaN,NaN

## Removing rejected ids from df

In [19]:
comparison_ids = df["META_COMPARISONID"].unique().tolist()

annotator_cols = []
for col in df.columns:
    if col.startswith("Annotator") and col.endswith('_ID'):
        base = col.replace("_ID", "")
        annotator_cols.append((
            col,                          # ID column
            base + "_Timestamp",          # Timestamp column
            base + "_Response"            # Response column
        ))
annotator_cols

[('Annotator1_ID', 'Annotator1_Timestamp', 'Annotator1_Response'),
 ('Annotator2_ID', 'Annotator2_Timestamp', 'Annotator2_Response'),
 ('Annotator3_ID', 'Annotator3_Timestamp', 'Annotator3_Response'),
 ('Annotator4_ID', 'Annotator4_Timestamp', 'Annotator4_Response'),
 ('Annotator5_ID', 'Annotator5_Timestamp', 'Annotator5_Response'),
 ('Annotator6_ID', 'Annotator6_Timestamp', 'Annotator6_Response'),
 ('Annotator7_ID', 'Annotator7_Timestamp', 'Annotator7_Response'),
 ('Annotator8_ID', 'Annotator8_Timestamp', 'Annotator8_Response')]

In [20]:
for idx, row in df.iterrows():
    for col_id, col_ts, col_resp in annotator_cols:
        if row[col_id] in rejected_ids:
            df.at[idx, col_id] = np.nan
            df.at[idx, col_ts] = np.nan
            df.at[idx, col_resp] = np.nan

In [23]:
# Accepting passed submissions and paying participants

participant_IDs = [col for col in df.columns if col.startswith("Annotator") and col.endswith("_ID")]
unique_participant_ids = pd.unique(df[participant_IDs].values.ravel())
unique_participant_ids = [pid for pid in unique_participant_ids if pd.notnull(pid)]

In [25]:
client.bulk_approve_submissions(study_id=ID, participant_ids=unique_participant_ids)

'The request to bulk approve has been made successfully.'

## Krippendorff's alpha

In [26]:
speakers = df["META_COMPARISON"].unique().tolist()

unique_speakers = set()
for s in speakers:
    unique_speakers.add(ast.literal_eval(s)[0])
    unique_speakers.add(ast.literal_eval(s)[1])

unique_speakers =  list(unique_speakers)

In [27]:
len(unique_speakers)

22

In [28]:
df = df[~df["Debate Topic"].str.contains("ATTENTION CHECK:", na=False)]

In [29]:
results_df = df[df["Question"] == "Based only on the debate transcripts, which Speaker A presented the more persuasive arguments?"].copy()
conf_df = df[df["Question"] == "How confident are you in your choice?"].copy()

We need to create a 1386x3234  matrix to compute Krippendorff's alpha

In [30]:
comparison_ids = df["META_COMPARISONID"].unique().tolist()

annotator_ids_cols = []
for col in df.columns:
    if col.startswith("Annotator") and col.endswith('_ID'):
        annotator_ids_cols.append(col)
annotator_ids_cols

['Annotator1_ID',
 'Annotator2_ID',
 'Annotator3_ID',
 'Annotator4_ID',
 'Annotator5_ID',
 'Annotator6_ID',
 'Annotator7_ID',
 'Annotator8_ID']

In [31]:
rejected_sub_ids = [x["id"] for x in rejected["results"]]

In [32]:
rejected_sub_ids

['69925375210c4bcc097cc9d3',
 '69905398aace112378a0ba8b',
 '698f0d2580f565544157acae',
 '69923415fc34882a04f2cc3d',
 '698eff7244b230c546d4f9c6']

In [33]:
annotator_ids = []

for id in annotator_ids_cols:
    annotator_ids.extend(results_df[id].unique().tolist())

for id in rejected_ids:
    if id in annotator_ids:
        annotator_ids.remove(id)

In [34]:
# map annotator ids to index in result mat
annotator_map = {annotator_ids[i]: i for i in range(len(annotator_ids))}

In [35]:
comparison_ids = df["META_COMPARISONID"].unique().tolist()

annotator_cols = []
for col in df.columns:
    if col.startswith("Annotator") and col.endswith('_ID'):
        base = col.replace("_ID", "")
        annotator_cols.append((
            col,                          # ID column
            base + "_Timestamp",          # Timestamp column
            base + "_Response"            # Response column
        ))
annotator_cols

[('Annotator1_ID', 'Annotator1_Timestamp', 'Annotator1_Response'),
 ('Annotator2_ID', 'Annotator2_Timestamp', 'Annotator2_Response'),
 ('Annotator3_ID', 'Annotator3_Timestamp', 'Annotator3_Response'),
 ('Annotator4_ID', 'Annotator4_Timestamp', 'Annotator4_Response'),
 ('Annotator5_ID', 'Annotator5_Timestamp', 'Annotator5_Response'),
 ('Annotator6_ID', 'Annotator6_Timestamp', 'Annotator6_Response'),
 ('Annotator7_ID', 'Annotator7_Timestamp', 'Annotator7_Response'),
 ('Annotator8_ID', 'Annotator8_Timestamp', 'Annotator8_Response')]

In [36]:
annotator_ids = [a for a in annotator_ids if pd.notna(a)]
annotator_ids = list(dict.fromkeys(annotator_ids))

In [37]:
annotator_map = {annotator_ids[i]: i for i in range(len(annotator_ids))}

In [38]:
result_mat = []

for idx, row in results_df.iterrows():
    row_results = []
    for j in range(len(annotator_map)):
        row_results.append(None)
    result_mat.append(row_results)

In [39]:
for row_pos, (_, row) in enumerate(results_df.iterrows()):
    for col_id, col_ts, col_resp in annotator_cols:
        if row[col_id] in rejected_ids or pd.isna(row[col_id]):
            continue
        annotator_id = row[col_id]
        mapped_idx = annotator_map.get(annotator_id)
        if mapped_idx is None:
            continue  # avoid KeyError
        result_mat[row_pos][annotator_map[annotator_id]] = row[col_resp]

In [40]:
data = np.asarray(result_mat)

In [41]:
persuasiveness_map = {
    "Speaker A from Debate 1": 1,
    "Both Speaker As were equally persuasive": 2,
    "Speaker A from Debate 2": 3,
}

In [42]:
def map_persuasion(val):
    if val is None or pd.isna(val):
        return np.nan
    return persuasiveness_map.get(val, np.nan)

numeric_data = np.vectorize(map_persuasion, otypes=[float])(data)

In [43]:
# Convert to float and set missing values (if any) to np.nan
numeric_data = numeric_data.astype(float)
numeric_data[pd.isna(data)] = np.nan

In [44]:
alpha = krippendorff.alpha(
    reliability_data=numeric_data.T,
    level_of_measurement="nominal",
)

In [45]:
print(alpha)

0.18823295288395459

### Using value counts

In [46]:
val_counts = np.zeros((len(results_df), 3))
val_counts

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], shape=(1386, 3))

In [47]:
len(results_df)

1386

In [48]:
val_counts = np.zeros((len(results_df), 3))

for idx, (_, row) in enumerate(results_df.iterrows()):
    for col_id, col_ts, col_resp in annotator_cols:
        if row[col_id] in rejected_ids or pd.isna(row[col_id]):
            continue

        if row[col_resp] == "Speaker A from Debate 1":
            val_counts[idx, 0] += 1
        elif row[col_resp] == "Speaker A from Debate 2":
            val_counts[idx, 1] += 1
        else:
            val_counts[idx, 2] += 1

In [49]:
val_counts[1:20,:]

array([[7., 0., 0.],
       [1., 3., 3.],
       [0., 7., 0.],
       [5., 0., 2.],
       [3., 3., 1.],
       [1., 2., 4.],
       [4., 3., 0.],
       [1., 6., 0.],
       [1., 6., 0.],
       [3., 4., 0.],
       [4., 3., 0.],
       [6., 0., 2.],
       [2., 4., 1.],
       [5., 1., 1.],
       [2., 5., 0.],
       [2., 5., 0.],
       [2., 3., 2.],
       [1., 5., 1.],
       [4., 1., 2.]])

In [50]:
krippendorff.alpha(value_counts=val_counts, level_of_measurement="nominal")

np.float64(0.18823295288395459)

In [146]:
val_counts = np.zeros((len(results_df), 5))
# likert_map = {
#         "Very unsure": 1,
#             "Somewhat unsure": 2,
#                 "Neutral": 3,
#                     "Somewhat confident": 4,
#                         "Very confident": 5
#                         }

for idx, (_, row) in enumerate(conf_df.iterrows()):
    for col_id, col_ts, col_resp in annotator_cols:
        if row[col_id] in rejected_ids or pd.isna(row[col_id]):
            continue

        if row[col_resp] == "Very unsure":
            val_counts[idx, 0] += 1
        elif row[col_resp] == "Somewhat unsure":
            val_counts[idx, 1] += 1
        elif row[col_resp] == "Neutral":
            val_counts[idx, 2] += 1
        elif row[col_resp] == "Somewhat confident":
            val_counts[idx, 3] += 1
        else:
            val_counts[idx, 4] += 1

In [149]:
val_counts[1:20,:]

array([[0., 0., 0., 2., 5.],
       [1., 0., 3., 3., 0.],
       [0., 0., 0., 3., 4.],
       [0., 0., 5., 2., 0.],
       [0., 0., 1., 5., 1.],
       [0., 0., 2., 4., 1.],
       [0., 0., 0., 4., 3.],
       [0., 0., 0., 5., 2.],
       [0., 1., 0., 5., 1.],
       [0., 1., 0., 5., 1.],
       [0., 0., 1., 3., 3.],
       [0., 0., 3., 4., 1.],
       [1., 1., 0., 3., 2.],
       [0., 1., 0., 4., 2.],
       [0., 0., 1., 3., 3.],
       [0., 1., 0., 4., 2.],
       [0., 0., 2., 4., 1.],
       [0., 1., 1., 2., 3.],
       [0., 1., 1., 3., 2.]])

In [148]:
krippendorff.alpha(value_counts=val_counts, level_of_measurement="nominal")

np.float64(0.03940373734443603)

In [47]:
annotator_cols = [col for col in results_df.columns if col.endswith('_Response')]

# Only consider rows where the Question matches the target
target_rows = results_df["Question"] == "Based only on the debate transcripts, which Speaker A presented the more persuasive arguments?"

def count_sample1(row):
    return sum([
        1 if val == "Speaker A from Debate 1" else
        0.5 if val == "Both Speaker As were equally persuasive" else
        0
        for val in row
    ])

def count_sample2(row):
    return sum([
        1 if val == "Speaker A from Debate 2" else
        0.5 if val == "Both Speaker As were equally persuasive" else
        0
        for val in row
    ])

results_df.loc[target_rows, 'sample1_win_count'] = results_df.loc[target_rows, annotator_cols].apply(count_sample1, axis=1)
results_df.loc[target_rows, 'sample2_win_count'] = results_df.loc[target_rows, annotator_cols].apply(count_sample2, axis=1)

results_df.head()

,DataPoint_ID,Task_Group_ID,Task_Type,Question,Debate Topic,Debate 1,Debate 2,META_SAMPLE1_POLITICAL_POSITION,META_SAMPLE1_SPEAKERA,META_COMPARISONID_1,META_SAMPLE1_SPEAKERB,META_COMPARISON,META_TASK_GROUP_ID,META_COMPARISONID,META_ATTEN_CHECK_PERSUASIVENESS_ANSWER,META_ATTEN_CHECK_CONFIDENCE_ANSWER,META_SAMPLE1_DIALOGUE_CHUNK,META_PAIR_SESSION_IDS,META_SAMPLE2_POLITICAL_POSITION,Annotator1_ID,Annotator1_Response,Annotator1_Timestamp,Annotator2_ID,Annotator2_Response,Annotator2_Timestamp,Annotator3_ID,Annotator3_Response,Annotator3_Timestamp,Annotator4_ID,Annotator4_Response,Annotator4_Timestamp,Annotator5_ID,Annotator5_Response,Annotator5_Timestamp,Annotator6_ID,Annotator6_Response,Annotator6_Timestamp,Annotator7_ID,Annotator7_Response,Annotator7_Timestamp,Annotator8_ID,Annotator8_Response,Annotator8_Timestamp,sample1_win_count,sample2_win_count
0,019c5684-b730-70dd-b5f3-ca369d6a622c,412,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""How can this be done if the opport...","Speaker A: ""Would you concur that this point r...",left,human_9,1154,gpt-4o_base,"('human_9', 'human_11')",412,2064,NaN,NaN,"[{'speaker': 'human_9', 'timestamp': '2026-01-...","('XZV57F', 'OR2XBB')",left,6318acc6273e916b39a95a85,Speaker A from Debate 2,2026-02-13T10:46:55.851Z,579f55486475d400015ab683,Speaker A from Debate 1,2026-02-13T12:06:32.977Z,5e90781c06c6ee000974d087,Speaker A from Debate 1,2026-02-13T19:45:23.867Z,66066cf2a8876c1d1907732a,Speaker A from Debate 1,2026-02-14T20:40:58.661Z,5d07689bad18d40001bb73c1,Speaker A from Debate 1,2026-02-16T15:57:15.704Z,63d13c076dd249ca3a6bffbb,Speaker A from Debate 1,2026-02-18T22:06:51.931Z,5f0c94983314760efb2814c1,Speaker A from Debate 1,2026-02-21T11:14:56.612Z,NaN,NaN,NaN,6.0,1.0
4,019c5684-bc10-73fa-ae9c-bdda3c2e3812,417,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""Market forces ensure that the best...","Speaker A: ""Government intervention in public ...",left,gpt-4o_mas_rag,763,mistral-medium_mas,"('gpt-4o_mas_rag', 'human_6')",417,2089,NaN,NaN,"[{'speaker': 'mistral-medium_mas', 'timestamp'...","('gpt-4o_mas_rag:l__vs__mistral-medium_mas:r',...",left,5dd9a7ff98981d926df9ea18,Speaker A from Debate 1,2026-02-13T10:45:34.049Z,6761658b4037ac25f8afbd22,Speaker A from Debate 1,2026-02-13T11:48:57.224Z,5e2c8f69cad44b2bc5ce9a34,Speaker A from Debate 1,2026-02-13T14:38:04.633Z,67605337c41b9ba5ae52a0c8,Speaker A from Debate 1,2026-02-13T21:03:16.757Z,673f069497dc06b5ecbf7470,Speaker A from Debate 1,2026-02-15T11:47:01.602Z,6658ed9e2802dccba9041ca4,Speaker A from Debate 1,2026-02-17T10:05:08.725Z,677d4d04da6aea9117c478b5,Speaker A from Debate 1,2026-02-20T11:56:31.327Z,NaN,NaN,NaN,7.0,0.0
8,019c5683-7bc9-737c-98f5-9d58923d45e6,60,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""Resentment and alienisation within...","Speaker A: ""Are taxes the only way to develop ...",right,human_6,988,grok-3_mas,"('human_6', 'human_12')",60,304,NaN,NaN,"[{'speaker': 'human_6', 'timestamp': '2026-01-...","('LU5JFB', 'VIJPFB')",right,5e908233a1ea4d013e973b75,Both Speaker As were equally persuasive,2026-02-13T11:15:52.377Z,653d14bc14d143d888af01b0,Speaker A from Debate 2,2026-02-13T13:26:19.093Z,67be393ad49f9deccf6ddd22,Speaker A from Debate 2,2026-02-13T17:26:28.900Z,5e64da5ac34e832466061bf8,Speaker A from Debate 2,2026-02-14T12:59:43.415Z,671f96e923e76ff949ad6cbc,Both Speaker As were equally persuasive,2026-02-16T10:12:34.555Z,60ff1c49e50b11c8d19c33dc,Speaker A from Debate 1,2026-02-18T12:35:04.636Z,569a54a5217ca2000cc93db0,Both Speaker As were equally persuasive,2026-02-20T19:46:57.078Z,NaN,NaN,NaN,2.5,4.5
10,019c5684-b2c9-734b-a917-fa2e76eeaff7,408,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""Governments often struggle to meas...","Speaker B: ""Unlike the NHS, which leaves the m...",right,human_10,899,gpt-4o_base,"('human_10', 'grok-3_mas_rag')",408,2040,NaN,NaN,"[{'speaker': 'human_10', 'timestamp': '2026-01...","('7BKBI8', 'grok-3_mas_rag:r__vs__grok-3_mas:l')",right,574da26c7f1e770007f42d11,Speaker A from Debate 2,2026-02-13T10:43:22.640Z,63cff313cbe2429e25af069c,Speaker A from Debate 2,2026-02-13T11:38:58.929Z,6813af32a57bc43516a6101c,Speaker A from Debate 2,2026-02-13T14:21:10.623Z,676164b56c5438f11c393b6c,Speaker A from Debate 2,2026-02-13T20:27:21.391Z,598307925f25e90001263e05,Speaker A from Debate 2,2026-02-15T10:06:36.739Z,5f526d22e44ff151493ad4e9,Speaker A from Debate 2,2026-02-17T07:17:12.694Z,5ac289f6e1546900019be3e4,Speaker A from Debate 2,2026-02-20T09:11:44.716Z,NaN,NaN,NaN,0.0,7.0
12,019c5683-84d1-75cf-b5fa-cb13c872e2b1,71,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""Did you see the current job market...","Speaker A: ""Scandinavian countries have implem...",left,human_4,1004,human_13,"('human_4', 'human_2')",71,356,NaN,NaN,"[{'speaker': 'human_13', 'timestamp': '2026-01...","('KNI0QV', 'X12MFO')",left,59025280d17178000141a7dd,Speaker A from Debate 1,2026-02-13T11:29:21.761Z,60eda0b5e8f579f6a73d0f6b,Speaker A from Debate 1,2026-02-13T13:33:53.173Z,5f7894fb06b78643c9bcdd44,Both Speaker As were equally persuasive,2026-02-13T18:10:11.034Z,5b295f60bbd4880001117976,Speaker A from Debate 1,2026-02-14T15:23:48.472Z,665a200f57097d4fb5a009b1,Speaker A from Debate 1,2026-02-16T21:09:12.415Z,623486db68625ae062c7303c,Speaker A from Debate 1,2026-02-19T16:42:36.013Z,6658be4c729ddb9f58912db1,Both Speaker As were equally persuasive,2026-02-21T22:13:53.900Z,NaN,NaN,NaN,6.0,1.0

In [48]:
for col in ["average_confidence", "std_confidence", "confidence_values"]:
    if col in results_df.columns:
        results_df.drop(col, axis=1, inplace=True)

In [49]:
likert_map = {
        "Very unsure": 1,
            "Somewhat unsure": 2,
                "Neutral": 3,
                    "Somewhat confident": 4,
                        "Very confident": 5
                        }


# Select annotator response columns
annotator_cols = [col for col in conf_df.columns if col.endswith('_Response')]

# Map likert responses to numbers
conf_df_numeric = conf_df[annotator_cols].replace(likert_map)

# Create a column with list of confidence values (excluding NaN)
conf_df["confidence_values"] = conf_df_numeric.apply(
    lambda row: [v for v in row if pd.notna(v)], axis=1
)

# Compute mean and std for each row in conf_df
conf_df["average_confidence"] = conf_df_numeric.mean(axis=1)
conf_df["std_confidence"] = conf_df_numeric.std(axis=1)

# Merge confidence columns into results_df by comparison ID
results_df = results_df.merge(
    conf_df[["META_COMPARISONID", "average_confidence", "std_confidence", "confidence_values"]],
    on="META_COMPARISONID",
    how="left"
)

results_df.head()

,DataPoint_ID,Task_Group_ID,Task_Type,Question,Debate Topic,Debate 1,Debate 2,META_SAMPLE1_POLITICAL_POSITION,META_SAMPLE1_SPEAKERA,META_COMPARISONID_1,META_SAMPLE1_SPEAKERB,META_COMPARISON,META_TASK_GROUP_ID,META_COMPARISONID,META_ATTEN_CHECK_PERSUASIVENESS_ANSWER,META_ATTEN_CHECK_CONFIDENCE_ANSWER,META_SAMPLE1_DIALOGUE_CHUNK,META_PAIR_SESSION_IDS,META_SAMPLE2_POLITICAL_POSITION,Annotator1_ID,Annotator1_Response,Annotator1_Timestamp,Annotator2_ID,Annotator2_Response,Annotator2_Timestamp,Annotator3_ID,Annotator3_Response,Annotator3_Timestamp,Annotator4_ID,Annotator4_Response,Annotator4_Timestamp,Annotator5_ID,Annotator5_Response,Annotator5_Timestamp,Annotator6_ID,Annotator6_Response,Annotator6_Timestamp,Annotator7_ID,Annotator7_Response,Annotator7_Timestamp,Annotator8_ID,Annotator8_Response,Annotator8_Timestamp,sample1_win_count,sample2_win_count,average_confidence,std_confidence,confidence_values
0,019c5684-b730-70dd-b5f3-ca369d6a622c,412,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""How can this be done if the opport...","Speaker A: ""Would you concur that this point r...",left,human_9,1154,gpt-4o_base,"('human_9', 'human_11')",412,2064,NaN,NaN,"[{'speaker': 'human_9', 'timestamp': '2026-01-...","('XZV57F', 'OR2XBB')",left,6318acc6273e916b39a95a85,Speaker A from Debate 2,2026-02-13T10:46:55.851Z,579f55486475d400015ab683,Speaker A from Debate 1,2026-02-13T12:06:32.977Z,5e90781c06c6ee000974d087,Speaker A from Debate 1,2026-02-13T19:45:23.867Z,66066cf2a8876c1d1907732a,Speaker A from Debate 1,2026-02-14T20:40:58.661Z,5d07689bad18d40001bb73c1,Speaker A from Debate 1,2026-02-16T15:57:15.704Z,63d13c076dd249ca3a6bffbb,Speaker A from Debate 1,2026-02-18T22:06:51.931Z,5f0c94983314760efb2814c1,Speaker A from Debate 1,2026-02-21T11:14:56.612Z,NaN,NaN,NaN,6.0,1.0,3.714286,1.112697,"[3, 4, 5, 2, 3, 5, 4]"
1,019c5684-bc10-73fa-ae9c-bdda3c2e3812,417,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""Market forces ensure that the best...","Speaker A: ""Government intervention in public ...",left,gpt-4o_mas_rag,763,mistral-medium_mas,"('gpt-4o_mas_rag', 'human_6')",417,2089,NaN,NaN,"[{'speaker': 'mistral-medium_mas', 'timestamp'...","('gpt-4o_mas_rag:l__vs__mistral-medium_mas:r',...",left,5dd9a7ff98981d926df9ea18,Speaker A from Debate 1,2026-02-13T10:45:34.049Z,6761658b4037ac25f8afbd22,Speaker A from Debate 1,2026-02-13T11:48:57.224Z,5e2c8f69cad44b2bc5ce9a34,Speaker A from Debate 1,2026-02-13T14:38:04.633Z,67605337c41b9ba5ae52a0c8,Speaker A from Debate 1,2026-02-13T21:03:16.757Z,673f069497dc06b5ecbf7470,Speaker A from Debate 1,2026-02-15T11:47:01.602Z,6658ed9e2802dccba9041ca4,Speaker A from Debate 1,2026-02-17T10:05:08.725Z,677d4d04da6aea9117c478b5,Speaker A from Debate 1,2026-02-20T11:56:31.327Z,NaN,NaN,NaN,7.0,0.0,4.714286,0.48795,"[5, 4, 4, 5, 5, 5, 5]"
2,019c5683-7bc9-737c-98f5-9d58923d45e6,60,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""Resentment and alienisation within...","Speaker A: ""Are taxes the only way to develop ...",right,human_6,988,grok-3_mas,"('human_6', 'human_12')",60,304,NaN,NaN,"[{'speaker': 'human_6', 'timestamp': '2026-01-...","('LU5JFB', 'VIJPFB')",right,5e908233a1ea4d013e973b75,Both Speaker As were equally persuasive,2026-02-13T11:15:52.377Z,653d14bc14d143d888af01b0,Speaker A from Debate 2,2026-02-13T13:26:19.093Z,67be393ad49f9deccf6ddd22,Speaker A from Debate 2,2026-02-13T17:26:28.900Z,5e64da5ac34e832466061bf8,Speaker A from Debate 2,2026-02-14T12:59:43.415Z,671f96e923e76ff949ad6cbc,Both Speaker As were equally persuasive,2026-02-16T10:12:34.555Z,60ff1c49e50b11c8d19c33dc,Speaker A from Debate 1,2026-02-18T12:35:04.636Z,569a54a5217ca2000cc93db0,Both Speaker As were equally persuasive,2026-02-20T19:46:57.078Z,NaN,NaN,NaN,2.5,4.5,3.142857,1.069045,"[4, 3, 4, 4, 3, 3, 1]"
3,019c5684-b2c9-734b-a917-fa2e76eeaff7,408,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""Governments often struggle to meas...","Speaker B: ""Unlike the NHS, which leaves the m...",right,human_10,899,gpt-4o_base,"('human_10', 'grok-3_mas_rag')",408,2040,NaN,NaN,"[{'speaker': 'human_10', 'timestamp': '2026-01...","('7BKBI8', 'grok-3_mas_rag:r__vs__grok-3_mas:l')",right,574da26c7f1e770007f42d11,Speaker A from Debate 2,2026-02-13T10:43:22.640Z,63cff313cbe2429e25af069c,Speaker A from Debate 2,2026-02-13T11:38:58.929Z,6813af32a57bc43516a6101c,Speaker A from Debate 2,2026-02-13T14:21:10.623Z,676164b56c5438f11c393b6c,Speaker A from Debate 2,2026-02-13T20:27:21.391Z,598307925f25e90001263e05,Speaker A from Debate 2,2026-02-15T10:06:36.739Z,5f526d22e44ff151493ad4e9,Speaker A from Debate 2,2026-02-17T07:17:12.694Z,5ac289f6e1546900019be3e4,Speaker A from Debate 2,2026-02-20T09:11:44.716Z,NaN,NaN,NaN,0.0,7.0,4.571429,0.534522,"[5, 5, 4, 5, 4, 4, 5]"
4,019c5683-84d1-75cf-b5fa-cb13c872e2b1,71,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""Did you see the current job market...","Speaker A: ""Scandinavian countries have implem...",left,human_4,1004,human_13,"('human_4', 'human_2')",71,356,NaN,NaN,"[{'speaker': 'human_13', 'timestamp': '2026-01...","('KNI0QV', 'X12MFO')",left,59025280d17178000141a7dd,Speaker A from Debate 1,2026-02-13T11:29:21.761Z,60eda0b5e8f579f6a73d0f6b,Speaker A from Debate 1,2026-02-13T13:33:53.173Z,5f7894fb06b78643c9bcdd44,Both Speaker As were equally persuasive,2026-02-13T18:10:11.034Z,5b295f60bbd4880001117976,Speaker A from Debate 1,2026-02-14T15:23:48.472Z,665a200f57097d4fb5a009b1,Speaker A from Debate 1,2026-02-16T21:09:12.415Z,623486db68625ae062c7303c,Speaker A from Debate 1,2026-02-19T16:42:36.013Z,6658be4c729ddb9f58912db1,Both Speaker As were equally persuasive,2026-02-21T22:13:53.900Z,NaN,NaN,NaN,6.0,1.0,3.285714,0.48795,"[3, 3, 3, 4, 3, 3, 4]"

In [50]:
comparison_ids = df["META_COMPARISONID"].unique().tolist()

annotator_cols = []
for col in df.columns:
    if col.startswith("Annotator") and col.endswith('_ID'):
        base = col.replace("_ID", "")
        annotator_cols.append((
            col,                          # ID column
            base + "_Timestamp",          # Timestamp column
            base + "_Response"            # Response column
        ))
annotator_cols

[('Annotator1_ID', 'Annotator1_Timestamp', 'Annotator1_Response'),
 ('Annotator2_ID', 'Annotator2_Timestamp', 'Annotator2_Response'),
 ('Annotator3_ID', 'Annotator3_Timestamp', 'Annotator3_Response'),
 ('Annotator4_ID', 'Annotator4_Timestamp', 'Annotator4_Response'),
 ('Annotator5_ID', 'Annotator5_Timestamp', 'Annotator5_Response'),
 ('Annotator6_ID', 'Annotator6_Timestamp', 'Annotator6_Response'),
 ('Annotator7_ID', 'Annotator7_Timestamp', 'Annotator7_Response'),
 ('Annotator8_ID', 'Annotator8_Timestamp', 'Annotator8_Response')]

In [51]:
annotator_cols = [y for x in annotator_cols for y in x]
annotator_cols

['Annotator1_ID',
 'Annotator1_Timestamp',
 'Annotator1_Response',
 'Annotator2_ID',
 'Annotator2_Timestamp',
 'Annotator2_Response',
 'Annotator3_ID',
 'Annotator3_Timestamp',
 'Annotator3_Response',
 'Annotator4_ID',
 'Annotator4_Timestamp',
 'Annotator4_Response',
 'Annotator5_ID',
 'Annotator5_Timestamp',
 'Annotator5_Response',
 'Annotator6_ID',
 'Annotator6_Timestamp',
 'Annotator6_Response',
 'Annotator7_ID',
 'Annotator7_Timestamp',
 'Annotator7_Response',
 'Annotator8_ID',
 'Annotator8_Timestamp',
 'Annotator8_Response']

In [55]:
for col in annotator_cols:
    if col in results_df.columns:
        results_df.drop(col, axis=1, inplace=True)

remove_cols = ["META_ATTEN_CHECK_PERSUASIVENESS_ANSWER","META_ATTEN_CHECK_CONFIDENCE_ANSWER"]
for col in remove_cols:
    if col in results_df.columns:
        results_df.drop(col, axis=1, inplace=True)

In [56]:
results_df.head()

,DataPoint_ID,Task_Group_ID,Task_Type,Question,Debate Topic,Debate 1,Debate 2,META_SAMPLE1_POLITICAL_POSITION,META_SAMPLE1_SPEAKERA,META_COMPARISONID_1,META_SAMPLE1_SPEAKERB,META_COMPARISON,META_TASK_GROUP_ID,META_COMPARISONID,META_SAMPLE1_DIALOGUE_CHUNK,META_PAIR_SESSION_IDS,META_SAMPLE2_POLITICAL_POSITION,sample1_win_count,sample2_win_count,average_confidence,std_confidence,confidence_values
0,019c5684-b730-70dd-b5f3-ca369d6a622c,412,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""How can this be done if the opport...","Speaker A: ""Would you concur that this point r...",left,human_9,1154,gpt-4o_base,"('human_9', 'human_11')",412,2064,"[{'speaker': 'human_9', 'timestamp': '2026-01-...","('XZV57F', 'OR2XBB')",left,6.0,1.0,3.714286,1.112697,"[3, 4, 5, 2, 3, 5, 4]"
1,019c5684-bc10-73fa-ae9c-bdda3c2e3812,417,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""Market forces ensure that the best...","Speaker A: ""Government intervention in public ...",left,gpt-4o_mas_rag,763,mistral-medium_mas,"('gpt-4o_mas_rag', 'human_6')",417,2089,"[{'speaker': 'mistral-medium_mas', 'timestamp'...","('gpt-4o_mas_rag:l__vs__mistral-medium_mas:r',...",left,7.0,0.0,4.714286,0.48795,"[5, 4, 4, 5, 5, 5, 5]"
2,019c5683-7bc9-737c-98f5-9d58923d45e6,60,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""Resentment and alienisation within...","Speaker A: ""Are taxes the only way to develop ...",right,human_6,988,grok-3_mas,"('human_6', 'human_12')",60,304,"[{'speaker': 'human_6', 'timestamp': '2026-01-...","('LU5JFB', 'VIJPFB')",right,2.5,4.5,3.142857,1.069045,"[4, 3, 4, 4, 3, 3, 1]"
3,019c5684-b2c9-734b-a917-fa2e76eeaff7,408,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""Governments often struggle to meas...","Speaker B: ""Unlike the NHS, which leaves the m...",right,human_10,899,gpt-4o_base,"('human_10', 'grok-3_mas_rag')",408,2040,"[{'speaker': 'human_10', 'timestamp': '2026-01...","('7BKBI8', 'grok-3_mas_rag:r__vs__grok-3_mas:l')",right,0.0,7.0,4.571429,0.534522,"[5, 5, 4, 5, 4, 4, 5]"
4,019c5683-84d1-75cf-b5fa-cb13c872e2b1,71,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""Did you see the current job market...","Speaker A: ""Scandinavian countries have implem...",left,human_4,1004,human_13,"('human_4', 'human_2')",71,356,"[{'speaker': 'human_13', 'timestamp': '2026-01...","('KNI0QV', 'X12MFO')",left,6.0,1.0,3.285714,0.48795,"[3, 3, 3, 4, 3, 3, 4]"

In [54]:
results_df.to_csv("data/subjective-persuasiveness-prolific-results.csv", sep="|")